### ISSUE TITLE
NTR dilution assay

### ISSUE THREAD

**Issue by dsiegele** [evidenceontology/evidenceontology#104]
term name: dilution assay
def: A sensitivity/resistance assay used to determine the activity of a solution by exposing an indicator culture or organism to a series of dilutions and determining the lowest concentration that elicits a biological response. For chemicals, bacteriocins, or phage, the indicator culture is typically present in a soft-agar layer on top of nutrient agar and a small quantity of each dilution is spotted onto the soft agar overlay. 

synonyms: spot assay; critical dilution assay

Reference:
Parente, E., Brienza, C., Moles, M. and Ricciardi, A. (1995) A comparison of methods for the measurement of bacteriocin activity J. Microbiol. Methods 22(1):95-108.
doi:10.1016/0167-7012(94)00068-I

**Comment by nsuvarnaiari** [comment]
Hi Debby,

The term has been added in eco-edit.owl file. 
ECO_0005800 (dilution assay evidence)
SubClassOf (obo:ECO_0000002 - direct assay evidence)

Thanks,
Suvvi
