### ISSUE TITLE
Manual Assertion codes for enzyme assay and cell transfections

### ISSUE THREAD

**Issue by ukemi** [evidenceontology/evidenceontology#107]
Could we please have two new evidence codes?

enzyme assay evidence used in manual assertion
cell transfection experiment evidence used in manual assertion

**Comment by nsuvarnaiari** [comment]
Hi David,

These terms have been added to our eco-edit.owl file. They will be public once we do a release. 
enzyme assay evidence used in manual assertion  -  ECO:0005801
cell transfection experiment evidence used in manual assertion -  ECO:0005802

Thanks,
Suvvi

**Comment by ukemi** [comment]
Hi Suvvi,

Thanks for the terms. What is your release schedule?

-David
