### ISSUE TITLE
2 new codes

### ISSUE THREAD

**Issue by ukemi** [evidenceontology/evidenceontology#108]
Could I please get two new codes?

immunofluorescence evidence used in manual assertion

yeast 2-hybrid evidence used in manual assertion

Thanks!

-David

**Comment by nsuvarnaiari** [comment]
Hi David, 

These new terms have been added to our eco-edit.owl file. They will be public once we make a release. 
yeast 2-hybrid evidence used in manual assertion - ECO:0005805
immunofluorescence evidence used in manual assertion- ECO:0005804

You asked me in your previous ticket about our release cycle. Our release schedules have been little irregular but now we are more committed to doing releases every first Friday of the month.

Thanks,
Suvvi
