### ISSUE TITLE
Request for eco-gaf mapping file

### ISSUE THREAD

**Issue by ukemi** [evidenceontology/evidenceontology#109]
Currently there is a file for mapping the GOC gaf codes to ECO codes. It would be nice to have tab-delimited text file for the opposite direction, containing all of the ECO codes and the gaf codes to which they map?
For example,
ECO:0001181 <tab> IPI

-D

**Comment by nsuvarnaiari** [comment]
David,

I have added the eco-gaf-mapping file in our repository, https://github.com/evidenceontology/evidenceontology. 

Thanks,
Suvvi

**Comment by loricorbani** [comment]
[eco.txt](https://github.com/evidenceontology/evidenceontology/files/502940/eco.txt)

What MGD needs is a simple tab-delimited file of ECO/3-letter equivalent that provides *all* of the ECO/3-letter equivalents, not just the top nodes.

See that attached file.  

I am generating this file by reading the eco.obo file, the xrefs, the synonyms.

But it would be great if this file could be supplied at your end so the software engineers that need to use this information do not have to keep writing scripts that pull out this information in a more usable form.  I expect that other GO groups will need this file as well.

**Comment by loricorbani** [comment]
I looks like this text file is not showing line breaks.

It should look like this:

ECO:xxxx   EXP
ECO:xxxx   IEA
ECO:xxxx  EXP
.etc.
