### ISSUE TITLE
NTR: motility assay

### ISSUE THREAD

**Issue by KristenKC** [evidenceontology/evidenceontology#110]
Definition: An assay that’s used to determine the motility of a cell or cells. 

This would be a parent term that could be used when there is not a specific term for the assay. And it’s also a way to group together different motility assay.

**Comment by nsuvarnaiari** [comment]
Hi Kristen,

I have added the term in our eco-edit.owl file. It will be public once we do a release.
motility assay evidence - ECO:0005803
is_a : direct assay evidence (ECO:0000002)

Thanks,
Suvvi
