### ISSUE TITLE
Please provide a full eco-to-3 letter translation in tab-delimited format

### ISSUE THREAD

**Issue by loricorbani** [evidenceontology/evidenceontology#111]
What MGD needs is a simple tab-delimited file of ECO/3-letter equivalent that provides all of the ECO/3-letter equivalents, not just the top nodes.

See that attached file.

[eco.txt](https://github.com/evidenceontology/evidenceontology/files/508254/eco.txt

I am generating this file by reading the eco.obo file, the xrefs, the synonyms.  It would be great if this could be provided by the Evidence Ontology group and we could just pick up this tab-delimited file.  We don't need the entire Ontology.  We just need this piece.

**Comment by nsuvarnaiari** [comment]
#109 
Hi,

We will work on it and add the file to our repository soon.
Thanks for providing the details, that helps.

Thanks,
Suvvi

**Comment by loricorbani** [comment]
thank you.

**Comment by rctauber** [comment]
@loricorbani Was this file generated by a script or compiled manually?

**Comment by loricorbani** [comment]
by a script that I wrote:

https://github.com/mgijax/goload/blob/master/lib/ecolib.py

**Comment by rctauber** [comment]
@loricorbani 
Here's a tab-delimited file that was requested. There is some overlap, especially with EXP, since the classes mapped to some (IDA, for example) are subclasses of the term mapped to EXP. Please let me know if this works for you, or if you would prefer a filtered list with no redundancy.

[File Here](https://raw.githubusercontent.com/rctauber/ecogo-list/master/eco-go.txt)

**Comment by loricorbani** [comment]
thanks.  I have downloaded the file, and will take a look.

**Comment by rctauber** [comment]
@loricorbani Here is a list filtered for redundancy as well, just in case.
[File Here](https://raw.githubusercontent.com/rctauber/ecogo-list/master/eco-go-filter.txt)

**Comment by loricorbani** [comment]
I think that the we need to know which ECO is the "master" or "default" to a given 3-letter code.

That is, "IPI" has 26 ECO ids...but only ECO:0000353 is the "default".

I cannot tell this from the new file.  Can you add a default field to each row?  If "default", then this will be the "master"/top-level field for that 3-letter code?

We need to be able to swing in both directions...ECO-> 3 letter, but also 3-letter -> ECO.

Thanks.

**Comment by rctauber** [comment]
I added in the defaults in the filtered list. Let me know if this works, alternatively I could list the defaults at the top.

[File Here](https://github.com/rctauber/ecogo-list/blob/master/eco-go-filter.txt)

**Comment by loricorbani** [comment]
Can you make the "Default" the 3rd field, not the 2nd field?

field 1 : ECO
field 2 : 3 letter code
field 3 : Default or null

Thanks.

**Comment by loricorbani** [comment]
Also, we do not need to the "GO_REFS" in this file.

Thanks.

**Comment by rctauber** [comment]
@loricorbani No problem. Removed GO_REFS and put Default in 3rd column [here](https://github.com/rctauber/ecogo-list/blob/master/eco-go-filter.txt).

**Comment by loricorbani** [comment]
Rebecca,
This looks great!  I will change my code to use this new file.  Thank you so much.  This is so helpful.
Lori

**Comment by loricorbani** [comment]
I am going to have David Hill take a look as well.  Thanks again!

**Comment by cmungall** [comment]
Everyone should use this: http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

ECO editors - can we make a more prominent link to this on the front page

If there is desire to have a pre-inferred version of this, this is fine but it should follow the same format, be in the same folder in github, and have a similar PURL

**Comment by loricorbani** [comment]
Chris,

This file is insufficient for our needs.  We had to write a specific obo parser so we could detect all relationships.

We need to translate:

ECO -> 3 letter code

3 letter code -> ECO default

I requested and am testing a new tab-delimited file from Evidence Ontology (Rebecca…many thanks):

https://github.com/rctauber/ecogo-list/blob/master/eco-go-filter.txt

This file is what MGD needed.  Hopefully it will help others too.

Thanks.
Lori

**Comment by mchibucos** [comment]
Thank you for the comment, Chris. @loricorbani were made aware of the gaf-eco-mapping.txt file previously. That is the file that all users should be using. But they wanted something different, for whatever reason, so we helped them. They explicitly requested a file that followed a different format. I do not think the file that they requested would be of broad use, and I think that having it in the repo next to the original gaf would only serve to confuse users. So we created it to help them with a specific application. That said, yes, it should have been placed in ECO repo and just labeled with a bunch of warnings, in my opinion. (I might still create a subdir for such types of custom files.)  I haven't had time to finish my reply to @loricorbani explaining the gaf file - there may be some confusion about the use of "default" and GO refs - but I am sending this reply first, before this thread gets too off track.

**Comment by loricorbani** [comment]
Marcus,

The reason why we asked for this file is because we are loading GO_Noctua/GPAD data into MGD and need to translate any ECO to its proper 3 letter code.

Then, we need to go back the other way…and generate both a GPAD and a GAF file…to send back to GO.

GPAD requires ECO.  GAF requires 3 letter code.  So, we need to translate things in both directions in our pipeline.

ECO -> 3 letter code

3 letter code -> default ECO

The new file really helps us because it eliminates the need for us to write code to take the obo file and generate this ourselves.  And since you are the keepers of the Evidence Ontology, it seems to make sense to ask you to provide this translation.

I expect that other groups that are loading GO_Noctua/GPAD may also find this useful.

We really appreciate your efforts in supplying this file and that it will be updated along with any changes to the Evidence Ontology.

Our GO_Noctua/GPAD loading will be run weekly (if not daily), in order to help facilitate our GO Curators for using GO_Noctua.

Many thanks.
Lori

**Comment by cmungall** [comment]
I believe the GO GPAD->GAF converter does this for you. cc @tonysawfordebi

**Comment by cmungall** [comment]
Also everyone be sure to read the docs at the top of http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

This actually maps tuples of `(code,ref)` to ECO classes. This doesn't generally affect Noctua annotation now (the ref code is generally blank for experimental annotations), but it may in future

```
# Permanent URL of this document:
#  http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt
#
# Always use this URL
#
# About:
# This mapping translates evidence codes used in a GAF to a specific evidence type in ECO
#
# Each mapping is from a pair:
#  1. GAF evidence code (e.g. IEA)
#  2. A GO_REF (found in the GAF Reference column)
# to a class identifier in ECO (http://purl.obolibrary.org/obo/eco.owl)
#  3. ECO ID
#
# If the value 'Default' is in column 2 then this mapping is used if
# no more specific mapping can be found
#
# This document consists of these comments (after #s) followed by
# a set of mappings, each represented as the above 3 columns separated by tabs
#
# For example an IEA supported by
#  http://www.geneontology.org/cgi-bin/references.cgi#GO_REF:0000002
# maps to ECO:0000256 'match to sequence model evidence used in automatic assertion'
#
# To request changes in the mappings, submit an item to
#  https://code.google.com/p/evidenceontology/issues/list
#
```

(oops, looks like URL of tracker needs changed)

**Comment by tonysawfordebi** [comment]
We (GOA) also have the need to be able to map ECO codes to their equivalent GO evidence code, so I created a script to do that based on the structure of the ECO graph and the GOECO xrefs.

I'm not convinced that the mappings in the new file are 100% correct, because it contains these entries:

ECO:0001828	(visual sequence inspection evidence) => IC
ECO:0005611	(inference from experimental data evidence) => IDA
ECO:0005612	(inference from phenotype manipulation evidence) => IPI
ECO:0005613	(inference by association of genotype from phenotype) => EXP

These are raw evidence types, and are thus not directly usable in GO annotations. Indeed, it appears that the "... used in manual assertion" forms of these terms do not currently exist, and so should probably be added to the ontology.

**Comment by mchibucos** [comment]
Thanks @tonysawfordebi for these comments. These terms are definitely problematic. We need to address this asap, starting with revisiting #85 .

**Comment by rctauber** [comment]
@loricorbani @tonysawfordebi -
Please see #116. I will be adding gaf-eco-derived.txt to the repo today.

**Comment by tberardini** [comment]
@lreiser: this is the ticket I was talking about

**Comment by loricorbani** [comment]
Rebecca, file is working even with last ^M still in the file.  Thanks.
