### ISSUE TITLE
Suspicious-looking xrefs in ECO:0000006 and ECO:0005803

### ISSUE THREAD

**Issue by tonysawfordebi** [evidenceontology/evidenceontology#112]
The definition of ECO:0000006 in eco.obo looks like:

[Term]
id: ECO:0000006
name: experimental evidence
def: "An evidence type that is based on the results of a laboratory assay." [ECO:MCC, GOC:ecd]
subset: go_groupings
xref: inferred from experiment
is_a: ECO:0000000 ! evidence

and ECO:0005803 is:

[Term]
id: ECO:0005803
name: motility assay evidence
xref: A type of direct assay evidence where the motility of a cell or cells is determined. {xref="ECO:SN"}
is_a: ECO:0000002 ! direct assay evidence

The xref attributes don't look right (and, moreover, they break my parser...)

Can you take a look, please?

**Comment by nsuvarnaiari** [comment]
@tonysawfordebi 
I am taking a look now.

**Comment by dosumis** [comment]
Looks to me like these errors come from incorrect choice of annotation properties while editing in Protege.  This doc might help:

https://docs.google.com/document/d/18epAEpii6tJVBW0hLxANjl2fUujgJ61Ksz7THrGL70Y/edit#heading=h.dintzn9iwuiv

**Comment by nsuvarnaiari** [comment]
@dosumis, @tonysawfordebi 
I am going to make the corrections and do an emergency release in few mins. Sorry, still learning to do edits in Protege.
Thanks for bringing the issues to our notice.

Suvvi

**Comment by tonysawfordebi** [comment]
Thanks @nsuvarnaiari

**Comment by nsuvarnaiari** [comment]
@tonysawfordebi 

I finished the emergency release. Please give it a try and let me know if you continue to have issues.

Closing the ticket now. Reopen if needed.

Thanks,
Suvvi
