### ISSUE TITLE
'X used in mannual assertion' cross product terms needed

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#113]
Please could you add the following terms using the standard XP pattern for manual assertions:

| New term | Based on |
|----|----|
| electron microscopy evidence used in manual assertion	| ECO_0005033 |
| super resolution microscopy evidence used in manual assertion	| ECO_0005578 |
| fractionation evidence used in manual assertion | ECO_0000100 |
| yeast 2-hybrid evidence used in manual assertion	 | ECO_0000068 |
| electrophysiology assay evidence used in manual assertion	| ECO_0000164 |

Thanks,
David

**Comment by rctauber** [comment]
Hi @dosumis ! Yeast 2-hybrid evidence used in manual assertion has recently been added to ECO (ECO:). I just added the other 4 terms (ECO:0006003 - ECO:0006007). Please let me know if you need anything else.

**Comment by dosumis** [comment]
Hi @rctauber - just getting back to this now.  I can see the new terms in https://github.com/evidenceontology/evidenceontology/blob/master/eco-edit.owl  but not yet in your public release.  Can you push a new release for us?

Many thanks,
David

PS: A reason you moved the master to OWL?  With Protege 5 you can carry on saving in OBO.  Much better for simple diffs to track/check your edits.

**Comment by rctauber** [comment]
Hi again @dosumis -
We typically do releases on the first Friday of the month, so I'll push a new one out on Friday morning. If that isn't soon enough please let me know, though!

As for OWL, ECO had already been moved to OWL when I joined the team so I think @mchibucos or @nsuvarnaiari would be able to answer this question better than I can.
