### ISSUE TITLE
new term: mRNA 

### ISSUE THREAD

**Issue by lreiser** [evidenceontology/evidenceontology#115]
An author describes method described as "mRNA interactome capture" as evidence for annotation to "RNA binding".

This method essentially uses  UV crosslinking (in vivo) followed by selection on an oligo(dT)column, followed by RNAse treatment, protein extraction,  SDS-PAGE and mass spec to identify the proteins.

 I am not entirely sure where this belongs. It  is probably more like a sibling of  ECO:0001826 (ultraviolet light DNA footprinting evidence) which is a type of nucleic acid binding evidence rather than an instance of ECO:0001170 (cross-linking evidence used in manual assertion) which is a type of protein binding evidence. 

New term : ultraviolet light crosslinking RNA binding evidence
Synonym: mRNA -protein interactome capture
Definition:A type of nucleic acid binding evidence where RNA is cross linked by ultraviolet light and RNA protein bound complexes are recovered by selection on oligo(dT) columns. After RNAse treatment the proteins are purified by SDS-PAGE and identity determined by mass spectrometry.
Parentage: (is a/type of)  ECO:0000136
Reference: PMID:27729395

**Comment by rctauber** [comment]
Hi @lreiser - I looked up the PubMed article you provided, but I don't have access to it. I found an article with what seems to be a very similar technique for isolating RNA binding proteins ([In vivo UV-cross-linking hybridization](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC309546/)). This method uses UV cross-linking, SDS-PAGE and western blotting for detection (no mass spec).

**Comment by rctauber** [comment]
'mRNA interactome capture evidence' (ECO:0006010) - A type of nucleic acid binding evidence in which ultraviolet light induces cross-linking of RNAs and proteins, then the bound complexes are recovered by selection on oligo(dT) columns, purified by SDS-PAGE, and subsequently analyzed and identified by western blotting and/or mass spectrometry.
is_a ECO:0000136 ! nucleic acid binding evidence

Also:
'mRNA interactome capture evidence used in manual assertion' (ECO:0006011) -A type of mRNA interactome capture evidence that is used in a manual assertion.

Let me know if this needs any changes. I included 'ultraviolet light crosslinking RNA binding evidence' as an exact synonym.

Thanks!

**Comment by lreiser** [comment]
Aaaand we're back. DDoS'd right in the middle of commenting....

I am attaching the manuscript that is the source of the method (similar to above).
I think that what you have created is fine. 

FWIW The authors suggested " A type of nucleic acid binding evidence where RNA and proteins are cross-linked by ultraviolet light and RNA-protein complexes are captured on oligo(dT) beads. After RNAse treatment, the RNA-bound proteins are identified by mass spectrometry. "

[Plant Cell-2016-Reichel-tpc.16.00562.pdf](https://github.com/evidenceontology/evidenceontology/files/545248/Plant.Cell-2016-Reichel-tpc.16.00562.pdf)

**Comment by rctauber** [comment]
@lreiser Thanks for that - I'll update that definition and commit it then.
