### ISSUE TITLE
NTR under electrophysiology evidence - whole-cell patch-clamp evidence

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#118]
whole-cell patch-clamp

SynGO suggests: High resolution single cell recordings of whole cell currents, membrane potentials or cell capacitance.
PMID:6143532 http://www.springer.com/us/book/9780306448706

Wikipedia entry looks useful for more experimental details: https://en.wikipedia.org/wiki/Patch_clamp#Whole-cell_recording_or_whole-cell_patch that might align more closely with defs for related terms you already have:

e.g.

rdfs:label "cell-attached single-channel recording evidence"
id "ECO:0005573"
definition "A type of electrophysiology assay evidence that involves isolation of a patch of membrane electrically from the external solution and to record current flowing into the patch and this is achieved by pressing a fire-polished glass pipette, which has been filled with a suitable electrolyte solution, against the surface of a cell and applying light suction."

It may also be worth adding a general class for patch clamp evidence covering whole cell, cell attached etc.  See https://en.wikipedia.org/wiki/Patch_clamp for mappings to current terms (chase up original refs from WP wherever poss!)

**Comment by rctauber** [comment]
Hi @dosumis - just want to check if I'm understanding correctly. The proposed parent class (patch clamp recording evidence) would cover this new term, 'cell-attached single-channel recording evidence', and the following:

-  cell-detached inside-out single-channel recording evidence (ECO:0005574)
-  cell-detached outside-out single-channel recording evidence (ECO:0005582)

As well as 'macropatch voltage clamp recording evidence' (ECO:0005584)?
Def: 'A type of electrophysiology assay evidence where recording is done on a fragment of the cell membrane (attached to or detached from the cell) using a large tip diameter pipette that allows isolating and studying a small number of channels into that fragment (patch).'

Am I missing anything? Thanks!

**Comment by vhinard** [comment]
Is the existing term "whole-cell voltage clamp recording evidence" (ECO:0005572) could not match your request of "whole-cell patch-clamp"? At least it is a child of.

ECO:0005572
Def: "A type of electrophysiology assay evidence that involves direct measurement of ionic current across a membrane while controlling the membrane potential by maintaining the voltage."

**Comment by dosumis** [comment]
Hi Valerie,

Thanks for chipping in. 

> Is the existing term "whole-cell voltage clamp recording evidence" (ECO:0005572) could not match your request of "whole-cell patch-clamp"? At least it is a child of.

The experts on the synapse project apparently rejected using the existing term.  As far as I can gather, the difference is that in a 'whole-cell voltage clamp', a sharp electrode is used to pierce the membrane, whereas in a 'whole-cell patch clamp' a blunter, 'patch clamp' electrode is used and the membrane under the patch is ruptured.   I think maybe strictly it's not a superclass, but they're clearly both methods to measure the same thing.  

Proposal:

patch clamp: "
   <- is_a: cell-attached single-channel recording evidence (ECO:0005573) # exact_synonym: cell-attached patch clamp evidence
   <- is_a: cell-detached inside-out single-channel recording evidence (ECO:0005574) # exact_synonym: cell-detached inside-out patch clamp evidence
   <- is_a: cell-detached outside-out single-channel recording evidence (ECO:0005582) # exact_synonym: cell-detached outside-out patch clamp evidence
   <- is_a: whole cell patch clamp

& perhaps: 

whole cell voltage clamp
    <- is_a whole cell patch clamp

**Comment by rctauber** [comment]
'patch-clamp recording evidence' (ECO:0006012)
is_a ECO:0000164 ! 'electrophysiology assay evidence'
definition: "A type of electrophysiology assay evidence in which a glass micropipette is sealed to the surface of a cell membrane (patch) to study ion channels."

'whole-cell patch-clamp recording evidence' (ECO:0006014)
is_a ECO:0006012 ! 'patch-clamp recording evidence'
definition: "A type of patch-clamp recording evidence in which a glass micropipette filled with a prepared solution is used to form a seal with the cell membrane followed by rupture of membrane to provide accurate and high resolution electrical property measurements of the whole cell."

'patch-clamp recording evidence used in manual assertion' (ECO:0006013)
'whole-cell patch-clamp recording evidence used in manual assertion' (ECO:0006015)

ECO:0005573, ECO:0005574, and ECO:0005582 are now children of 'patch-clamp recording evidence'. If everything looks good, I'll go ahead and commit it. Thanks!

**Comment by rctauber** [comment]
Going to go ahead and close this since the terms have been added in. Please let me know if there are any other issues.
