### ISSUE TITLE
NTR: biofilm formation assay evidence

### ISSUE THREAD

**Issue by KristenKC** [evidenceontology/evidenceontology#119]
Definition: An assay to determine the presence or absence of a biofilm using crystal violet or safranin to detect the biofilm.

PMID:10547784

**Comment by pgaudet** [comment]
Hi Karen, 

I leave it to Suvvi and Marcus to decide, but in our group we have tried *not to create ECO terms that are equivalent to GO terms. We had started to create 'apoptosis assay,', 'cell proliferation assay', etc, and we thought it was redundant with the GO and not very informative. So we try to use for example 'TUNNEL assay' and 'microscopy'. 

Pascale

**Comment by rctauber** [comment]
We have been working on some microbiology classes in micro-edit.owl (not part of eco.owl yet). One subset of these new terms is 'microbiological staining evidence', which has a differential staining evidence child (with Gram staining evidence, endospore staining evidence, etc.). I haven't put in any classes regarding biofilms, but I could add something like 'biofilm staining evidence'.

Unfortunately, I don't have access to the PMID you mentioned so I can't see the exact technique. Is there a particular name for it?

**Comment by KristenKC** [comment]
I've seen it most often referred to as a biofilm formation assay with one paper calling it a crystal violet assay which is why I decided to include the different stain types in the definition. Maybe we could list crystal violet assay as a synonym?

**Comment by rctauber** [comment]
@KristenKC are you referring to the whole assay (not just the staining), as in [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4568995/)? I think I got a bit caught up with the staining part in the definition.

From some quick research, it looks like this often involves formation in a 96-well microtiter plate. I think a good specific term could be 'microtiter plate biofilm assay evidence', or something along those lines (which involves the whole process). There are some other methods described in the paper linked, and if those are required, perhaps they could be put under a general parent class.

For the request itself, please see the [information here](https://github.com/evidenceontology/evidenceontology/wiki/New-term-request-how-to) on requesting a new term. In micro-edit.owl, there are some parent classes that don't yet exist in ECO and I think this could fall those. For the moment, it could fit as a child of 'in vitro culture assay evidence' if the term is needed now. What do you think?

Thanks, and sorry for any confusion!

**Comment by KristenKC** [comment]
Yes I think it could fit as a child of 'in vitro culture assay evidence'. I think that microtiter plate biofilm assay evidence might be too specific since people also use test tubes or cuvettes to assay biofilm growth and we wanted to try to make a general term to capture all of that. 

I've attached a PDF of the paper I referenced above 
[PMID10547784.pdf](https://github.com/evidenceontology/evidenceontology/files/620022/PMID10547784.pdf)

**Comment by rctauber** [comment]
@KristenKC Thanks for the PDF! What do you think of this term as a parent class? Like @pgaudet said, we'd like this to be as informative as possible, but there are a lot of different methods used, so we also want to make sure the correct terms are in there. We would put in the different specific assays under that, and then if there is one missing we can always add it in. Some children could be...

From https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4568995/
'microtiter plate biofilm assay evidence'
'air-liquid interface assay evidence'
'colony biofilm assay evidence'
'Kadouri drip-fed biofilm assay'

'crystal violet binding assay evidence' http://www.idosi.org/gv/gv6(1)11/2a.pdf
'microplate spectrofluorometric biofilm assay evidence' https://www.researchgate.net/publication/7311498_A_microplate_spectrofluorometric_assay_for_bacterial_biofilms

**Comment by rctauber** [comment]
Hi again @KristenKC - I wanted to follow up and see if these terms work for you:

'biofilm formation assay evidence'
is_a ECO:0000182 ! 'in vitro culture assay evidence'
**definition**: A type of in vitro culture assay evidence in which biofilm growth is monitored and detected from attachment to development.

'air-liquid interface assay evidence'
is_a ECO:0006020 ! 'biofilm formation assay evidence'
**definition**: A type of biofilm formation assay evidence in which biofilm formation is analyzed, without staining, over 4 to 48 hours by growth on a tilted multiwell plate.
**comment**: Tilting of the plate positions the air-liquid interface on a clear portion to improve visability.

'colony biofilm assay evidence'
is_a ECO:0006020 ! 'biofilm formation assay evidence'
**definition**: A type of biofilm formation assay evidence in which a colony is grown on a semipermeable membrane on an agar plate to continuously supply nutrients by relocating to fresh plates.
**comment**: The plates commonly contain different carbon sources or antibiotic treatments to observe properties of the cells.

'Kadouri drip-fed biofilm assay evidence'
is_a ECO:0006020 ! 'biofilm formation assay evidence'
**definition**: A type of biofilm formation assay evidence in which mature bacterial biofilms are grown in a multiwell plate that has a growth medium continually pumped through the wells while waste is continually pumped out.

'microtiter plate biofilm assay evidence'
is_a ECO:0006020 ! 'biofilm formation assay evidence'
**definition**: A type of biofilm formation assay evidence in which microtiter dishes or tubes are inoculated and incubated to promote biofilm formation, and then biofilms are detected by staining with crystal violet or safranin to observe phenotypes.

**Comment by KristenKC** [comment]
Hi @rctauber I think everything you sent me above looks great! Thanks for all of your input.

**Comment by rctauber** [comment]
Great - I'll go ahead and commit those terms (+ their 'used in manual assertion' children) and close this issue. Thanks!
