### ISSUE TITLE
NTRs: electrophysiology - extracellular recording

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#120]
New terms needed under [electrophysiology assay evidence](http://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000164):

(indentation => suggested classification hierarchy)

* electrophysiology assay evidence, extracellular recording
   * electrophysiology assay evidence, single-unit extracellular recording
   * electrophysiology assay evidence, field potential recording
      * electrophysiology assay evidence, local field potential recording

Refs: 
https://en.wikipedia.org/wiki/Electrophysiology#Extracellular_recording
http://journal.frontiersin.org/article/10.3389/fnins.2014.00423/full (PMID: 25610364)

**Comment by rctauber** [comment]
Are there other types of field potential recording, or is it always local field potential recording? As I was doing some research, I really only saw local field potential recording. In that case, would it make sense to have 'local field potential recording evidence' with broad_synonym 'field potential recording evidence'? I did also see it referred to as 'intracranial EEG'.

If I'm totally off base, please let me know!

**Comment by dosumis** [comment]
EEG & ECG could count as 'field potential recording' ( see https://en.wikipedia.org/wiki/Extracellular_field_potential) but is definitely much broader than 'local').  Perhaps add both terms and add a gloss on the def of 'field potential recording'  stating that this term covers both local recording from microelectrodes as well as recording from larger areas of electrically active tissue such as electroencephalograms.

**Comment by rctauber** [comment]
Here are the suggested term additions (will commit as soon as you review and OK):

extracellular recording evidence
Parent: electrophysiology assay evidence
Definition: A type of electrophysiology assay evidence resulting from the use of electrodes to measure in vivo electrical activity coming from adjacent neurons. (source: http://www.nature.com/subjects/extracellular-recording)

single-unit extracellular recording evidence
Parent: extracellular recording evidence
Definition:  A type of extracellular recording evidence in which an extracellular microelectrode is used to measure the electrical activity of a single neuron. (doi:10.1385/0-89603-185-3:1 / http://link.springer.com/protocol/10.1385%2F0-89603-185-3%3A1)

field potential recording evidence
Parent: extracellular recording evidence
Definition: A type of extracellular recording evidence in which electrical activity is measured in either tissue or at a cellular level with microelectrodes. *
Narrow Synonym: local field potential recording evidence

* I tried to make this definition very broad, but it may be too general. Please let me know if you have any suggestions for this.

I will include the 'used in manual assertion' children for these terms as well.
