### ISSUE TITLE
NTR: electrophysiology - optical assay evidence 

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#121]
parent class:

electrophysiology assay evidence: "A type of direct assay evidence where electrical properties of cells or tissues are studied."

Electrical properties of cells are now commonly measured using fluorescent detectors.  Most commonly [GCaMP](https://en.wikipedia.org/wiki/GCaMP) is used to measure intracellular calcium levels*, but more recently direct voltage detectors are being used (see http://www.nature.com/nature/journal/v529/n7587/full/529469a.html & https://www.ncbi.nlm.nih.gov/pubmed/26586188).

Please add:

electrophysiology - optical assay evidence: "A type of direct assay evidence where the electrical properties of cells or tissues are studied using fluorescent sensors."

*I guess it is somewhat debatable if IC Ca2+ = electrical property.  Measuring PD across the plasma membrane (voltage sensing) sensing definitely is though. If it is not, please could you add a term for  evidence from fluorescent detection of IC Ca2+ somewhere else?

**Comment by dosumis** [comment]
Note: term(s) should also be under "fluorescence evidence" ECO:0001115

**Comment by dosumis** [comment]
One other suggestion:

Potential parent class for fluorescent detection of activity

'optogenetic sensor evidence': A type of direct assay evidence where some activity state of a cell  or tissue is measured using an genetically encoded optical sensor.'
comment:  examples include  sensors for calcium (GCaMP), vesicular release (synaptopHluorin), Neurotransmitter (GluSnFRs), or membrane voltage (Arc Lightning, ASAP1).

**Comment by rctauber** [comment]
With the addition of 'optogenetic evidence' (#122), 'optical assay evidence' would be a child of that, yes? That one puts optogenetics under 'experimental phenotypic evidence', but you mention 'direct assay evidence' here.

Optical assays seem to be used outside of electrophysiology, so perhaps this could be 'optical electrophysiology evidence'? Thanks!

**Comment by dosumis** [comment]
HI Rebecca,

I've reviewed this again and think the following will work.

Cheers,
David

----------------

- direct assay evidence: "Experimental evidence that is based on direct measurement of some aspect of a biological feature."
   - fluorescence evidence: "Experimental evidence that is based on direct measurement of some aspect of a biological feature via use of a fluorescent reagent."
      - fluorescent sensor evidence: "Experimental evidence that is based on direct, quantitative  measurement of some cellular property using a fluorescent sensor. Examples include sensors for ion concentration and potential difference across a membrane."*
         - genetically encoded fluorescent sensor evidence: "Experimental evidence that is based on direct, quantitative  measurement of some cellular property using a genetically encoded fluorescent sensor." (exact_synonym: optogenetic sensor evidence)
	    - genetically encoded fluorescent electrophysiology assay evidence: "A type of direct assay evidence where the electrical properties of cells or tissues are studied using fluorescent sensors.  Examples include genetically encoded sensors that detect potential difference across plasma membrane." ( exact_synonym: "electrophysiology - optical assay evidence"_
            - genetically encoded fluorescent ion concentration sensor assay evidence: "Experimental evidence that is based on direct, quantitative  measurement of ion concentration using a genetically encoded fluorescent sensor.  Examples include the genetically encoded calcium indicator GCaMP.

(* Struggled with this one a bit - but I think it is worth distinguishing a typical use of fluorescence via secondary antibodies from specific sensors of cellular properties.)

- electrophysiology evidence
   - genetically encoded fluorescent electrophysiology assay evidence: 

- experimental phenotypic evidence
   - optogenetic evidence: "Evidence arising from experiment in which neuronal activity is manipulated using genetically encoded, optically activated neuronal actuators. exact_synoynym: optogenetic actuator evidence

Note "optogenetic sensor evidence" is not a commonly used term.  The term optogenetic is mostly used to refer to experiments with actuators.  It's unlikely it would be used to refer to genetically encoded fluorescent sensors outside of an experiment using optogenetic actuators.

**Comment by rctauber** [comment]
Hi @dosumis - sorry for the delayed response, we have been getting ready for the OBI workshop this past week. I will start working on these terms later today. Thanks!

**Comment by rctauber** [comment]
I just added in the above terms, plus their 'manual assertion' children as ECO:0006032 - ECO:0006041. Going to close this issue and #122
