### ISSUE TITLE
NTR: pharmacological assay evidence

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#123]
pharmacological assay evidence: "Evidence from an experiment that assays the response of a cell, tissue, organ or organism following exposure to a receptor agonist or antagonist."

Not sure of the parent class - perhaps directly under experimental evidence?

**Comment by rctauber** [comment]
This one seems like it would fit well under 'biological assay evidence' -
Definition: Direct assay evidence that is derived by using a living organism to measure the effect of a substance, factor, or condition.

If that sounds good, I'll go ahead and add it there.

**Comment by rctauber** [comment]
Hi @dosumis -
I wanted to follow up on these NTRs - #120, #121, #122, and this. We will be doing the monthly release tomorrow so I could add these in before the release if these comments look good. Thanks!

**Comment by dosumis** [comment]
> This one seems like it would fit well under 'biological assay evidence' -
> Definition: Direct assay evidence that is derived by using a living organism to measure the effect of a substance, factor, or condition.

I guess.  But I'm a little worried about how broad this makes GO IDA.   Despite the name, the requested term refers to a type of perturbation.  It leaves the nature of the assay completely open.  The perturbation is in many ways analogous to a mutation - there may be many steps between the direct effect of the perturbation and the effect being assayed.

CC @ggeorghiou

**Comment by ggeorghiou** [comment]
I agree that it should not by default be mapped to GO IDA. Pharmacology is the study of drug action on the body. You have to consider the experiment being performed to determine the GO evidence to use. 

For example, if you are using an inhibitory molecule, you are suppressing the normal function of the gene product. This is technically a mutant phenotype, so it would fall under GO IMP. If you are using an activating molecule, then technically you are examining the normal function of the gene product. This in a way similar to overexpression of a gene product, which we normally would assign the evidence code as GO IDA.

**Comment by dosumis** [comment]
Thanks George.

Hi Rebecca, 
Could you add this under experimental phenotype evidence?  We can discuss mapping to IMP under #117 
cheers,
David

**Comment by rctauber** [comment]
Hi @dosumis - sorry I did not respond sooner.

Adding in the following:
ECO:0006053 'pharmacological assay evidence'
subClassOf 'experimental phenotypic evidence'
definition: "A type of experimental phenotypic evidence that arises from assaying the response of a cell, tissue, organ or organism following exposure to a receptor agonist or antagonist."

ECO:0006054 'pharmacological assay evidence used in manual assertion'

**Comment by dosumis** [comment]
Looks good.  Thanks.
