### ISSUE TITLE
gaf-eco-mapping.txt refers to ECO term that isn't in eco.obo

### ISSUE THREAD

**Issue by tonysawfordebi** [evidenceontology/evidenceontology#125]
IMP is now mapped in gaf-eco-mapping.txt to ECO:0006030, but that term doesn't exist in eco.obo.

**Comment by tonysawfordebi** [comment]
This needs to be fixed ASAP, please, as it means that we are unable to import GO annotations from external sources that use the IMP evidence code, because it is being mapped to an ECO ID that we don't recognise.

**Comment by dosumis** [comment]
**This seems to stem from the fix to issue #11.  Given the consequences for GO annotation at the EBI, and possibly elsewhere, It's quite urgent that this change be reverted. ASAP .**

I think we should discuss whether the [solution we agreed first](https://github.com/evidenceontology/evidenceontology/issues/117#issuecomment-265448984) of moving terms under 'mutant phenotype evidence' would work.

> Right now, we are going to move some of the apparent 'mutant' terms under 'mutant phenotype evidence' (i.e. the various mutation evidences), but not all of the terms that GO considers IMP.

We should discuss these and see if we can come to an agreement.   Can you list them.

If we did agree to change the default IMP mapping, then this would require further discussion and a notice period.  Many existing annotations will have to be changed and, given the variety of data pipelines for GO annotation, there may be additional overhead that we are not yet aware of.

Many thanks,
David

**Comment by rctauber** [comment]
@tonysawfordebi @dosumis - I'm sorry about the unintended consequences, I just pushed a revert that maps IMP back to ECO:0000315 for further discussion. These changes were made based on discussion on Tuesday at the ECO meeting about whether what GO considers IMP would truly fit under 'mutant phenotype evidence'. 

We are working on a solution for easier GO code mapping (#124) but it would take some time to implement, so we wanted to give a solution to #117. A release would have added ECO:0006030 'experimental phenotypic evidence used in manual assertion' to eco.owl for production (hence why it wasn't found). I will re-open #117 for discussion on that issue. Please let me know if there's anything else that needs to be done for this fix.

**Comment by dosumis** [comment]
Hi Rebecca,
Many thanks for the quick fix!  
- David
PS: I'll assume discussion of fixed moved back to #117

**Comment by tonysawfordebi** [comment]
Thanks Rebecca - just FYI, we currently have around 220K GO annotations in our database with ECO:0000315 as their evidence code; if the default mapping between IMP and ECO is changed, then we would need to determine what should happen to those annotations - it *should* just be a case of updating the ECO code, but there may well be some subtleties, hence the need for a notice & discussion period.

**Comment by rctauber** [comment]
@tonysawfordebi @dosumis - since the mapping has been reverted is it safe to go ahead and close this issue to resume discussion on #117?
I apologize again for any trouble this may have caused - hopefully this sorts everything out!

**Comment by tonysawfordebi** [comment]
Yep, fine by me.
