### ISSUE TITLE
NTR: 

### ISSUE THREAD

**Issue by hdrabkin** [evidenceontology/evidenceontology#128]
cell transfection experiment evidence used in manual assertion, child of IDA

**Comment by pgaudet** [comment]
I don't think this should be a child of IDA - you transfect a protein, you still need an assay to test its activity.

**Comment by hdrabkin** [comment]
Using that logic I don't see how the current term  (cell transfection experiment evidence) can map to EXP.  The transfection is part of  the experiment; there is always some assay. ( at some point  I thought we would be able to pipe these: eg, transfection|enzyme assay or transfection|immunolocalization, but at the moment this doesn't work well).

**Comment by rctauber** [comment]
Hi @hdrabkin - I apologize for the delay on following up on this issue.

Here's what GO says about transfection:

> For transfection experiments or other experiments where a gene from one organism or tissue is put into a system that is not its normal environment, the annotator should use the author's intent and interpretation of the experiment as a guide as to whether IMP or IDA is appropriate. When the author is comparing differences between alleles, regardless of the simplicity or complexity of the assay, IMP is appropriate. When the author is using an expression system as a way to investigate the normal function of a gene product, IDA is appropriate.

In the current state, this class could not just be placed under IDA... in some cases, it could be IMP. Perhaps it would make sense to create two child classes of 'cell transfection experiment evidence' with logical axioms on what the experiment *is about*, and then they would infer to the proper codes.

**Comment by hdrabkin** [comment]
I think when a cell is used as an expression vessel, I would use an IDA. I personally would never u ECOse a transfection experiment an IMP unless there were two sets being compared: a wild type version of the transfected cDNA with a mutant version; That use of transfections would be to compare the two. 
If it were a transfection to demonstrate, for example, nuclear localization (ie, a gfp-version or such), I would use an IDA. (it would be nice to chain the more detailed codes, (transfection/heterologous  expression assay (I forget the exact term)/GFP-experiment), but we currently cannot afaik

**Comment by rctauber** [comment]
I agree that there needs to be some sort of 'cell transfection experiment evidence' term under IDA, but we also need to account for the allele comparison cases that belong under the IMP code. Perhaps that means moving the current class and creating a new 'comparison' class under IMP, but I'm not sure what an appropriate label would be.

If we were to move ECO:0005606 (cell transfection experiment evidence) under 'direct assay evidence', I also want to make sure this will not cause any problems for our users.

**Comment by rctauber** [comment]
Hi @hdrabkin - would you still like to continue with this? Otherwise, we will close this issue.

**Comment by mgiglio99** [comment]
Hi all,
Looks like the original request was for a manual assertion child - that exists now.
All are under 'experimental evidence'.
I'm going to close this. 
Regarding the IDA/EXP debate, there are a number of terms where this issue comes up and we intend to review this more broadly, hopefully soon.
Michelle
