### ISSUE TITLE
NTR: fluorescence recovery after photobleaching

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#132]
https://en.wikipedia.org/wiki/Fluorescence_recovery_after_photobleaching

\+ used in manual assertion derived term

subClassOf:  fluorescence evidence

**Comment by rctauber** [comment]
Hi @dosumis, let me know if this needs anything else -

'fluorescence recovery after photobleaching evidence'
Exact synonym: FRAP evidence

Definition: A type of fluorescence evidence in which quantitative information on the diffusion properties of a sample is produced from the measurement of diffusion of fluorescent probes over time into an area that has been photobleached by a high-intensity laser pulse.

Comment: FRAP is a fluorescence microscopy-based technique.

xRef: PMID:26314367

**Comment by dosumis** [comment]
Looks good to me.  Would be great if you could add ASAP.  Cheers, David

**Comment by rctauber** [comment]
@dosumis just pushed the commit, will close this now. Thanks!
