### ISSUE TITLE
Evidence types for Ontology of Microbial Phenotypes annotations

### ISSUE THREAD

**Issue by mchibucos** [evidenceontology/evidenceontology#134]
@nsuvarnaiari is gathering up evidence types for OMP project, some of which are here: http://microbialphenotypes.org/wiki/index.php/Categories_to_Search
Other evidences exist in a prototype ontology here: https://github.com/evidenceontology/evidenceontology/blob/master/micro-edit.owl

The goals are:
1. Vastly improve the micro-edit.owl structure, definitions, logic, etc.
2. Learn more about OMP's methods categorized on their wiki - is the link above the only place for such evidence-related terminology.
3. Add ECO classes for the OMP methods/evidence terminology, in particular here: http://microbialphenotypes.org/wiki/index.php/Category:Methods
4. Speak to OMP about updating their methods template to show the ECO class.

**Comment by nsuvarnaiari** [comment]
Debby created a google doc with new ECO term requests for OMP methods.
https://docs.google.com/document/d/1qvMkRe7TlsV5ZYgfm3BGH8GykY2xN8Y9EtLfxUuSfLA/edit?usp=sharing
#142 is part of the google doc term request.

**Comment by rctauber** [comment]
I'm importing all of the NTRs and term edits into a ROBOT template here: https://docs.google.com/spreadsheets/d/1zSn1APhRKkO37uTQgm4BL6UDA5qnE9fckV9dMQg6ArY/edit?usp=sharing

Once everything is reviewed and OK'd we can just make the axioms and merge them into ECO 😃 

cc @dsiegele

**Comment by rctauber** [comment]
These terms are all added to ECO. Please reopen if this needs more discussion.
