### ISSUE TITLE
New term for disease annotation

### ISSUE THREAD

**Issue by sbello** [evidenceontology/evidenceontology#137]
Hi Elvira,
Here is our suggestion for a new ECO term to be used for disease annotation. We are trying to encompass cases where the author uses multiple lines of experimental evidence plus background knowledge of the human disease state to assert that a mutation in organism X models the human disease condition.

Suggested term name: combinatorial experimental evidence and background scientific knowledge used in a manual assertion
Definition: A type of combinatorial analysis combining use of one or more lines of experimental evidence and background scientific knowledge that is used in a manual assertion
suggested abbreviation: CEB
suggested parents:
combinatorial evidence used in manual assertion (ECO:0000244)
experimental evidence used in manual assertion (ECO:0000269)

Thanks,
Sue

**Comment by elviram** [comment]
Hi Sue,

this term seems a bit... cumbersome. It will need further discussion. @mchibucos, your input would be valuable here.

Cheers,
Elvira

**Comment by sbello** [comment]
I don't disagree the name is a mouthful. More than happy to try to come up with something shorter that covers the same basic concept.
Sue

**Comment by sjm41** [comment]
Hi,

I agree we need the 'combinatorial experimental evidence bit' but I'm not convinced we need the 'and background scientific knowledge' bit.  (I'm not sure what this bit is meant to cover - does MGI make disease model annotations based (partly) on the background knowledge of the curator?)
As it stands, the proposal trys to bring together concepts under 3 major branches of the 'evidence' tree, which might be too much:
- combinatorial evidence
- experimental evidence
- inferential evidence

I'm wondering if this simpler version would be sufficient?:
Term name: combinatorial experimental evidence used in manual assertion
Definition: A type of experimental evidence arising from the integration of more than one line of evidence that is used in a manual assertion. 
suggested abbreviation: EXPC
suggested parents:
combinatorial evidence used in manual assertion (ECO:0000244)
experimental evidence used in manual assertion (ECO:0000269)

**Comment by sbello** [comment]
The issue is that the **author** is using a combination of experimental evidence about the model combined with background knowledge about the human disease state to assert that the mouse/rat/fly/... is a model of the human disease condition. The background knowledge about the human disease state is essential to the annotation.
Sue

**Comment by sbello** [comment]
Hi Marcus,
Any progress on this. AGR would like to get this ready so we can switch to a consistent code for our disease annotations.
Thanks,
Sue

**Comment by sbello** [comment]
Any chance you've had a chance to work on this. The AGR group would like to put this into use.
Thanks,
Sue

**Comment by rctauber** [comment]
Hi @sbello - thank you for following up on this tracker item.

I think the inclusion of a 'has part' relationship would make more sense. I propose to create a child that is a subclass of 'combinatorial evidence' and is equivalent to:
```
'inference from background scientific knowledge'
 and ('has part' some 'experimental evidence')
```

At the top level, this is an inference... not experimental evidence (and therefore it would not make sense to assert this as a child of that). The experimental evidence is part of the inference, though. In this case, the new class is inferred to be a child of 'inference from background scientific knowledge' and can therefore be mapped up to the IC GO code.

As for the label... `inference from background knowledge and experimental evidence` could capture the same idea in less words, since the author is asserting something based on their background knowledge plus experimental evidence... let me know your thoughts.

cc @mchibucos

**Comment by sjm41** [comment]
This looks good to me.  Thanks!

**Comment by sbello** [comment]
Looks good to me.
Thanks,
Sue

**Comment by sbello** [comment]
Any movement on getting this into the ontology?

**Comment by rctauber** [comment]
Hi @sbello - I'm so sorry there hasn't been any movement on this issue recently.
I'm going to meet with the team this week RE this issue, and I'll have an update for you ASAP!

**Comment by rctauber** [comment]
Following up on this...

We still believe this should be an asserted child of `combinatorial evidence`. After reviewing the issue, we want to also add add a new term `author inference`. In the use case you discussed, the inference is made by the **author**, not the curator, so we would like to differentiate this.

The term will include the logical definition equivalent to:
```
'experimental evidence' and 'author inference'
```
and will be inferred to be 'experimental evidence' and 'author inference', along with the asserted parent class of 'combinatorial evidence'.

Finally, we propose the label:
```
'combinatorial evidence from author knowledge and experimental evidence'.
```
I know it's a bit longer, but I think it better captures what this evidence type is about: a combination of the author's knowledge and the experimental evidence in equal parts.

I would like to add that we will be reviewing the `inferential evidence` branch in the future, but this term label will remain the same. Please let us know your thoughts, and I apologize this has taken so much time to be addressed.

**Comment by sbello** [comment]
That sounds good. The ZFIN group (and some other groups) would also like a code for:
combinatorial evidence from curator knowledge and experimental evidence

**Comment by rctauber** [comment]
@sbello - should both of these terms include the `used in manual assertion` children?

**Comment by sbello** [comment]
Yes please.

**Comment by rctauber** [comment]
Alright, all taken care of! These will be available with the March release.

**Comment by sjm41** [comment]
Hi Rebecca,

Can we somehow associate these 3-letter abbreviations to those two terms you made for us a year back? (like you do for the 3-letter GO evidence code abbreviations)
combinatorial experimental and author inference evidence used in manual assertion (ECO:0007013) = CEA
combinatorial experimental and curator inference evidence used in manual assertion (ECO:0007014) = CEC

Let me know if you need a new ticket for this, rather than me commenting on this closed ticket. ;-)

**Comment by nsuvarnaiari** [comment]
Hi @sjm41 

Before we suggest a way to incorporate the three letter codes in ECO, we would like to get some input from you. Are there abbreviations used as in-house identifiers for annotating evidence? Or, you want us to add them (like synonyms) to make searching easy for these terms in ECO? Just trying to understand how you use the codes.

Thanks,
Suvvi

**Comment by sjm41** [comment]
Hi @nsuvarnaiari 
Primarily the first option - used as a short-hand for annotating evidence, and for displaying the evidence code on our website.  But the second option would be good too.
Basically, we'd like them implemented within ECO in a similar way as the three-letter codes using in GO annotation (e.g. IMP = ECO_0000315).  FlyBase will be using the CEA/CEC codes in our disease model annotations soon, and the expectancy is that other MODs will do the same in future.
 
Steven

**Comment by mgiglio99** [comment]
Hi Steven,
We are leaning toward making the 3-letter codes dbxrefs.
If we do that, is there a place in your system where users could find info on these codes?
Thanks,
Michelle

**Comment by sbello** [comment]
Are planning to do this for all the 3 letter codes? If so then I think we can figure out how to handle this in our systems.

**Comment by sjm41** [comment]
Looks like the GO 3-letter codes are handled like this (only showing subset of lines): 
[Term]
id: ECO:0000315
name: mutant phenotype evidence used in manual assertion
def: "A type of mutant phenotype evidence that is used in a manual assertion." [ECO:MCC]
synonym: "IMP" RELATED [GOECO:IMP]
synonym: "inferred from mutant phenotype" RELATED [GOECO:IMP]
xref: GOECO:IMP "inferred from mutant phenotype"

Does that mean the GO 3-letter codes are already included as dbxrefs?

If so, handling the proposed 'CEA' and 'CEC' codes in the same way makes sense and would allow developers to extract them all in the same way, if required.

**Comment by mgiglio99** [comment]
Yes, currently the GO codes are dbxrefs. They are also synonyms, but we are hoping to move away from the synonym option in the future. For all new 3-letter codes we would like to just use the dbxref option. Although for this option, it is important that there is something in the db we refer to that we can point to for information on the code.

**Comment by sjm41** [comment]
_Although for this option, it is important that there is something in the db we refer to that we can point to for information on the code_
Hmm, so you'll need a database to refer to...something equivalent to the "GOECO" in the xref shown in my example?
We asked for these codes to support disease model annotations within the model organism databases, but there's not an equivalent of the 'GO consortium' database for this purpose.  Probably the Alliance of Genome Resources (https://www.alliancegenome.org) may be the best bet going forwards, though no database is actively using those 3-letter codes right now.
Any thoughts @sbello?

**Comment by sbello** [comment]
I agree that the Alliance is probably the best we have but then I don't know what to use as a short abbreviation. Alliance seems too long and I'm not sure that using AGR for something for public consumption would be acceptable. Maybe we could use MODECO? That would be inclusive of all MODs. While we're not using these currently, I think many of us will switch to these in the future. Using AGRECO or MODECO would also let us add other codes if/when we need them in the future. 
We should check with Stacia about the use of AGR as a dbxref.

**Comment by mgiglio99** [comment]
If no one is using those 3-letter codes now, then I suggest not making them at all. We only have the GO codes in there because they predate ECO. Can you simply use the ECO id?

**Comment by sbello** [comment]
The desire is to have short text to display on the user interface in columns where we are already displaying GO codes. We would prefer not to mix showing GO codes with ECO IDs in the same display. For consistency and user familiarity we would like to continue to display the GO codes and add new codes for these new terms. We will be loading the ECO IDs and using these as well.

**Comment by sjm41** [comment]
I don't think I spelt out the reason for reason for asking about these two new codes (CEA and CEC) in my original post:
i) to check they are available - i.e. not already in use within ECO for some other term
ii) to add them to the ontology to 'register them' and so that scripts can look up a given ECO id within the ECO file and retrieve the 3-letter code for display purposes (our devs specifically asked about this.)

**Comment by mgiglio99** [comment]
Thanks for this additional info. ECO cannot take on the task of generating and maintaining 3-letter abbreviation codes for ECO terms. That would be equivalent to maintaining a parallel set of unique IDs. Ideally, people should use the ECO IDs to refer to ECO terms. However, we understand your desire to display the info in your resource in a way that is familiar to your users. Other groups we have worked with also have in-house ways of displaying ECO terms. In those cases, those groups maintain a mapping file linking their in-house codes or abbreviations to ECO term IDs. This allows them to display the information in any way they choose. In cases where it is possible to point to their system with a dbxref, we can add those cross references to the ECO terms.
 
Where 3-letter codes were in use before ECO came into existence, as with GO, although originally stored as synonyms, moving forward we plan to store these only as dbxrefs.
 
If you're interested, we'd be glad to talk to you more about our work with the groups using ECO terms as part of customized in-house systems to help you get that set up.
