### ISSUE TITLE
evidence used in manual assertion

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#138]
Please could we have 'evidence used in manual assertion' variants for the following terms:

* immunofluorescence wide-field microscopy evidence  ECO:0005599
* wide-field fluorescence microscopy evidence ECO:0005598
* over expression analysis evidence ECO:0000120
* cell-free assay evidence ECO:0000183
* in vitro cell based assay evidence ECO:0005014 

Thanks!

**Comment by rctauber** [comment]
These terms have been added in, please let me know if you need anything else @dosumis
