### ISSUE TITLE
Microscopy terms specifying immunolocalization/immunolabelling

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#140]
* immuno-labelling electron microscopy evidence
   * SubClassOf: electron microscopy evidence
   * SubClassOf: immunolocalization evidence
* immunofluorescence super resolution microscopy evidence
  * SubClassOf 'super resolution microscopy evidence'
  * SubClassOf 'immunolocalization evidence'*
  * SubClassOf 'immunofluoresence evidence'*

+ used in manual assertion variants

### *Some notes on classification:

Maybe there should be some connection between these two:

* *'immunofluorescence evidence':* "A type of protein detection assay evidence where a fluorescently labeled antibody is used to detect the presence or localization of a biomolecule within a cell."
* *'immunolocalization evidence':* "A type of microscopy evidence where antibodies are used to detect the location of molecules or other structures within cells or tissues."

And 'immunolocalization evidence' should definitely classify:

* *"immunofluorescence confocal microscopy evidence":* "A type of confocal microscopy evidence where light passes through immunofluorescent-stained tissue sections or cells and then the emitted light passes through the dichroic mirror and is focused onto the pinhole for subsequent detection."
* AND
* *"immunofluorescence wide-field microscopy evidence":* "A type of wide-field fluorescence microscopy evidence where fluorescently tagged antibodies are imaged that are used to bind to their antigens."

**Comment by rctauber** [comment]
Hi @dosumis -
Thanks for reaching out! We are currently in process of adding logic to ECO through mappings with OBI terms. In this project, we are trying to enforce a single asserted parent. With the logic, then, additional parents are inferred.

For your two term requests, we propose that the parents be 'electron microscopy evidence' and 'super resolution microscopy evidence', respectively. Then, when we add the mappings in, the other parentage should be inferred. Do you have a preference for which class is the asserted parent?

We will look at the logical defs for the terms you listed below as well to see where connections may be inferred.

**Comment by dosumis** [comment]
I have no preference for which classification is asserted and which inferred.  My advice is to go with whatever works best for your formalization - In ontologies I build, there is no special status to asserted classification vs inferred - and your users won't see any difference anyway.


Any ETA on these? we need them quite soon.

Many thanks,
David

**Comment by rctauber** [comment]
Hi @dosumis -
I'm adding them in now with the following (plus the manual assertion children):

ECO:0006070 'immuno-labelling electron microscopy evidence'
A type of electron microscopy evidence resulting from the use of antibodies to identify the localization of antigens in cells and tissues.

ECO:0006072 'immunofluorescence super resolution microscopy evidence'
A type of super-resolution microscopy evidence resulting from the use of fluorescently-tagged antibodies to identify the localization of antigens in cells and tissue.

Let me know if anything looks off and I'll update it, but otherwise they will be available in eco.owl after our release on Friday. Thanks!

**Comment by dosumis** [comment]
Excellent.  Thanks!

How's the work on formalization patterns with OBI coming along?  Have you considered using [DOSDPs](https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-017-0126-0)?    <<<Shameless plug>>>

**Comment by rctauber** [comment]
Hi @dosumis ! Sorry it took so long to respond here - the formalization is going really well. We are currently using ROBOT templates to implement the design patterns in OWL, but I'll definitely take a look at DOSDPs. Thanks for sharing!
