### ISSUE TITLE
NTR for colony morphology evidence

### ISSUE THREAD

**Issue by dsiegele** [evidenceontology/evidenceontology#142]
• colony morphology evidence: A type of xx evidence based on the form and structure of a colony formed by a microorganism. 
     • colony size evidence: A type of colony morphology evidence where growth and/or viability of a microorganism is assessed based on colony size.
     • colony color evidence: A type of colony morphology evidence where colony color is used to assess the presence or absence of some physiological process in a microorganism. narrow synonym: colony pigmentation evidence

**Comment by mchibucos** [comment]
Hello Ontology of Microbial Phenotypes and @dsiegele !
Thank you for your request. @rctauber can you please add these - and check into OBI/GO/OMP to see if we can add some logic right off the bat? Thanks! Marcus

**Comment by rctauber** [comment]
@mchibucos @dsiegele Adding now - I'll put them on the spreadsheet and start looking!

**Comment by rctauber** [comment]
@dsiegele Do you have a recommended parent for 'colony morphology evidence'? Would 'in vitro culture assay evidence' be appropriate?

**Comment by mchibucos** [comment]
Hi @rctauber . In vitro culture would not be optimal in my opinion... I think we want to consider some sort of microbiological assay-based hierarchy... let's speak offline, as there is some project background you need to know...

**Comment by dsiegele** [comment]
Modified definition for colony size evidence

colony size evidence: A type of colony morphology evidence where colony size is used to assess growth, fitness, and/or viability of a microorganism.

**Comment by mchibucos** [comment]
Emailing from phone - will update reply later:

 This one is a good example for our logical definitions pattern work - specifically I am curious about the "is about" concept, in this case growth, etc.  Contrast this with that prior request by RGD where the is about was disease. Let's discuss this among ECO staff soon, as I want to use a consistent design pattern...

Marcus

**Comment by mgiglio99** [comment]
NTR was taken care of, other design issues will be handled in other tickets.
