### ISSUE TITLE
Query about RNA sequencing assay evidence

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#144]
Hello, 

I am looking at RNA sequencing assay evidence used in manual assertion (ECO:0005664) and
RNA sequencing assay evidence used in automatic assertion (ECO:0005665)
 and I wonder when to use each of these ? 
which part of the annotation would be manual? We are trying to annotate transcript levels by RNA seq in different tissues/cell lines, which is a rather standard application for RNAseq. 

In the experiment, authors purify/enrich the cell line or tissue, the RNAseq pipeline is run, and annotation to 'expressed in tissue x at level y' is produced. Is this manual or automated ? 

Thanks,

Pascale

**Comment by mgiglio99** [comment]
Hi @pgaudet 
Apologies for us dropping the ball on this.
We think this is similar to how we handle things like automated and manual Blast results. 
In this case if a human reviews the expression results and decides what level of RNAseq results are required to decide something is expressed or differentially expressed within the biological context of the experiment, than it would be manual. But if a pipeline is run and automated cutoffs are used and  there is no human review then it would be automated. Does that make sense?

**Comment by pgaudet** [comment]
Hi @mgiglio99 

We were trying to capture transcript levels, not sequence similarity (this was a type of IEP). 

But probably the term is not very clearly formulated !

**Comment by mgiglio99** [comment]
I know you were talking about transcript levels - I was just using the sequence similarity stuff as an analogy of how to use the automatic/manual terms for this. I think about this situation in much the same way.
If there is no human intervention in the assertions made from the RNAseq analysis pipeline then its automatic - that is if the pipeline spits out a list of expressed genes based on built in cutoffs. However if a human reviews the transcript count data and based on that decides what the cutoff will be for counting something as expressed then it would be manual.
Make sense?
For your example above, if you are just reporting levels of expression that come straight out of a pipeline then I think its automatic.

**Comment by mgiglio99** [comment]
Hi @pgaudet  - just checking if you think we've answered this sufficiently and can close this one.
Michelle

**Comment by mgiglio99** [comment]
Closing this for now, please reopen if you want to discuss more.
:)
