### ISSUE TITLE
Definition xrefs have disappeared from eco.obo

### ISSUE THREAD

**Issue by tonysawfordebi** [evidenceontology/evidenceontology#146]
All definition xrefs appear to have disappeared in the 2017-07-07 release of eco.obo.

For example, this is ECO:0000001 in the 2017-06-02 release:

[Term]
id: ECO:0000001
name: inference from background scientific knowledge
def: "A curator inference that links the current annotation to a different evidence-based annotation via background knowledge of the curator." [ECO:go, ECO:MCC]
is_a: ECO:0000205 ! curator inference

and this is it in the 2017-07-07 release:

[Term]
id: ECO:0000001
name: inference from background scientific knowledge
def: "A curator inference that links the current annotation to a different evidence-based annotation via background knowledge of the curator." []
is_a: ECO:0000205 ! curator inference
property_value: IAO:0000119 ECO:MCC xsd:string

Is this deliberate?

**Comment by rctauber** [comment]
Hi @tonysawfordebi -
With this release, we switched from providing definition sources as annotations on the definition with the database_cross_reference property (the xrefs) to using IAO's 'definition source' annotation property (what you're seeing as IAO:0000119). These were only changed for the definitions, and any xrefs to GO codes were left, e.g. as with 'physical interaction evidence'

```
[Term]
id: ECO:0000353
name: physical interaction evidence used in manual assertion
def: "A type of physical interaction evidence that is used in a manual assertion." []
synonym: "inferred from physical interaction" EXACT [GOECO:IPI]
synonym: "IPI" EXACT [GOECO:IPI]
xref: GOECO:IPI "inferred from physical interaction"
property_value: IAO:0000117 "mchibucos" xsd:string
property_value: IAO:0000119 ECO:MCC xsd:string
```

If this is an issue for your work, please let us know so we can get things sorted out.
cc @mchibucos

**Comment by tonysawfordebi** [comment]
OK - this means that GO & ECO do things differently now, so I can't use a shared parser (although I'm in the process of switching to consuming the OBOGraph version of GO rather than OWL/OBO, so that's not a major consideration).

I'll modify my code to take account of this change.

Incidentally, was this change announced anywhere before you implented it?

Incidentally (2), do you have any plans to make ECO available in OBOGraph (JSON) form at any point?

**Comment by tonysawfordebi** [comment]
@rctauber I've updated our parser so that it now handles the new way of dealing with definition xrefs, but I've noticed a problem with other xrefs, namely that if the id part of the xref itself contains a colon, then the colon is escaped. For example:

[Term]
id: ECO:0000052
...
xref: TAIR:TED\:0000063

[Term]
id: ECO:0000005
...
xref: PSI-MI:MI\:0415 "enzymatic study"

This is something that seems to have snuck in in this release.

**Comment by rctauber** [comment]
Thanks for bringing this up @tonysawfordebi - I don't see this in the eco-edit.owl file or the eco.owl file, but it is an issue in eco.obo. I'll replace these on the eco.obo file for now and look into it. I'll be doing an unscheduled release in just a bit so that you have a live file to work with.

**Comment by tonysawfordebi** [comment]
Thanks, @rctauber

**Comment by rctauber** [comment]
@tonysawfordebi We noticed that we'd like to change the PSI-MI:MI:xxxx refs to simply be MI:xxxx (e.g. MI:0415) to be consistent with other annotations. Would that cause any issues? It would be live with the next release in August.

**Comment by tonysawfordebi** [comment]
That's fine with me, @rctauber

**Comment by cmungall** [comment]
Can you switch back to doing the definitions as axiom annotations? This is standard

**Comment by mchibucos** [comment]
Yes. We can. would be grateful if you would suggest some documents/refs/etc. about this standard, as I am trying to learn more. @rctauber

**Comment by tonysawfordebi** [comment]
@mchibucos / @rctauber Can you give me a heads-up when you're about to make this change, please, as I'll need to change my parser again.

Thanks.

**Comment by mchibucos** [comment]
Will do - and again, sorry for the inconvenience.

**Comment by tonysawfordebi** [comment]
No worries.

**Comment by tonysawfordebi** [comment]
Thanks, @rctauber - I'll modify my parser accordingly.

**Comment by tonysawfordebi** [comment]
@rctauber @mchibucos I've updated my parser to reflect your changes, and I've noticed that the problem of colons in the id part of xrefs being escaped has crept back into eco.obo.

For example:

`[Term]
id: ECO:0000200
...
def: "A type of sequence similarity evidence where a sequence alignment is the basis for making an annotation, but only when the alignment has been manually reviewed; or if the information is in a published paper, the authors have manually reviewed the evidence. Such alignments may be pairwise alignments or multiple alignments." **[url:http\\://www.geneontology.org/GO.evidence.shtml]**
...

[Term]
id: ECO:0000226
...
xref: **PSI-MI:MI\\:0402** "chromatin immunoprecipitation assay"
`

**Comment by rctauber** [comment]
Hi again @tonysawfordebi -

So sorry about that! I'll take care of that, and we will be doing another release on Monday. Thank you again so much for your patience.
