### ISSUE TITLE
New ECO code for ChIP and computational information?

### ISSUE THREAD

**Issue by RLovering** [evidenceontology/evidenceontology#147]
Dear Marcus
 
I am concerned about whether the GOC is limiting the import of transcription data due to a very conservative approach to ChIP data. Consequently, I was wondering if it would be possible to create an ECO code to describe that an annotation is supported by ChIP experimental data and also by computational information which has identified that the protein has a DNA binding domain.
 
This would then enable annotations to be created which describe that a protein binds a specific sequence of DNA based on ChIP evidence as well as a predicted DNA binding domain.
 
To be honest many GO annotations are made based on ‘author intent” which often relies on orthology or a the predicted function of a specific protein domain. However, there is strong opposition from a few people to include ChIP data and therefore a dedicated evidence code might alleviate the opposition to including this data.
 
Hopefully you will be able to provide more insightful suggestions for this. Apologies if this ECO (or an ECO that would meet this requirement) already exists, in which case please point me to it.
 
Kind regards
 
Ruth

**Comment by ivanerill** [comment]
Hi Ruth,

There are a few ChIP codes available in ECO that were generated when bringing [CollecTF](www.collectf.org) up to speed with ECO. The parent term is ECO:0000226, and you then have specializations for ChIP-chip, ChIP-seq, ChIP-exo...

I did not quite get why you would want a combo evidence code joining a ChIP method and a DNA-binding protein domain prediction. You can use ECO:0000028 or ECO:0000201 for the latter. The two methodologies support DNA binding from orthogonal angles (in vivo, in silico), and I believe it would be better to submit two annotations instead?

I also don't get the opposition to ChIP. It does yield quite a bit of false positives, but so do many other techniques. My approach is to push the data in and let the user decide if they want to use it.

**Comment by rctauber** [comment]
Hi @RLovering - following up here. Is this resolved, or can we provide some more assistance?
Thank you!

**Comment by mgiglio99** [comment]
ChIP terms have been reviewed lately. We are thinking that these being used along with other ECO terms by making more than one annotation, each one to a different term, rather than a combinatorial term might suffice here. We are happy to discuss more if you'd like.
