### ISSUE TITLE
Subset URLs in ECO have changed

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#149]
In the 2017-07-19 release, the structure of the subset URLs changed

e.g.
http://purl.obolibrary.org/obo/eco#go_groupings
->
http://purl.obolibrary.org/obo/eco/go_groupings

I can see the motivation for changing: the old URLs were ugly. However, unfortunately we were depending on these subsets for our amigo load (see #93). As the urls changed without warning, the classes effectively slipped out of the subset for us, causing this problem: https://github.com/geneontology/amigo/issues/433

In future can you give us advance warning so we can change our configurations? Thanks.

It may be easiest for you to stack with what you have for now (I recommend having the PURLs resolve) but I defer to @kltm here.

**Comment by cmungall** [comment]
Note that the change also had consequences for obo-format users - you can see for yourself in the obo version of the file.

The URI to shortform mappings for subsets is a little opaque, see http://owlcollab.github.io/oboformat/doc/obo-syntax.html
section 5.9.2

Basically 'non-canonical' identifiers like 'goslim_foo' get given a hash IRI using the ontology base IRI. There were reasons for this to do with unambiguous roundtripping.

Although more people are abandoning obo, unfortunately many of the consumers of eco still use it. I advise doing a diff between obo version with each release. If anything looks odd or changes unexpectedly then hold off and consult us.

**Comment by mchibucos** [comment]
Thanks Chris. Very helpful. Will do.

**Comment by cmungall** [comment]
OK, I consulted with @kltm, this is actually a bit more problematic for us than I thought.

@mchibucos  - Can we request an ASAP new release of ECO with the URLs for subsets reverted back (I can make the PR if you like). This will give us some time to make necessary software changes. We can then switch to your preferred URLs in 1-2 months, and perhaps coordinate this with wider implemented best practices across OBO.

**Comment by rctauber** [comment]
Hi @cmungall - I apologize for any issues this caused; this was actually something that I missed in a merge that changed the namespace from eco# to eco/. I'll fix it and release now.

**Comment by mchibucos** [comment]
Affirmative on all. @rctauber

**Comment by cmungall** [comment]
Not released yet....

**Comment by mchibucos** [comment]
Sorry Chris. I was under the impression this was fixed. @rctauber any insights?

**Comment by rctauber** [comment]
Release is live, thanks for your patience

**Comment by rctauber** [comment]
@cmungall is everything OK with this now? Let me know if there's anything else that needs to be fixed. Thanks!

**Comment by cmungall** [comment]
Thanks!
