### ISSUE TITLE
New codes for mutants

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#151]
Hello, 

We'd like to request children of 'mutant phenotype evidence' (ECO_0000015 ): 

1. 'temperature-sensitive mutant phenotype evidence'. Definition: A mutation that allow normal function of the organism at low temperatures, but altered function at higher temperatures.
(Source: https://en.wikipedia.org/wiki/Temperature-sensitive_mutant)

2. ‘recessive mutant phenotype evidence’: Definition: A mutation which, is diploid organisms, must be present in both alleles for a phenotype to manifest itself. 
(Source: https://www.ncbi.nlm.nih.gov/books/NBK21578/)

Thanks, Pascale

**Comment by rctauber** [comment]
Hi @pgaudet - do you have non-Wikipedia source for the temperature-sensitive mutant term request? If not, I can do some digging. Thanks!

**Comment by pgaudet** [comment]
Hi @rctauber 

Would this work? PMC2957654
PMC2746138

Thanks, Pascale

**Comment by pgaudet** [comment]
thanks !

**Comment by pgaudet** [comment]
Hi @rctauber 
just wondering where this file is ? 
Under https://github.com/evidenceontology/evidenceontology, eco-edit has been updated 1 year ago. 

Can you give me the IDs for the new terms ? 

Thanks, Pascale

**Comment by rctauber** [comment]
Hi @pgaudet - the terms are in eco-edit.owl currently. We do our releases the first Friday of every month, so the next release is Oct 6. Once the release process is complete, the terms show up in both eco.owl and eco.obo.

If you need these terms ASAP, I'm happy to do an unscheduled release.

**Comment by rctauber** [comment]
Oh! Sorry, forgot to add the IDs in... the new IDs are as follows:
ECO:0006098 - 'temperature-sensitive mutant phenotype evidence'
ECO:0006099 - ... 'used in manual assertion'
ECO:0006100 - 'recessive mutant phenotype evidence'
ECO:0006101 - ... 'used in manual assertion'
