### ISSUE TITLE
ECO:0005026 and ECO:0005006 are missing from the Ontology

### ISSUE THREAD

**Issue by dougli1sqrd** [evidenceontology/evidenceontology#154]
I have found some old usages of ECO:0005026 "gel electrophoresis evidence" and ECO:0005006 "direct assay evidence", but I noticed that in the ontology, these were not subclasses of ECO:0000000 "evidence". When I checked in Ontobee, these IDs didn't exist. I could only find references to these here: [ECO:0005026](http://microbialphenotypes.org/wiki/index.php/Category:ECO:0005026_!_gel_electrophoresis_evidence_(ECO:0000337)) and [ECO:0005006](http://microbialphenotypes.org/wiki/index.php/Category:ECO:0005006_!_direct_assay_evidence(ECO:0000002)). 

These classes should still exist in the ontology in their original structural place and searchable in ontobee, but obsoleted, or with synonyms, or both. This ensures that old terms from the past are still usable in ontologies today even if changed now. 

Thanks!

**Comment by rctauber** [comment]
Hi @dougli1sqrd (and @cmungall) -

I checked the release published 2017-03-28 and 2017-03-03 (as the email from Chris indicated that these IDs were checked in on 3/28) and these IDs didn't exist in ECO then, either. That said, I went back to the 2015-07-03 release and the following terms existed:

ECO:0005026 - gel electrophoresis evidence (ECO:0000337)
ECO:0005006 - direct assay evidence(ECO:0000002) (as a deprecated term)

In the next release on 2015-11-24, these terms were gone. It looks like this was a restructuring project that somehow got incorporated into the main release, as ECO:0000337 (gel electrophoresis evidence) existed as a separate term at the same time as ECO:0005026. And, ECO:0000002 (direct assay evidence) existed as a separate term from ECO:0005006 (which was deprecated in the release).

Here is a list of terms that had duplicate entries with different IDs in this release on 2015-11-24:
- ECO:0005001 - enzyme assay evidence(ECO:0000005)
- ECO:0005023 - experimental evidence (ECO:000006)
- ECO:0005017 - experimental phenotypic evidence(ECO:0000014)
- ECO:0005024 - imaging assay evidence(ECO:0000324)
- ECO:0005018 - immunological assay evidence(ECO:0000040)
- ECO:0005013 - in vitro assay evidence (ECO:0000181)
- ECO:0005025 - physical interaction evidence(ECO:0000021)
- ECO:0005022 - protein assay evidence (ECO:0000039)

There are also a handful of terms with the flag "(new)" in their label that do not appear to exist in ECO currently, such as ECO:0005000 (posttranslational modification assay evidence (new)). It seems that most of them have been officially added, such as ECO:0005034 (apoptosis assay evidence (new) -> 'apoptotic assay evidence' in current release).

All of these were under what seems to be a placeholder class: 'isb-sib evidence' (ECO:0000091), which does not even exist as a deprecated class currently.

As these classes were separate from the actual classes (as indicated by the IDs in the label), I wonder if it would make sense to add these as alt. IDs or to add them back into ECO as deprecated classes? It seems to me that this release was not a finalized release, but this was back in 2015, so it's hard to tell what was going on. It was the first release on GitHub, so it may have had something to do with transferring over from the previous version control system. I apologize that this is such a long reply, and hopefully this all makes a bit of sense.

@nsuvarnaiari had added these terms, do you have any more info on this?

**Comment by rctauber** [comment]
Hi again @dougli1sqrd & @cmungall -
I spoke with Michelle, and we would like to go ahead and merge these missing terms into the existing terms, rather than re-adding and deprecating them. 

I will do so for all the terms listed above. Hopefully this will solve any problems with these annotations, but let me know if there is anything else we need to do.

**Comment by rctauber** [comment]
Following up - does this need any more work done, or is it safe to close?

**Comment by cmungall** [comment]
When you say merge into existing terms, you mean as alt_ids (in obo-format lingo)? I think this is fine.

Note that in the OWL representation these will still be deprecated classes. See https://github.com/owlcs/owlapi/issues/317

**Comment by rctauber** [comment]
Exactly @cmungall !

Thanks for the heads up, good to know. 
Feel free to reopen if this ends up needing something else.
