### ISSUE TITLE
Addition of terms for definition references (DO)

### ISSUE THREAD

**Issue by rctauber** [evidenceontology/evidenceontology#158]
DO has requested the addition of terms to annotate their definition sources, such as PMIDs, links to encyclopedia entries, ebook references, and so on. This is separate from the current use of ECO's author statements - [discussion here](https://github.com/evidenceontology/evidenceontology/issues/106#issuecomment-349989251)

As per the discussion in #106 (linked above), we are looking into the structure of the terms like 'author statement' to support these sorts of annotations, while maintaining the integrity of 'traceable author statement' (TAS) and 'non-traceable author statement' for GO annotations. As such, 'traceable author statement from published clinical study' (PCS for HPO) may be recategorized as a sibling of TAS.

Further discussion and updates will be posted in this thread.
CC @lschriml @mgiglio99 @mchibucos

**Comment by pnrobinson** [comment]
@rctauber Thanks very much for asking--this will not affect our use of the codes at all, the change also sounds reasonable from a semantic point of view!

**Comment by rctauber** [comment]
These terms have been added so we are closing this issue. We will reopen if it needs further discussion. See also https://github.com/information-artifact-ontology/ontology-metadata/issues/44
