### ISSUE TITLE
New term requests - children of "substance quantification evidence"

### ISSUE THREAD

**Issue by dosumis** [evidenceontology/evidenceontology#159]
I can't find terms for assays involving quantification of tagged molecules.  Can you add these, or advise on alternatives?

"radioisotope quantification assay evidence (new term)"
is_a "substance quantification evidence (ECO:0000335)"
is_a "radioisotope assay evidence (ECO:0001120)"

"fluorescence quantification assay evidence (new term)"
is_a "substance quantification evidence (ECO:0000335)"
is_a "fluorescence evidence (ECO:0001115)"

Thanks!

**Comment by rctauber** [comment]
Thank you for the request! I can’t think of any alternatives for these terms that would already be in ECO, so we can definitely add them.

Do you have any PMIDs or other references for definitions on these?

**Comment by rctauber** [comment]
Hi @dosumis - following up on these terms.

I tried to find a source for 'radioisotope quantification assay', but only found some articles published in 1975 on hydrocarbon oxidizing bacteria. Could you provide some context for this term? What exactly is being assayed here? We are trying to focus on what the evidence is *about* in all new terms.

Same for 'fluorescence quantification assay evidence'. What is the fluorescence being used to measure in your case?

Thank you!

**Comment by dosumis** [comment]
> I tried to find a source for 'radioisotope quantification assay', but only found some articles published in 1975 on hydrocarbon oxidizing bacteria. Could you provide some context for this term? What exactly is being assayed here? 

Most Biochemistry and cell biology in the 2nd half of the 20thC involved labelling chemical with some radio-isotope and using this to trace/quantify the chemical after some biochemical process or extraction from some biological sample.   Much of cell/organismal biology has moved on to using fluorescent tags for the same thing.  Think this is so common that not referenced.

The specific motivating case for the radio-isotope quantification used to measure transport across a membrane.  A specific term for this would be useful, but thought it worth asking for the general one first.

**Comment by rctauber** [comment]
Thank you for the insight!

I think it would be good to go with the more-specific term that you need. If there ends up being multiple terms like that, we can always create a general parent class to organize them.

**Comment by rctauber** [comment]
@dosumis I apologize that it's taken this long to follow up, but I wanted to reach out and see if you were still interested in these terms. Did you get a chance to determine the specific terms that would be useful? We're happy to add in both the more-specific and general terms.

**Comment by rctauber** [comment]
Hi again. We went ahead and added these two new terms for you - they will be available in the release this Friday:

* ECO:0007847 'fluorescence quantification assay evidence'
* ECO:0007844 'radioisotope quantification assay evidence'

They both have automatic and manual assertion children.
