### ISSUE TITLE
New term request: voltammetry evidence

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#160]
Suggested relation:
is_a substance quantification evidence

**Comment by rctauber** [comment]
Hi @Pimmelorus - thank you for your request!
Could you kindly provide:
1. PMID(s) or other source(s) for a textual definition
2. The name of the group/project this term is for

**Comment by Pimmelorus** [comment]
Sure!

1. Ref: __Hitchhiker's Guide to Voltammetry: Acute and Chronic Electrodes for in Vivo Fast-Scan Cyclic Voltammetry__ ([PMID:28127962](https://www.ncbi.nlm.nih.gov/pubmed/28127962))
2. This term is for the Synapse Gene Ontology group.

**Comment by rctauber** [comment]
Thanks so much. I want to make sure I'm getting this right - the term is in reference to voltammetry used to measure neurotransmission, as in Fast-Scan Cyclic Voltammetry (FSCV)?

Is it always FSCV, or are there different types? The more specific the term, the better we can categorize it. Correct me if I'm wrong, but this seems like it could fall under 'electrophysiology assay evidence'.

More specifically, could it be a child of 'extracellular recording evidence'?
Def: A type of electrophysiology assay evidence resulting from the use of electrodes to measure in vivo electrical activity coming from adjacent neurons.

**Comment by Pimmelorus** [comment]
Well, I would be fine with the more general term __voltammetry__. I think we should be cautious not to mix technique and area of application too much. I guess some applications of __voltammetry__ in general or __FSCV__ more specifically lies in the measurement of physiological parameters. However, when applied to measure chemical reactions outside of a biological system the parent term 'electrophysiology assay evidence' does not apply. The same rationale goes for the suggested parent term 'extracellular recording evidence'.

My recommendation is as stated above:

Suggested relation:
is_a substance quantification evidence

**Comment by rctauber** [comment]
Here's a suggested definition from @jbmunro for `voltammetry evidence`
> A type of substance quantification evidence where an electrical gradient potential is applied to analyze an analyte of interest, resulting in a measurement amount of electrical current across the potential range applied.

If this sounds good, I'll go ahead and add it in!

**Comment by Pimmelorus** [comment]
Perfect!

**Comment by rctauber** [comment]
Added `voltammetry evidence` as ECO:0007015 and `voltammetry evidence used in manual assertion` as ECO:0007016. I'll be pushing a release on Friday, and they'll be available in `eco.owl` then!
