### ISSUE TITLE
New term request: photoconversion evidence

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#161]
reference: [https://www.ncbi.nlm.nih.gov/pubmed/28574633](https://www.ncbi.nlm.nih.gov/pubmed/28574633)

Suggested relations:
is_a fluorescence evidence
is_a imaging assay evidence
is_a protein assay evidence

**Comment by rctauber** [comment]
Hi again @Pimmelorus - for this term, I also need:
1. PMID(s) or other source(s) for a definition
2. The name of the group/project this term is for

Thanks again!

**Comment by Pimmelorus** [comment]
Hello @rctauber 
This term is for the Synapse Gene Ontology group.

**Comment by rctauber** [comment]
As with the other term, I want to make sure I get the specific application correct. What is being labeled with the fluorescent proteins? Or is it just a broad term for any sort of labeling with this type of fluorescent protein?

Sorry for all the questions - I'm trying to get an idea of what this assay is *about*, so we can be sure to categorize it based on that, rather than just the methods applied.

**Comment by Pimmelorus** [comment]
General: The basic principle is that the spectral emission properties of fluorescent proteins (e.g., mEosFP, tdEosFP, Dendra, Dronpa, Kaede, KikGR, mOrange) can be shifted (send out a different color of light upon excitation) once they are irradiated by ultraviolet or blue light.  

Application: When these fluorescent proteins are attached to native protein in a cell, this technique can be used to track mobility of protein from a given start position in the cell (exposed to ultraviolet or blue light). [ref: [Scientific Reports volume 5, Article number: 11771](https://www.nature.com/articles/srep11771) ]

**Comment by rctauber** [comment]
We also have the term `fusion protein localization evidence` with the definition:
> A type of protein localization evidence resulting from the fusion of a protein of interest to a labeling protein which has enzymatic activity or fluorescence properties.

If we're looking at the application you suggested, it seems like this term could be a child of that. If it's not necessarily protein localization, though, I'll place it as a child of `protein assay evidence`.

**Comment by Pimmelorus** [comment]
Again, I personally do not like to mix technique with application. __photoconversion evidence__ may be used for other applications as well. What I request is a tern term that describes the general type of evidence. You are free to create a child that incorporates __fusion protein localization evidence__, but I will not be using it.

**Comment by ivanerill** [comment]
Seems like `photoconversion evidence` should be child of `fluorescence evidence` (under `direct assay`), and then `fusion protein photoconversion localization evidence` could be derived and placed under `fusion protein localization evidence` (as per ref: Scientific Reports volume 5, Article number: 11771)

**Comment by rctauber** [comment]
Great, thanks @Pimmelorus and @ivanerill 

I'll move forward with `photoconversion evidence` as a child of `fluorescence evidence`, with a suggested definition:
> A type of fluorescence evidence where a molecule tagged with a fluorescent protein is exposed to ultraviolet or blue light to shift the spectral emission properties for visualization.

**Comment by rctauber** [comment]
I'm going to add this term in so it gets pushed with the release today. If you have any issues with the definition, please let me know and we can change it! The ID will be ECO:0007017, and ECO:0007018 for the manual assertion child.

**Comment by rctauber** [comment]
Closing this issue - please let me know if you have any other questions!
