### ISSUE TITLE
Adding synonyms to children terms

### ISSUE THREAD

**Issue by lreiser** [evidenceontology/evidenceontology#163]
While working on a project that incorporates specifically those ECO terms that are mapped to GO evidence codes we encountered an issue where a term was not found because a synonym was assigned ONLY to a parent but NOT the 'manual assertion' child.

The specific example is about 
ECO:0000096 electrophoretic mobility shift assay evidence
apparently the synonym EMSA was added a while back
https://github.com/evidenceontology/evidenceontology/issues/34

But the child term
ECO:0001807 electrophoretic mobility shift assay evidence used in manual assertion
Does not have this synonym, but it should. 

Is there a reason to only have the synonym associated to the parent in this case? If not then I would suggest to add EMSA to the child term. Are there other cases in ECO like this?

**Comment by rctauber** [comment]
Hi @lreiser - we haven't typically added the synonyms from the parents to the "manual assertion" children (or "automatic assertion").

We'd be happy to add EMSA as a broad synonym to ECO:0001807. Would it be beneficial if we also added all synonyms from the parent terms as broad synonyms for the "manual assertion" terms?

**Comment by ivanerill** [comment]
When doing cross-products with assertion I don't see why the synonyms for (or any other aspect of) the evidence part would change, so it makes sense (and seems more consistent) to port them.

**Comment by lreiser** [comment]
It does seem so yes.  I don't know how many there are that would propagate but yes. I mean it is possible to get to the 'manual term' but you have to traverse the tree. Its extra steps but also the relation I think is logically consistent.

**Comment by rctauber** [comment]
There are quite a lot, but I can run a SPARQL query and populate a ROBOT template to put everything in pretty quick. I should be able to get this in tomorrow morning 😃

**Comment by rctauber** [comment]
Done! The synonyms will be available in the April release, but just let me know if you need them any sooner.

**Comment by lreiser** [comment]
@rctauber  is this now in ?
gaf-eco-mapping-derived.txt
is that file equivalent to 
gaf-eco-mapping.txt?

**Comment by rctauber** [comment]
Hi @lreiser - the synonyms will show up with our April release, which I'll be pushing next week.

`gaf-eco-mapping-derived.txt` is not the same as the original mapping file. The derived file contains all the mapped classes, as well as their *children*. See #109 for more details. Thanks!

**Comment by rctauber** [comment]
@lreiser - the synonyms are live now!

**Comment by lreiser** [comment]
Great thank you!
