### ISSUE TITLE
Wish list: standard icons for upper level ECO terms

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#164]
It might be worth having a decomposition of ECO classes into sets of icons.

For GO and many projects, there are a few properties that people care about: experimental or non-experimental, manual or automated. This could be represented by 2 icons. We might want to expand with an additional icon representing the method - e.g. a tree for IBA.

Other groups may have other requirements.

cc @jmcmurry

**Comment by jmcmurry** [comment]
How small do you need these to be? Simple like font-awesome style? Also, when you say 2 icons, do you mean two images, each with a cross out for their opposites?

**Comment by ivanerill** [comment]
Maybe "experimental or non-experimental" could be rephrased as in vitro, in
vivo and in silico?

**Comment by rctauber** [comment]
There was some discussion on this awhile back (issue #31). Going off that, would this be the same idea to have the icon associated with a class with [depiction](http://xmlns.com/foaf/spec/#term_depiction)?

It seems like a cool idea - what's the use case for the icons?

**Comment by mgiglio99** [comment]
We've decided not to proceed on this for now.
Closing and will reopen if needed.
