### ISSUE TITLE
NTR: ribosome profiling

### ISSUE THREAD

**Issue by ValWood** [evidenceontology/evidenceontology#165]
def
A type of expression evidence  using specialized messenger RNA (mRNA) sequencing to   produces a “global snapshot” of all the ribosomes active in a cell at a particular moment.

Thanks

Val

**Comment by rctauber** [comment]
Hi @ValWood - let me know if this looks good and I'll push it. Thanks!

**label**: ribosome profiling evidence
**parent**: expression pattern evidence
**synonyms**: ribosome footprinting evidence, ribo-seq evidence
**definition**: A type of expression pattern evidence in which translation is measured by the positions of ribosomes active in a cell, identified through deep sequencing of ribosome-protected mRNA fragments. (http://www.cell.com/cell/pdf/S0092-8674(16)30216-1.pdf)

**Comment by ValWood** [comment]
Looks good to me!

Thanks

Val

**Comment by rctauber** [comment]
Great, I've added it in as ECO:0007087 and a manual assertion child as ECO:0007088. These will be released next week. I'm going to close this issue, but please feel free to reopen if you need anything else.

Thanks!
