### ISSUE TITLE
Add links to GO documentation on ECO classes from within ontology

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#166]
Can we add rdfs:seeAlso links to URLs from ECO classes in the GO GAF subset to the individual pages here: http://wiki.geneontology.org/index.php/Guide_to_GO_Evidence_Codes

**Comment by rctauber** [comment]
Hey @cmungall -

Right now, we have rdfs:seeAlso links for the 'used in...' children that are analogous to the codes themselves (e.g. 'experimental evidence used in manual assertion' rdfs:seeAlso http://geneontology.org/page/exp-inferred-experiment).

Would you like these links to also be on the parent classes ('experimental evidence', etc.)? Also, if you'd rather have the wiki links I can change all those.

**Comment by rctauber** [comment]
Since these links exist on the mapped terms, I'm going to close this issue. Please just reopen it if you need anything else in regards to this.
