### ISSUE TITLE
Workshop invitation: 4-6 July 2018

### ISSUE THREAD

**Issue by TinaHeger** [evidenceontology/evidenceontology#167]
Dear evidence ontology team,

We are in the process of building a web portal for ecology and realize that an ontology would probably be a very important component. Moreover, evidenceontology.org has many features we were thinking to include in our site too, so we were very happy to discover your work. 

We would be highly interested to learn more about your project, and would therefore like to invite you to send a team member as participant to our workshop “Developing a web portal for biodiversity research based on the hierarchy-of-hypotheses approach: Conceptual ecology meets bioinformatics, data visualization and web design”. The workshop is funded by the VolkswagenStiftung and will take place July 4-6, 2018 at the conference center “Schloss Herrenhausen” in Hanover, Germany: http://www.schloss-herrenhausen.de/en/.

In a freshly published book as well as several journal papers (see below) and a previous workshop (see link to blog post below), we have started exploring the potentials of the so-called hierarchy-of-hypotheses approach. The approach has so far been used to structure results of empirical studies, assess the validity of hypotheses, and as conceptual framework to structure research programs.

In this workshop, we would like to take steps towards a web portal for biodiversity research based on the hierarchy-of-hypotheses approach (see also our recently launced website http://www.hi-knowledge.org/). We will have in-depth discussions of very concrete and problem-oriented questions such as e.g.: Which users of such a web portal (e.g. scientists within or outside the field, policy makers, managers, students) are looking for which type of information, and how should we customize the web portal for different user groups? How should the data in the web portal be updated? How should we visualize the data?

We believe that this workshop would profit very much from insight into the achievements of evidence ontology, and we would very much appreciate your participation. Please let us know whether anyone of your team will be available and can participate. We can send a preliminary program for further information as soon as you we receive an email address from you. The funding will cover all your travel expenses, and there is no workshop fee.

We are looking forward to hearing back from you, hopefully with a confirmation of your attendance,

Tina Heger and Jonathan Jeschke

 

 

References:

Heger, T. and Jeschke, J. M. 2014. The enemy release hypothesis as a hierarchy of hypotheses. Oikos. 123: 741-750. doi: 10.1111/j.1600-0706-2013.01263.x.

Heger, T., Pahl, A. T., Botta-Dukat, Z., Gherardi, F., Hoppe, C., Hoste, I., Jax, K., Lindström, L., Boets, P., Haider, S., Kollmann, J., Wittmann, M. and Jeschke, J. M. 2013. Conceptual frameworks and methods for advancing invasion ecology. Ambio. 42: 527-540. doi: 10.1007/s13280-012-0379-x.

Jeschke, J. M., Gómez Aparicio, L., Haider, S., Heger, T., Lortie, C. J., Pyšek, P. and Strayer, D. L. 2012. Support for major hypotheses in invasion biology is uneven and declining. NeoBiota. 14: 1-20. doi: 10.3897/neobiota.14.3435.

 

Book publication:

Jeschke, J. M. and Heger, T. (editors): Invasion ecology – Hypotheses and evidence. CABI, Wallingford, UK.

 

Previous workshop:

https://jecologyblog.wordpress.com/2017/07/26/hierarchy-of-hypotheses-as-an-organizing-tool-for-research-report-on-a-workshop/

 

-- 
Dr. Tina Heger

Biodiversity Research / Systematic Botany
University of Potsdam
Maulbeerallee 2a
D-14469 Potsdam, Germany

++49 (0)331 977 4823
www.invasion-ecology.de
www.bbib.org/bibs-projekt.html
--

**Comment by mgiglio99** [comment]
Hello @TinaHeger 

Please accept my sincere apologies. I'm incredibly embarrassed, in fact mortified, to say that our team somehow overlooked your invitation. We have no explanation for how this happened, and it was only today that we realized you had sent this. Your project and the workshop sounded very interesting and we would have indeed been happy to be a part of this effort. I realize that you may have moved on to another resource when we didn't reply, but if you are still interested in working with us, we'd be happy to discuss possibilities further.

My apologies again,
Michelle

---------------------------
Michelle Giglio, Ph.D.
Associate Professor, Department of Medicine and Institute for Genome Sciences (IGS)
Associate Director for Analysis, IGS Informatics Resource Center
Academic and Outreach Coordinator, IGS
Institute for Genome Sciences
University of Maryland School of Medicine
Baltimore, MD
