### ISSUE TITLE
eco.owl causing AmiGO to fail to load

### ISSUE THREAD

**Issue by elserj** [evidenceontology/evidenceontology#168]
We use the eco.owl file as a part of our AmiGO for planteome.org.  We have had it as part of the load for quite some time, but since 5/18 it causes our daily test load to fail.  Errors are:
2018-05-22 02:03:46,923 ERROR (GafCommandRunner:962) Can't process an ontology with unsatisfiable classes for solr
2018-05-22 02:03:48,163 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0103115 'protoheme IX ABC transporter activity'
2018-05-22 02:03:48,164 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0103117 'UDP-3-O-acyl-N-acetylglucosamine deacetylase activity'
2018-05-22 02:03:48,165 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0103116 'alpha-D-galactofuranose transporter activity'
2018-05-22 02:03:48,165 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0103111 'D-glucosamine PTS permease activity'
....... (many more lines)

If I remove eco.owl from the list of files to load, the load successfully completes.  I tried contacting @cmungall to see if it may just be a local issue with AmiGO, but he is apparently at a meeting and may not respond for a bit, so I thought I'd see if you guys have any ideas.

Justin

**Comment by rctauber** [comment]
Hi Justin!

The issue might be coming from a discrepancy between where OBI places molecular_function and where GO has it. We had some issues with this before. With the OBI import, molecular_function gets moved. I can place it back as a top-level class and it should solve the unsatisfiable errors...

I will see if I can get some insight from OBI too, as we need GO and OBI to reconcile in ECO.

Do you need an unscheduled release for this fix?

**Comment by rctauber** [comment]
Good news! OBI corrected this today - see https://github.com/obi-ontology/obi/issues/921

I will update the import and publish a new release so that this is resolved. Sorry for any inconvenience this caused.

**Comment by rctauber** [comment]
@elserj @cooperl09 - are you able to test with eco-edit, or do you need the released version? I want to make sure this is what's causing the problem before publishing a new release. I can also send you a pre-release.

**Comment by elserj** [comment]
I can test with another version, just need the URL for it.  Thanks.

**Comment by rctauber** [comment]
@elserj let me know if this works: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.owl

**Comment by elserj** [comment]
Thanks, didn't even have to change the address as this is where the purl redirects.  Works fine now.

**Comment by elserj** [comment]
Sorry to reopen this, but I believe this fix introduced a new issue, probably just a typo.  We didn't notice till today.

On line 63122 in eco.owl (at least with the commit that was for this issue, not sure if it was moved with the new release), https://github.com/evidenceontology/evidenceontology/commit/f99dabdf920f27932f7b224d9a07b45548d3a5d9#diff-87cfba14225baf721ff1a8cf1db439fdR63122, The label was added with "GO:molecular_function", we believe it should just be "molecular_function".  It ends up displaying with the wrong label on our site.

**Comment by rctauber** [comment]
No worries!

This is imported from OBI and they appended the “GO” to it. I can rename it
in the import file so that it just shows up as “molecular_function” though.

**Comment by elserj** [comment]
That seems to work for us, thanks!
