### ISSUE TITLE
Create an eco-basic and eco-base release file

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#169]
It would be useful if ECO would be one of the ontologies to test the new "-base.owl" product, this would be all asserted axioms in ECO (i.e may have references to OBI but no actual OBI axioms)

Would help with issues like #168 where ECO unwittingly is the conduit for axioms from OBI that end up polluting GO as we discovered here: https://github.com/geneontology/minerva/issues/195

(GO and other ontologies are also guilty of this kind of injection, we'll import base.owl too...)

cc @balhoff

Ah "basic" file would also work for GO's purposes (i.e. no external ontology classes at all) but the base file would be most useful for compositional purposes.

**Comment by rctauber** [comment]
Hi @cmungall ! Should the base product only include the simple is_a hierarchy, like the "simple" versions created by OORT? I'll get this done this week.

**Comment by balhoff** [comment]
Hi @rctauber, the 'base' file would be like the form described here: https://docs.google.com/document/d/1eCo5C3aZ9kjhBu98-24c2FHZIHEeFV7I2TJ4Vd6qw6k/edit#heading=h.u7or56kflnm2

So it's all the axioms (not just hierarchy) created by the ECO project, but no inferences materialized, no axioms provided by imported ontologies, and no imports declarations. I added one for CL here: https://github.com/obophenotype/cell-ontology/pull/509/files

**Comment by rctauber** [comment]
Thanks @balhoff - so for the "base" file, I'll remove the import declarations and annotate it. No reasoning, no other processing steps.

For the "basic" file, I'll remove any equivalent statements and anonymous subclass statements. Would it make sense to remove the 'assertion method's from the "basic" file as well? Thoughts @cmungall @mchibucos ?

**Comment by balhoff** [comment]
Thanks!

**Comment by rctauber** [comment]
We have eco-base and eco-basic. Please reopen if this requires more discussion.
