### ISSUE TITLE
Question about gaf-eco-mapping-derived.txt

### ISSUE THREAD

**Issue by tonysawfordebi** [evidenceontology/evidenceontology#170]
While investigating some errors thrown by our GO annotation checker I discovered that ECO:0001242 (phage display evidence used in manual assertion) is mapped (in https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt) to the legacy GO evidence code IPI. However, when I looked at the ancestry of the term (https://www.ebi.ac.uk/QuickGO/chart?ids=ECO:0001242,ECO:0000314,ECO:0000353) I see that it could equally well be mapped to IDA. Indeed, there is an argument (in my mind, at least!) that says it **should** be mapped to IDA rather than IPI, because ECO:0000314 is closer to ECO:0001242 than ECO:0000353 is.
![eco_0001242](https://user-images.githubusercontent.com/10084958/42884399-2528eff8-8a96-11e8-975d-e4cecd66d2fc.png)

So, my question is this: how are the mappings in gaf-eco-mapping-derived.txt determined?

**Comment by ivanerill** [comment]
I agree, phage display is typically used in a manner that is more akin to IPI than to IDA.

**Comment by rctauber** [comment]
The mappings come from a query that iterates through all the classes mapped
to codes and finds all the descendants. For each step, all other codes are
filtered out until there are none left so things aren’t duplicated in the
case of dual parentage. IPI just happens to be after IDA, so if a class
maps up to both IPI and IDA, IPI will always be the mapping.

I don’t know how many classes fit this case, but we could change either the
query (to put IPI before IDA, so that IDA is the final mapping in the case
of both) this specific class to map it only to IDA. What are your thoughts?

**Comment by ivanerill** [comment]
Well, I now realize I read Tony's comment backwards. So I beg to disagree ;-) In my mind phage display is more IPI than IDA. And IPI is by definition a type of IDA, so it would make sense to default to IPI whenever there is double-inheritance.

**Comment by rctauber** [comment]
Great! That was my thought process when laying out the query - the
more-specific one should be the final mapping.

**Comment by tonysawfordebi** [comment]
@ivanerill IPI (ECO:0000353) is **not** a subclass of IDA (ECO:0000314); they are, however, both subclasses of EXP (ECO:0000269).

@rctauber Are you saying that you now think that ECO:0001242 should be mapped to IDA?

**Comment by ivanerill** [comment]
>IPI (ECO:0000353) is not a subclass of IDA (ECO:0000314)

@tonysawfordebi You are right, it is not in ECO. But my undestanding is that the IPI code was defined with that idea in mind on GO:
["IPI can be thought of as a type of IDA, where the actual binding partner or target can be specified"](http://wiki.geneontology.org/index.php/Inferred_from_Physical_Interaction_(IPI))

**Comment by ggeorghiou** [comment]
Hi all, just to weigh in here on this, phage display can also be used to examine not only interactions between gene products (typically protein-protein), but also for gene-product and chemical (i.e. small molecule compounds). Would it worth having an evidence code that distinguishes between interactions between gene products shown via phage display vs. interactions between gene-products and other molecules? The former can map to IPI, and the latter to IDA.

**Comment by pgaudet** [comment]
Hi,

- I thought IPI was a subtype of IDA; isn't it?
- George : IPI used to mean inferred from physical interaction, so small
molecules would also be OK for this code.

Thanks, Pascale

Le jeu. 19 juil. 2018 à 2:24 PM, Tony Sawford <notifications@github.com> a
écrit :

**Comment by tonysawfordebi** [comment]
@pgaudet No, in ECO terms, IPI is **not** a subtype of IDA, and that's where the problem that I'm having stems from.

**Comment by tonysawfordebi** [comment]
That would work for my purposes, but I don't know what the philosophically correct solution is.

**Comment by ivanerill** [comment]
@tonysawfordebi I am afraid you are not alone there :-) 

>Hi all, just to weigh in here on this, phage display can also be used to examine not only interactions between gene products (typically protein-protein), but also for gene-product and chemical (i.e. small molecule compounds). Would it worth having an evidence code that distinguishes between interactions between gene products shown via phage display vs. interactions between gene-products and other molecules? The former can map to IPI, and the latter to IDA.

@ggeorghiou the problem with this approach is that IPI can be used with _anything_ that is identifiable (e.g. an Enzyme Commission number, CHEBI ID...). A more robust move, which @rctauber alludes to, would be to create a phage display evidence term for "targeted" phage display (where interacting partners can be identified), and another one for "un-targeted" (where interacting partners cannot, or are not, identified). The latter could encompass other uses of phage display, such as protein engineering with PACE.

**Comment by rctauber** [comment]
We have been thinking about moving IPI (physical interaction evidence) under IDA (direct assay evidence) in ECO. I think this move would solidify the fact that "phage display evidence" belongs under IPI.

**Comment by pgaudet** [comment]
Sounds sensible.

Pascale

**Comment by beckyjackson** [comment]
This change was made on 2/27 and 'physical interaction evidence' is now a child of 'direct assay evidence'. We are closing this issue, but please reopen if it needs more discussion.
