### ISSUE TITLE
Why do you include non ECO codes in eco.obo ?

### ISSUE THREAD

**Issue by pamichel** [evidenceontology/evidenceontology#171]
Hi, we use the ECO ontology for annotations integrated in our platform [www.nextprot.org](http://www.nextprot.org). I noticed that many terms in the eco.obo are not ECO codes, among which:
- 620 GO terms
- 482 OBI terms
- ...

It seems that no GO term is involved in the definition fo any ECO terms, so why are there in the file ?
Thanks for your response

**Comment by rctauber** [comment]
Hi @pamichel - these are part of the ECO-OBI mapping project to increase logic within ECO. We can create an "eco-basic" OBO file if you'd like, see #169. We will be creating an "eco-basic" OWL file, so it won't be difficult to just convert it to OBO.

**Comment by rctauber** [comment]
Hi again - we have removed the imports from the `eco.obo` file so these terms will no longer appear as of the most recent release. Please reopen if you have any other questions!
