### ISSUE TITLE
Review of 'experimental phenotypic evidence' branch

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#174]
Currently reviewing 'phenotypic evidence' branch and creating this ticket to document discussions and notes.

[phenotypic similarity evidence.docx](https://github.com/evidenceontology/evidenceontology/files/2315519/phenotypic.similarity.evidence.docx)
[phenotypic similarity evidence2.docx](https://github.com/evidenceontology/evidenceontology/files/2315520/phenotypic.similarity.evidence2.docx)

James

**Comment by jbmunro** [comment]
Part 1 of the review of this branch involved discussion with Debby Siegel regarding proposed changes that are related to OMP.  The following changes are proposed.

**1.	'colony morphology evidence'** 
•	Change the name of this term to 'colony morphology phenotypic evidence'
•	Modify the definition:
A type of experimental phenotypic evidence resulting from studying the physical characteristics of an assemblage of microorganisms growing on a solid surface such as the surface of an agar culture medium.

**2.	'colony color evidence'** 
•	Change the name of this term to 'colony color phenotypic evidence'
•	Modify the definition:
A type of colony morphology evidence resulting from studying the colony pigmentation.

**3.	'colony size evidence'**
•	Change the name of this term to 'colony size phenotypic evidence'
•	Modify the definition:
A type of colony morphology evidence resulting from studying the size of the colony.

**3.1	'colony diameter phenotype evidence'**
•	New term, child of 'colony size evidence'
•	Proposed def: A type of colony size phenotypic evidence resulting from measurement of a microbial colony's diameter.

**4.	'phenomic profiling assay evidence'**
•	Modified definition:
A type of experimental phenotypic evidence that results from the study of the change in one or more phenotypes (the physical and biochemical traits of organisms in particular environments) in response to genetic and/or environmental factors.
•	Add the following annotations:
*	A phenome is defined as the SET of physical and biochemical traits, or, as the SET of all phenotypes expressed, i.e. a phenome is defined as the sum total of all phenotypic traits. 
*	Modified - Debby notes: I think this term is meant to be used for high throughput experiments where a large number of mutants is screened for their ability to grow in a large number of conditions. The individual mutants can then clustered based on the similarity of their phenotypic profiles--whether they grew or didn't grow across all the conditions. The goal being to try to identify genes whose products function in the same biological pathways based on their having similar phenotypes across multiple conditions.
*	xref: PMID:2118507

**Comment by jbmunro** [comment]
Hi @dsiegele and @jimhu-tamu,

With regard to the above suggestions, 
**1** - We will move forward with the proposed changes

**2** - We will move forward with the proposed changes

**3** - Rather than creating a child 'colony diameter phenotype evidence' as suggested in 3.1, we propose modifying the definition of 'colony size evidence' to include both area and diameter as follows: 

"A type of colony morphology evidence resulting from measuring the area or diameter of the colony."

Additionally, I will add the terms 'colony diameter phenotype evidence' and 'colony area phenotype evidence' as narrow synonyms.

**4** - We suggest further modification to the definition: 

"A type of experimental phenotypic evidence that results from the study of the change in more than one phenotype (the physical and biochemical traits of organisms in particular environments) in response to genetic and/or environmental factors."

If these meet with your approval, I will move forward making changes to ECO.

James

**Comment by jbmunro** [comment]
Additional review of this branch included discussion of terms with @pgaudet. Proposed changes and comments follow.

**5. 'behavioral assay evidence' ECO:0001012**
* current def: A type of experimental phenotypic evidence resulting from behavioral phenotyping and analysis to assess cognitive functioning.
* We would like to change the label to 'cognitive assay phenotypic evidence' to better reflect the definition.
* **Response: OK**

**6. 'constitutively active mutant evidence' ECO:0001032**
* current def: A type of experimental phenotypic evidence resulting from a constitutively active mutant (CAM), resulting in mutant proteins that remain active in the absence of upstream signals.
* Should we consider modifying the current definition?   A constitutive mutation = a mutation usually in the operator gene or regulator gene resulting in unregulated expression of structural genes.
* **Response: This is not what we meant - this was done with kinases in mind, but probably other regulated proteins can have this behavior: some mutations make them catalytically active without any stimulation.**
* I believe that the mutation is within the DNA, so would this term be better placed as a child of 'mutant phenotype evidence'?
* **Response: As I mentioned above, we meant something different. You might want to create that other term, although personally I would use 'overexpression evidence' for this (not sure what the exact ECO term is).**
* We would like to change the label to 'constitutively active mutant phenotypic evidence'.
* **Response: If this covers mutated gene products (proteins), sure.**

**7. 'deletion mutation evidence' ECO:0001038**
* We would like to move this to 'mutant phenotype evidence'.
* We would like to change the label to 'deletion mutation phenotypic evidence'
* **Response: Yes.**

**8. 'dominant-negative mutant evidence' ECO:0001042**
* We would like to move this to 'mutant phenotype evidence'.
* We would like to remove "the analysis of" from the definition to keep it more in line with the other definitions:
** new def: A type of mutant phenotype evidence resulting from ~~the analysis of~~ a mutated gene producing mutant polypeptides that disrupt the activity of the wild-type genes.
* We would like to change the label to 'dominant-negative mutant phenotypic evidence'
* **Response: All good for me.**

**9. 'transgenic organism evidence' ECO:0001131**
* We would like to modify the current definition:
** current def: A type of genetic transformation evidence resulting from an organism that has had its expressed phenotype altered by modification.
** new def: A type of genetic transformation evidence resulting from the artificial introduction of genetic material (DNA) from an unrelated organism.
* **Response: We had the following definition: "Inference based on an organism containing a gene sequence that has been isolated from one organism and introduced into a different organism. in general, the DNA is incorporated into the organism's germ line. The insertion is not necessarily targeted to a specific locus. " I think 'different' is better than 'unrelated' - one might ask, what is related.**
* We would like to change the label to 'transgenic organism phenotypic evidence'
* **Response: OK**
* What are your thoughts on making 'transgenic organism phenotypic evidence' a child of 'transgenic rescue experiment evidence'?  This would require modifying the label from 'transgenic rescue experiment evidence' to 'transgenic rescue experiment phenotypic evidence', require modification of the definition and require making 'transgenic rescue experiment phenotypic evidence' a child of 'experimental phenotypic evidence'.
**Response: No, the transgenic organism is not necessarily a rescue experiment.** 
* current def: A type of functional complementation evidence resulting from the introduction of a transgene to prevent, or "rescue" an organism from a condition.
* new def: A type of experimental phenotypic evidence resulting from the introduction of a transgene (genetic material from an unrelated organism) to prevent, or "rescue" an organism from a condition.

**10. 'natural variation mutant evidence' ECO:0001103**
* What is the difference between 'natural variation mutant evidence' and 'mutant phenotype evidence' ECO:0000015?  I am trying to determine if they are not essentially equivalent and if not, should 'natural variation mutant evidence' be a child of 'mutant phenotype evidence'?
* 'natural variation mutant evidence' def: A type of experimental phenotypic evidence resulting from the observation of the impact of a natural mutation on the expressed traits.
* 'mutant phenotype evidence' def: A type of experimental phenotypic evidence derived from the difference in two alleles of a corresponding gene that result from one or more changes in the genome.
* **Response: Mutant phenotype is more general. Natural variants occur in populations; while mutants may be natural or artificial.**
* Assuming that 'natural variation mutant evidence' is distinct from 'mutant phenotype evidence', we would like to modify the current definition by removing "the observation of":
** new def: A type of experimental phenotypic evidence resulting from the observation of the impact of a natural mutation on the expressed traits.
* **Response: OK**
* We would like to change the label to 'natural variant phenotypic evidence'.
* **Response: OK**

**11. 'point mutation evidence' ECO:0001113**
* We would like to move this to 'mutant phenotype evidence'.
* We would like to change the label to 'point mutation phenotypic evidence'.
* **Response: Yes**

**12. 'syngeneic transplantation experiment evidence' ECO:0001128**
* Our concern is that the definition describes a process as opposed to a type of evidence and we are trying to focus on the latter, correcting terms where possible.  If you have any suggestions in this regard, I would be grateful.
* current def: A type of experimental phenotypic evidence resulting from a transplantation in which the transplanted material (stem cells) is from an individual's identical twin.
* **Response: I don't think it's any more a process than other evidences. You can find an example in PUBMED:17477969, in which NN-B16 melanoma are of BL/6 background and are injected to BL/6 mice. How would you capture that?**

**Comment by jbmunro** [comment]
Further discussion with  @dsiegele and @jimhu-tamu,

Proposed changes #1-#3 are fine.  

Regarding #4 'phenomic profiling assay evidence', James needs to work on the definition to emphasize the comparison of multiple strain profiles, that this is a meta-analysis of patterns from many tests of many phenotypes, and that it is a **comparison** of two or more strains based on a **set of phenotypes** across a series of conditions.

**Comment by mgiglio99** [comment]
All of the above were completed (long, long ago) except 6,9,10,12.
Of these only 6 still requires discussion. The others we have decided to leave as is.
Closing, and will make an issue just for 6.
