### ISSUE TITLE
Semicolons in URIs for ECO:000156, ECO:000156 and ECO:000157

### ISSUE THREAD

**Issue by afaulconbridge** [evidenceontology/evidenceontology#175]
In the recent v2018-08-21 release, 3 new terms were added that have semicolons instead of underscores in the URIs - ECO:000156, ECO:000156 and ECO:000157. This means eco.owl can't be correctly parsed using the Python rdflib module, which is a problem for us at https://www.opentargets.org/

Is it possible to fix this please? In the mean time, we can use the last working version of v2018-06-14 but we'd rather not pin to an old version for longer than necessary

**Comment by rctauber** [comment]
Hi @afaulconbridge - thanks for bringing this to our attention. I'll make a fix for this and try to figure out where the error was introduced.

**Comment by rctauber** [comment]
I just published a release with a fix for this, see here: https://github.com/evidenceontology/evidenceontology/releases/tag/v2018-09-03

If you have any other problems parsing the file, please let me know. Also, the full version of `eco.owl` includes OBI and GO mappings. If you don't wish to include these, please use `eco-basic.owl`! Thanks!
