### ISSUE TITLE
Add documentation to gaf-eco-mapping-derived.txt

### ISSUE THREAD

**Issue by mchibucos** [evidenceontology/evidenceontology#177]
The file here is well commented: 
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt

The related corresponding derived file here is not documented and contains no comments:
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

Can @rctauber perhaps add some explanatory comment in the head like the source file? I would like to be able to know source of this file, roughly what it describes, and who is using for what purpose...

**Comment by rctauber** [comment]
Absolutely- I’ll have to think about the best way to do this as we
automatically generate this file during the release. I could either do a
template file (not a ROBOT template) or code the doc string into the
Makefile. Not sure what would be cleaner.

**Comment by mgiglio99** [comment]
Hi @rctauber 
Any new thoughts on this?

**Comment by rctauber** [comment]
I think it would be best to have it in the Makefile, so people don't get confused about which file is which. @mchibucos or @mgiglio99 do you have suggestions for the content of the doc strings?

**Comment by mchibucos** [comment]
I’m editing a copy of the comment section from the other file with info appropriate for this file…

**Comment by mchibucos** [comment]
@rctauber would something like this work as comments for the derived file? Feel free to modify as you see fit.

# Permanent URL of this document:
#  http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt
#
# Always use this URL
#
# About:
# This mapping is derived from a mapping that translates evidence codes used 
# in a GAF to a specific evidence type in ECO. That file can be found here:
# http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt
#
# Here, each row represents a mapping between an ECO class and a GAF evidence
# code (http://geneontology.org/docs/go-annotation-file-gaf-format-21/). 
# Because an ECO class can have many subclasses, multiple ECO classes may map
# to the same GAF evidence code. The highest-level ECO parent class that maps
# to a corresponding GAF evidence code is notated with "Default" (see comments
# concerning GO_REFs in original mapping file above). ECO classes not indicated
# with "Default" are subclasses of the highest-level ECO parent classes that
# map to a GAF code with the "Default" notation.
#
#  1. ECO ID
#  2. GAF evidence code (e.g. IEA)
#  3. Indication ("Default") of highest-level ECO class mapping one-to-one to a GAF
#  evidence code. Blank means it is a child of an ECO class with "Default".
#
# To request changes in the mappings, submit an item to
#  https://github.com/evidenceontology/evidenceontology/issues

**Comment by mchibucos** [comment]
Would something like this work as comments for the derived file?

```
# Permanent URL of this document:
#  http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt
#
# Always use this URL
#
# About:
# This mapping is derived from a mapping that translates evidence codes used 
# in a GAF to a specific evidence type in ECO. That file can be found here:
# http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt
#
# Here, each row represents a mapping between an ECO class and a GAF evidence
# code (http://geneontology.org/docs/go-annotation-file-gaf-format-21/). 
# Because an ECO class can have many subclasses, multiple ECO classes may map
# to the same GAF evidence code. The highest-level ECO parent class that maps
# to a corresponding GAF evidence code is notated with "Default" (see comments
# concerning GO_REFs in original mapping file above). ECO classes not indicated
# with "Default" are subclasses of the highest-level ECO parent classes that
# map to a GAF code with the "Default" notation.
#
#  1. ECO ID
#  2. GAF evidence code (e.g. IEA)
#  3. Indication ("Default") of highest-level ECO class mapping one-to-one to a GAF
#  evidence code. Blank means it is a child of an ECO class with "Default".
#
# To request changes in the mappings, submit an item to
#  https://github.com/evidenceontology/evidenceontology/issues

```

**Comment by rctauber** [comment]
That looks good to me!

**Comment by mgiglio99** [comment]
Need to revise the comment based on how we now generate the file now.
This revision was overlooked when we made the change to the new system.
New comment:

# Permanent URL of this document:
#  http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt
#
# Always use this URL
#
# About:
# This maps specific ECO terms to more general GO evidence codes. 
# This file is automatically generated based on the annotation property "has GO evidence code"
# that is attached to each ECO term. Values for "has GO evidence code" were initially populated 
# based on equivalence mappings of ECO high level terms to GO evidence codes (from 
# http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt) followed by propagation 
# of those GO evidence codes to the corresponding ECO child terms. 
# Currently, this field is populated as part of the term creation and curation process. 
# Child ECO terms may or may not be mapped to the same GO evidence code as their parents. 
# See PMID:34986598 for more details on this system.
# The lines that contain "Default" in the third column are ECO terms with equivalent mappings to 
# GO evidence codes from http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt. 
#
# Each mapping line contains:
#  1. GAF evidence code (e.g. IEA)
#  2. ECO term ID
#  3. Default (optional), only present if the ECO term is equivalent to the GAF evidence code
#
# This document consists of these comments (after #s) followed by a set of mappings,
# each represented as the above 3 columns separated by tabs.
#
# To request changes or report an issue with the mappings, submit an item to
#  https://github.com/evidenceontology/evidenceontology/issues
#

**Comment by mgiglio99** [comment]
Done

**Comment by nsuvarnaiari** [comment]
NOTE: Revised comment lines from Michelle post above have been added to '/Users/snadendla/evidenceontology/src/util/derived-header.txt' file which is read during a release process where the text from this file is appended to the mappings to create ' gaf-eco-mapping-derived.txt' file.

The revised 'derived-header.txt' file has been pushed.
