### ISSUE TITLE
Proposed definitions for ECO terms w/out definitions

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#178]
A recent survey of ECO found 10 terms that lacked definitions.  A search of issues revealed that definitions for these terms have not been previously discussed.

Tentative definitions proposals follow with the intention of generating review and discussion.  

James

**spatial pattern of transcript expression evidence ECO:0000047**
A type of transcript expression evidence that accounts for the position of transcription ranging in scale from the position of genes on the chromosome to differing tissues to regions of an anatomical structure.
Note: really not too sure about this one as I read several papers and the spatial degree that was analyzed varied considerably.

**biological target-disease association via drug evidence ECO:0000360**
mchibucos, 2014-9-26
Becky noted: I think it has something to do with drug-target interactions? https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2199-x
A type of experimental evidence resulting from the prediction of drug-target interactions by computational means.

**protein separation followed by direct sequencing evidence ECO:0000158**
A type of protein separation evidence that is followed by direct protein sequencing whereby a protein's amino acid sequence is determined experimentally by Edman degradation or by mass spectrometry.

**protein separation followed by fragment identification evidence ECO:0000160**
Becky noted: These might help
https://pubs.acs.org/doi/10.1021/bi3005126 and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5632530/
A type of protein separation evidence which then utilizes the screening and identification of small-molecules that bind to proteins.

**peptide affinity enrichment evidence ECO:0001110**
mchibucos, 2014-3-16, SIB:PG
A type of affinity evidence resulting from the appending of affinity tags on proteins so that they may be purified from their biological source using an affinity technique.

**blocking polyclonal antibody evidence ECO:0001015**
mchibucos, 2014-3-16, SIB:PG
A type of immunological assay evidence resulting from the inhibitory effect of polyclonal antibodies (antibodies secreted by different B cell lineages), which while not reacting with a specific antigen, serve to prevent other antibodies from doing so.
Note: 'blocking monoclonal antibody evidence' def. should be reviewed as it states, "A type of immunological assay evidence resulting from inhibitory effect of monoclonal antibody combining with an antigen over other antibodies." but blocking antibodies DO NOT combine / react with antigens.

**macroscopy evidence ECO:0001094**
mchibucos, 2014-3-16, SIB:PG
A type of experimental evidence that is visible to the naked eye cf. microscopy evidence which requires the aid of a microscope.

**spatial pattern of protein expression evidence ECO:0000045**
A type of protein expression evidence that accounts for the position of RNA translation to a protein product ranging in scale from differing tissues to regions of an anatomical structure.
Note: what is protein expression?  There is gene expression and protein production.
Note: really not too sure about this one as I read several papers and the spatial degree that was analyzed varied considerably.

**single exon transcript confirmation via alignment evidence ECO:0000345**
mchibucos, 2013-4-3
Becky noted: Seems like some sort of RNA-seq stuff, this might be a starting point but it might also not be useful: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4897596/
A type of sequence alignment evidence resulting from the comparison of a single exon transcript to a collection / database of known single exon genes.

**transient rescue experiment evidence ECO:0000038**
A type of functional complementation evidence resulting from the introduction of nucleic acids, which are not permanently incorporated into the genome, to temporarily prevent, or "rescue" an organism from a condition.

**Comment by mgiglio99** [comment]
These were defined and released prior to paper publication. Will revisit each of these one by one to assess.
