### ISSUE TITLE
primer extension assay evidence ECO:0001819 

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#179]
Hello @ivanerill and @ehobbs2,

In recent joint CollecTF and ECO discussions it was brought to our attention that while the definition for  'primer extension assay evidence' (ECO:0001819) specifically states "a radiolabeled synthetic oligonucleotide primer", the xref paper talks about fluorescent labelling.  To avoid future confusion, we propose to modify the definition as follows:

A type of transcript expression evidence used to determine expression levels of mRNA where a labeled (radio-, fluorescent-, etc.) synthetic oligonucleotide primer is annealed to mRNA at the transcription start site of a gene and the mRNA is extended with reverse transcriptase producing cDNA which is electrophoresed on a polyacrylamide gel and autoradiographed, and the band size is proportional to the initial RNA.

Does this meet with your approval?

Thanks.

James

**Comment by ehobbs2** [comment]
I'm OK with the proposed fix.

thanks,
Terri

**Comment by jbmunro** [comment]
Thank you @ivanerill and @ehobbs2!

James

**Comment by jbmunro** [comment]
Closing this issue.  Definition modified as suggested.

James
