### ISSUE TITLE
Review 'double mutant phenotype evidence' ECO:0000054

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#185]
Setting a placeholder for discussion regarding this term.

1) Make the definition more clear
2) Comment on why this is distinct from 'mutant phenotype evidence' ECO:0000015
3) Consider modifying the name so that people are not confused / misled

James

**Comment by jbmunro** [comment]
**Note:** 'mutant phenotype evidence' is the parent of 'double mutant phenotype evidence'

1. Tried making the definitions more clear.
2. Tried to address point 2 above by changing both definitions, adding a comment, adding a new reference.
3. Not keen on the idea of modifying the terms as they reflect accepted jargon.

Following is up for discussion with suggestions from those more familiar with this welcome.

James

**mutant phenotype evidence**
**current def:** A type of experimental phenotypic evidence derived from the difference in two alleles of a corresponding gene that result from one or more changes in the genome.
**new def:** A type of experimental phenotypic evidence in which an observable phenotypic difference results from what is usually a natural change or mutation in DNA, reflecting a different form of an allele.
**add comment:** The allele that encodes the phenotype most common in a particular natural population is referred to as the wild type allele, while any other form of that allele is known as the mutant form.
**add comment:** Note that mutations need not be negative.  Changes to DNA sequence (mutations) may be detrimental, have no impact, or be beneficial. 

**double mutant phenotype evidence**
**current def:** A type of mutant phenotype evidence resulting from two mutations in unrelated genetic loci.
**new def:** A type of mutant phenotype evidence resulting from an experiment typically constructed to determine if two different genes have an observable genetic interaction (functional connection) as the result of a mutation occurring in the alleles of the two genes of interest.
**dbxref:** PMID:18305163

**Comment by ivanerill** [comment]
> new def: A type of experimental phenotypic evidence in which an observable phenotypic difference results from what is usually a natural change or mutation in DNA, reflecting a different form of an allele.


So mutant phenotype is meant to be used primarily for work done with _natural_ mutants? Most of the instances I have come across are _artificial_ mutants, where experimenters intentionally knock out/down... a gene to observe a phenotypic difference. The same meaning does not seem to carry over to the double mutant definition.

**Comment by jbmunro** [comment]
Hi @ivanerill,

Good point!  At the time, I was trying to distinguish it from 'site-directed mutagenesis phenotypic evidence', however, given that 'site-directed mutagenesis phenotypic evidence' is a child of 'mutant phenotype evidence' - that cannot be done.

How about the following for 'mutant phenotype evidence'?

**new def:** A type of experimental phenotypic evidence in which an observable phenotypic difference results from ~~what is usually~~ a ~~natural~~ change or mutation in DNA, reflecting a different form of an allele.

James

**Comment by ivanerill** [comment]
@jbmunro I think it works much better this way

**Comment by jbmunro** [comment]
Thank you @ivanerill!

I appreciate the input!

James

**Comment by jbmunro** [comment]
Changes made and pushed to GitHub.  Closing this issue.

James
