### ISSUE TITLE
NTR for cell type defined by clustering (single-cell RNASeq)

### ISSUE THREAD

**Issue by ANiknejad** [evidenceontology/evidenceontology#186]
Dear ECO team,

At Bgee (bgee.org) we are in the process to capture expression data from single-cell RNA-seq, and we would like to make a difference in the annotation of cell type, between cell type identified  'a priori', for example by FACS isolation, and cell type defined 'a posteriori' by clustering of the results. 
For cell type identified by FACS isolation, I guess, ECO:0000268 (flow cytometry evidence) will be fine, but for cell types identified by clustering of cells depending on the results generated by scRNASeq, maybe a new term is request? Open to discussion, and already thank you for your help.
Regards,

Anne Niknejad
Bgee curator

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Thank you for the NTR.  We began discussing this at our last ECO meeting and I will update the ticket soon with some ideas.

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Apologies for the delayed follow up.

In short - the new term 'single cell RNA-sequencing evidence' will be created as a child of 'RNA-sequencing evidence'.  The definition will be "A type of RNA-sequencing evidence that uses a single cell as the source of the RNA."  scRNA-seq will be a synonym.

I will push this forward at my first opportunity in the new year.

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

FYI - the new term, 'single-cell RNA-sequencing evidence' - ECO:0001560 has been added and pushed to GitHub.  Closing this ticket but feel free to open it if need be.

James

**Comment by ANiknejad** [comment]
Hi James, @jbmunro 

Thank you so much for the update. This ECO term will be very useful for annotating cell-type for expression data from scRNA-sequencing evidence.
Actually now I still wondering how to report experimental evidence for cells that are 'simply' isolated from for example embryos, by chemical or mechanistical (by aspiration) way? (that means, 'a priori' claimed cell type, when the authors start to sequence the cells
Apart from FACS or MACS cell isolation, there are other methods to start working on sequencing cells, and these methods, as far as I can see, are not all reported in the Evidence Code Ontology.
Thank you in advance for your help.
Kind regards,
Anne

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Apologies for the tardy response.

I re-opened this ticket to discuss your questions / concerns but I see that you have another ticket open related to this one (#196) so I will close the ticket again and pick up the discussion there.

James
