### ISSUE TITLE
Altered Mappings

### ISSUE THREAD

**Issue by beckyjackson** [evidenceontology/evidenceontology#187]
Over the past year or so, we have done some restructuring. This has resulted in a few changes for classes is the derived mapping file.

We should review these changes to make sure they are appropriate for the class, and have not caused any unintended side effects.

| Label | ECO ID | Old Code | New Code |
| ------ | -------- | :-------: | :---------: |
| differential methylation hybridization evidence | ECO:0000069 | IEP | IDA |
| array-based sequence capture evidence | ECO:0000093 | IEP | EXP |
| cytochemistry evidence | ECO:0001035 | IEP | IDA |
| histochemistry evidence | ECO:0001050 | IEP | IDA |
| tissue microarray evidence | ECO:0001130 | IEP | IDA |
| protein-binding microarray evidence | ECO:0001601 | IEP | IPI |

**Comment by rctauber** [comment]
We added a manual fix for #216 to move ECO:0006095 to IGI as well.

**Comment by mgiglio99** [comment]
Hi Becky - I know this one has been open a long time - but I do still want to take a look at these in light of other mapping changes that were made recently. So, I'm going to keep it open so it stays on my radar screen.

**Comment by mgiglio99** [comment]
These have been reviewed and look fine.
