### ISSUE TITLE
NTR: multilocus sequence typing evidence

### ISSUE THREAD

**Issue by ivanerill** [evidenceontology/evidenceontology#191]
**Name:** multilocus sequence typing evidence
**Definition:** multilocus sequence typing evidence is a type of nucleic acid sequencing evidence in which DNA sequence variations within a specific set of genes (typically housekeeping genes) are used to characterizes strains by their unique allelic profiles. 

**Synonyms:** MLST

**Note:** The technique is predominantly used for bacterial typing, but has also been used in fungi.

**Proposed parent term:** ECO:0000221 - high throughput nucleotide sequencing assay evidence

**Reference:** [PMID:9501229](https://www.ncbi.nlm.nih.gov/pubmed/9501229)

**Example of use:** [PMID:24713082](https://www.ncbi.nlm.nih.gov/pubmed/24713082)

**Comment by jbmunro** [comment]
Hi @ivanerill, 

Thanks for the NTR and very helpful additional info.  

Everything looks good but I am wondering if 'high throughput nucleotide sequencing assay evidence' -  (ECO:0000221) is an appropriate parent.  MLST analysis doesn't necessarily have to be high throughput, does it?  Would 'nucleotide sequencing assay evidence' (ECO:0000219) be a suitable parent?

James

**Comment by ivanerill** [comment]
Hi @jbmunro ,

We were debating so. No, it does not necessarily have to be HT sequencing, although in practice it is (and you could make the argument that for the technique to be useful (and competitive with other techniques, such as PFGE or PCR fingerprinting) it would have to be. So I am ambivalent about which of the two might be the best parent.

Ivan

**Comment by jbmunro** [comment]
Hi @ivanerill,
Apologies that this took so long. The new term is a child of 'nucleotide sequencing assay evidence' as we are still discussing how to deal with HT evidence and its children.  I will have these new terms pushed to GitHub shortly.  I am going to close the ticket but please feel free to re-open it if need be.

James

**NTR: multilocus sequence typing evidence**
**child of:** nucleotide sequencing assay evidence
**def:** A type of nucleotide sequencing assay evidence in which DNA sequence variations within a specific set of genes (typically housekeeping genes) are used to characterizes strains by their unique allelic profiles.
**dbxref:** PMID:9501229
**exact synonym:** MLST
**comment:** see PMID:24713082 for use example

**NTR: multilocus sequence typing evidence used in automatic assertion**
**def:** A type of multilocus sequence typing evidence that is used in an automatic assertion

**NTR: multilocus sequence typing evidence used in manual assertion**
**def:** A type of multilocus sequence typing evidence that is used in a manual assertion
