### ISSUE TITLE
computational evidence (ECO:0007672) review

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#192]
**def:** A type of evidence in which data are generated by a computer.

**history:** This term was developed initially to allow for the development of the 'combinatorial evidence' branch (#189) with the intent of eventually populating it with computer-based evidence terms.

**issue:** Not intuitively in silico and definition is limited to data generation. 

**To do:**

- improve definition
- add exact synonym: in silico evidence

**Comment by ivanerill** [comment]
"Combinatorial evidence" (ECO:0000212) is defined as: 

> "evidence in which at least two distinct types of evidence have been integrated". 

I understand that:
- The evidence may be experimental or computational.
- The integration may be done by a human or a computer.

I take it that the role of "computational evidence" (ECO:0007672) is therefore to become a node from which to logically derive "combinatorial evidence" terms in which the _evidence_ is (at least partly) **computational** (not the integration). Is this correct? If so, it appears as if ECO:0007672 would be acting as a logical placeholder in the "combinatorial" tree, and not necessarily as a root term for deriving computational evidence types.

**Comment by mgiglio99** [comment]
@ivanerill 
Correct, that we made this term for the purpose of the logical connections in the 'combinatorial' branch. But we don't see a reason that prohibits us from adding children to 'computational evidence'. We still plan to do that, but the little bit we've worked on it so far, we realize it will be tricky and will get complicated with regard to 'similarity' terms. So we've not dived into that yet.

**Comment by ivanerill** [comment]
@mgiglio99 OK. If the term is going to be used as a sort of umbrella root node for computational evidence terms, its definition should probably be reworded to clarify that the "generated by" is not circumscribed to simulations (wherein one could confidently state that the computer _generates_ the evidence).

**Comment by jbmunro** [comment]
Hi @mgiglio99 and @ivanerill,

How is this for a new definition for 'computational evidence'?

**new def:** A type of evidence in which data are produced, and/or generated, and/or analyzed on a computer.

Also - is everyone OK with my adding 'in silico evidence' as an exact synonym?  

James

**Comment by ivanerill** [comment]
Hi @jbmunro ,

This is general enough to act as an umbrella root term for computational evidence, and I believe "in silico evidence" would be appropriate as a synonym. The only issue I see is that at this time there is no clear idea of what "computational evidence" will eventually encompass if it does not gobble up the whole "similarity" branch.

**Comment by jbmunro** [comment]
Hi @ivanerill,

Thanks for the input and your concern is noted.  

James

**Comment by mgiglio99** [comment]
Hi @ivanerill 
We have been wondering along the same lines and haven't figured that out yet. 
But we will - I hope.
: )

**Comment by ivanerill** [comment]
Hi @mgiglio99 ,

Not an easy one :-) Happy to chime in if needed.

Ivan

**Comment by jbmunro** [comment]
Definition updated.
Exact synonym added.
Closing ticket.
James
