### ISSUE TITLE
genomic context evidence (ECO:0000177) review

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#193]
In a conversation with CollecTF, the question was raised, "Why isn't 'genomic context evidence' a child of 'similarity evidence'?"

**genomic context evidence**
**def:** A type of evidence in which the location of the gene within the genome provides insight into its function, or provides evolutionary insight.
**children:** gene neighbors evidence, gene neighbors evidence used in automatic assertion, and gene neighbors evidence used in manual assertion

**similarity evidence**
**def:** A type of evidence resulting from comparing likeness of distinct biological entities.
**children:** genetic similarity evidence, phenotypic similarity evidence, phylogenetic evidence, sequence similarity evidence, similarity evidence used in automatic assertion, similarity evidence used in manual assertion

**First impressions:** 
The def for genomic context evidence would need to be re-tooled to emphasize the use of comparison between two entities with the evaluation of likeness or similarity.

**Comment by ivanerill** [comment]
>The def for genomic context evidence would need to be re-tooled to emphasize the use of comparison between two entities with the evaluation of likeness or similarity.
Agree. I believe the driving point here is that genetic context evidence is based on comparison. You either manually look for syntenic regions across multiple genomes to infer likely conservation of function, or you train a model on multiple genomes to make guilt-by-association assignments. In the former case, it is a comparison with other sequences, in the latter a comparison to a model (although that may be stretching the usage of "comparison"; if so, this and other terms should fall under a more general term for bioinformatic prediction that does not carry implicit comparison).

**Comment by mgiglio99** [comment]
Back in the day, when we were doing manual functional annotation at TIGR, we would use this evidence not when doing comparisons between genomes, but when looking at a set of genes in one genome. We'd see that the genes were oriented in the same direction, we'd see that they appeared to have related functions (perhaps to a protein complex). We might see that one of the genes in the operon has weak sequence-based evidence for one of the needed components - not enough to call the function on its own. But the fact that it was located next to the other components boosted the evidence for that protein. The thing we were comparing to was our knowledge of the same protein complex from other organisms and our identifications of neighboring genes. Does that count as similarity?

**Comment by ivanerill** [comment]
>But the fact that it was located next to the other components boosted the evidence for that protein. The thing we were comparing to was our knowledge of the same protein complex from other organisms and our identifications of neighboring genes. Does that count as similarity?

Tricky one ;-) But I would say that, yes, you had a model in your brain of synteny and you were comparing (informally) to that model. In my mind, that is equivalent to "motif similarity evidence" (ECO:0000028), which can be done formally by an algorithm (e.g. a PSSM/HMM matching) or visually by a researcher who has a solid working knowledge of the motif. But, again, these are fine distinctions to make, which harken back to the concept of whether all (or most) bioinformatics methods should be formally considered comparison-type forms of evidence.

**Comment by jbmunro** [comment]
Hi @ivanerill and @mgiglio99, 

Sorry - this one fell through the cracks.

So we are all agreed that 'genomic context evidence' is better placed as a child of 'similarity evidence' rather than the current situation where it is a child of 'evidence'?  I am inclined to agree with Ivan that the degree of similarity is being taken into account.

If so, would this new definition be sufficient?  (I simply changed the parent)

**genomic context evidence**
**new def:** A type of similarity evidence in which the location of the gene within the genome provides insight into its function, or provides evolutionary insight.

I'm wondering if I need to further drive home that a comparison is being made.  Given that is inferred from the parent term, I think not.

Thoughts?

James

**Comment by ivanerill** [comment]
I believe that we need not be explicit about the type of comparison (or the fact that a comparison is made), unless we want to specify the different types of genomic context methods available.

Here are some references that might help illustrate these methods:
https://www.ncbi.nlm.nih.gov/pubmed/10958625
https://www.ncbi.nlm.nih.gov/pubmed/10427000
https://www.ncbi.nlm.nih.gov/pubmed/15229555

For simplicity, the definition could be reworded:

> **new def:** A type of similarity evidence in which the location of the gene within the genome provides insight into its function or its evolutionary history.


If we want to add the explicit _comparison_ thing:

> **new def:** A type of similarity evidence in which genomic comparisons based on the location of a gene within the genome provide insight into its function or its evolutionary history.

**Comment by jbmunro** [comment]
Thanks to all for the input.

Changes made and pushed to GitHub.

Closing ticket.

James
