### ISSUE TITLE
deletion mutation phenotypic evidence and knockout phenotypic evidence review

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#194]
**issue:** Need to better explain when to use deletion mutation evidence vs. knockout evidence

**deletion mutation phenotypic evidence**
**def:** A type of mutant phenotype evidence resulting from a mutation in which there is a removal of one or more contiguous nucleotides.
**new def:** A type of mutant phenotype evidence resulting from a mutation in which there is the removal of one or more contiguous nucleotides that may alter the function of the resulting protein(s).
**add comment:** As a child of 'experimental phenotypic evidence', this is not to be confused with the biological processes deletion mutation / deletion deficiency in which DNA is lost during DNA replication.
**add comment:** The length of the DNA deleted can range from a single nucleotide to enough material that could include multiple genes.
**add comment:** cf. knockout phenotypic evidence in which any number of changes to the DNA result in elimination of the function of the gene in question.

**knockout phenotypic evidence**
**NB:** currently the term is 'knockout evidence' with the proposed change to 'knockout phenotypic evidence'
**def:** A type of genetic transformation evidence resulting from the removal of a particular gene (or genes), disrupting the function and allowing for functional analysis.
**new def:** A type of genetic transformation evidence resulting from a change in the DNA that results in the elimination of the function of the gene, allowing for functional analysis.
**add comment:** A change in the DNA may result from any number of processes such (deletion, insertion, frame shift, etc.) Additionally, the gene may be made inoperative via homologous recombination, site-specific nucleases, zinc finger nucleases, transcription activator-like effector nucleases (TALENs), or CRISPR (Clustered regularly interspaced short palindromic repeats).
**add comment:** cf. deletion mutation phenotypic evidence in which DNA is deleted which may result in altering the function of the resulting protein(s).
add narrow synonyms: gene deletion evidence, gene knockout evidence

relates to #172

**Comment by ivanerill** [comment]
The experimental stance in knockout phenotypic evidence is to knock out the gene, see what happens; this is not so for deletion mutation phenotypic evidence. I would not restrict the definition of the latter to effects on "proteins". I would go with something like "that may result in altered function or other measurable properties".

**Comment by jbmunro** [comment]
Modifications made, pushed to GitHub.

Thanks for the input!

Closing ticket.

James
