### ISSUE TITLE
ECO term: ECO:0000325

### ISSUE THREAD

**Issue by lascanom** [evidenceontology/evidenceontology#195]
Hello,

I was looking for a manual/automatic asserted version of chromatography (ECO:0000325), in order to describe, for example, paper-chromatography that doesn't appear in the ECO terms. Should I make a request for new term? Or is there another code I would have missed?
Thank you in advance for your help!

**Comment by rctauber** [comment]
Hi @lascanom - thank you for bringing this up!

I just added two new classes, as these should definitely exist:
* ECO:0007680 - chromatography evidence used in manual assertion
* ECO:0007681 - chromatography evidence used in automatic assertion

These will be available in the next release of ECO, happening Feb 1.

As for more-specific terms that don't appear in ECO, please feel free to request them! If you want to request a new type of chromatography evidence, just include a label and a proposed definition (you don't need to open a new issue).
