### ISSUE TITLE
NTRs: looking for ECO classes for technique or assay used to generate expression data from single-cells

### ISSUE THREAD

**Issue by ANiknejad** [evidenceontology/evidenceontology#196]
this issue is related to #186 
Now we have then
ECO:0001560 single-cell RNA-sequencing evidence
but 
in the annotation process of expression data from single-cell dataset, we aim to make distinction between cell type identified 'a priori', (ex. by FACS isolation), and cell type defined 'a posteriori' by clustering of the results, and we (maybe) need a larger panel of ECO classes for technique or assay used to generate the evidence of 'a priori' defined cell-type, I mean, the cell-type that the authors isolated to perform scRNA-sequencing:
* cells isolated (and maybe identified) by size at a specific developmental time, from a dissected embryo (cf PMID:27554860)
* or simply, cells isolated by any physical technique of dissociation, but from a defined tissue, and then broadly defined by the authors as, for example, 'hepatocytes'

(see WP: 'Many single-cell analysis techniques require the isolation of individual cells. Methods currently used for single cell isolation include: serial dilution, micromanipulation, laser capture microdissection, FACS, microfluidics, Dielectrophoretic digital sorting, manual picking, enzymatic digestion, and Raman tweezers')

Any help here will be greatly appreciated.

Anne Niknejad
curator for Bgee (bgee.org)

**Comment by jbmunro** [comment]
Hi @ANiknejad,

I am bringing this ticket up for discussion at the next ECO meeting.  

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Apologies for the tardy reply.

Can I assume that the assertion that you wish to make is that "This is cell type X based on evidence Y?"  That is, is the assertion you wish to make the identification of a certain cell type based on a type of evidence?

We can create evidence terms that assert cell type X based on Y evidence (such as 'FACS evidence'), and we can capture types of technologies (such as '10X single-cell RNA-sequencing evidence' or 'SmartSeq single-cell RNA-sequencing evidence'.) However, we would not want to make terms that combined steps such as ''10X single-cell RNA-sequencing evidence derived from cells sorted by FACS'. That would be trying to encode a protocol into a term name. One could imagine also then capturing things like if the source of the cells was cell culture or fresh tissue - this becomes unmanageable. If you want to capture protocols in an ontological way, this falls under the purview of OBI. For annotation purposes, I suggest annotating with the ECO term that represents the primary piece of evidence that led to the conclusion.

I hope this helps to explain the scope of what we can provide. Happy to discuss this further as well. If you have a specific set of evidence terms that you would like to add to ECO, I am more than happy to work with you to make this possible.  To speed the process along, I would ask for your help in providing a list of terms, definitions, and possible papers that can be used as database cross references.

Thank you.

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Just following up on this and wondering if there is anything further I can do.

James

**Comment by ANiknejad** [comment]
Hi James, I am very sorry to be late answering you, thank you so much for managing that. 
Actually, yes I would like to have 'evidence terms that assert cell type X based on Y evidence (such as 'FACS evidence')', because in Bgee (bgee.org) we are on the process to annotate expression data from single-cell sequencing, and we would like to annotate in 2 steps: 
-first, to annotate the cell type identified by the authors as the cells they used for the single-cell sequencing, 
-then in a second step, and still for the same library, the (new) cell-type the authors can at the end specify thanks to the clustering of the results from the single-cell RNA-seq, and for this second step, yes, the 'ECO:0001560 single-cell RNA-sequencing evidence' is fine. 
Here an interesting paper that, I guess, emphasizes the issue I am encountering:
https://www.ncbi.nlm.nih.gov/pubmed/?term=29149607
From FACS isolated olfactory projection neurons (PNs), many cell-sub-types are identified at the end of the single-cell RNA-seq analysis. So here the 'a priori' cell-type evidence is FACS, ok, and the 'at posteriori' cell-(new)type evidence is ECO:0001560 single-cell RNA-sequencing evidence', ok.
I also understand that I am mixing a bit the concept of ECO and OBI, but I wanted to anticipate any other new cell-type results that may come from 'a priori' evidence of 'general' cell-type isolated by any method other than FACS, because:
"WP: 'Many single-cell analysis techniques require the isolation of individual cells. Methods currently used for single cell isolation include: serial dilution, micromanipulation, laser capture microdissection, FACS, microfluidics, Dielectrophoretic digital sorting, manual picking, enzymatic digestion, and Raman tweezers"
Many thanks in advance for your patience, and thank you again for being open to discussion.
Best regards,

Anne

**Comment by jbmunro** [comment]
Hi @ANiknejad,

No apology necessary and happy to help!

I think that I now better understand what you need. You want to request terms that cover the possible types of evidence that are used to determine what a cell type is - correct? (Be it a priori or a posteriori matters not as the terms should be applicable to either situation.)

As I noted earlier, please feel free to provide a list of terms.  Additionally, if you provide definitions, and possible papers that can be used as database cross reference, it will speed up the process and make things more clear.  For example, you note "serial dilution" above.  I am unfamiliar with just how this provides evidence for determining cell type.  To me, serial dilution is a process/method involving the stepwise dilution of a substance in solution.

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Checking in to see where we stand with your NTRs.  If you have a list of terms and can provided definitions and reference papers to speed the process, I can move forward with this.

James

**Comment by ANiknejad** [comment]
Hi @jbmunro 
Very sorry not being able to answer you more quickly. Actually I still have to do some work for providing definitions and reference papers, thank you for your patience. Cheers,
Anne

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Not a problem at all.  I just wanted to make sure that this was still an active request.

James

**Comment by ANiknejad** [comment]
Hello James, I got the feeling I made complicated something very easy actually...
When annotating samples for bulk RNA-seq, I never tried to put an ECO term on the sample itself actually, because the sample is considered as it is claimed by the experimenter, but here with scRNA-sequencing we can a posteriori re-annotate the 'sample' (=cell) thanks to the results of the sequencing and here ECO:0001560 single-cell RNA-sequencing evidence is appropriate. I just wanted to put an ECO also at the first annotation level, but maybe 'experimental evidence' or even nothing as previously is fine??

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Sorry - I am not fully following.  Would it be possible to provide an example or two?  

Thank you.

James

**Comment by ANiknejad** [comment]
Hi James,
this paper was the reason for this brainstorming...

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6095479/

"Single-cell RNA-seq has recently emerged as a powerful technique to investigate cellular heterogeneity, discover new cell types, and identify cell type-specific markers. We established a robust single-cell RNA-seq protocol for Drosophila neurons and glia. By focusing on olfactory projection neurons (PNs), among the best characterized cell types in all nervous systems, we established unequivocally that transcriptomic identity corresponds with the anatomical and physiological neuronal subtypes defined by connectivity and function."

The fact that scRNA-seq of a defined cell-type allows to discover new (potentiential) sub-cell-type thanks to new markers gave me the reason to ask for making difference between 'a priori' and 'a posteriori' evidence codes...I am not sure how much I am more clear here, sorry for the trouble...

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Thanks for the reference and for pulling out the section of interest.  

Apologies for the confusion on my part.   

I am struggling to understand what you are looking for us to provide:
1) A series of evidence terms that are applicable to the identification of a cell's type?
2) An evidence term applicable to the identification of a cell's type for this paper only?
3) A generic evidence term applicable to the identification of a cell's type?

If 1, then I need you to provide a list of terms, definitions for those terms, and where possible, papers that can be used as database cross references.

If 2, then to be honest - I am having trouble seeing a strong assertion being made with regard to 'a priori' cell type determination in the example provided.  Essentially, what is being stated in the excerpt is that a protocol was developed using transcriptomic data from scRNA-Seq data to create cell-specific gene expression profiles that corresponds with cells defined by either anatomic or physiological means.  But what exactly are the types of evidence used to define a cell by anatomic or physiological means?  It is not clearly stated here.

If 3, I cannot think of a generic, "catch-all" term that would be suitable or applicable.  In fact, ECO strives to try provide as specific a type of evidence term as possible. Certainly you could use 'experimental evidence', however, there is a lack of specificity.  If you have a term in mind - please feel free to request it.

I reached out to my colleague @nsuvarnaiari who suggested that you might be looking for a single term to annotate this paper (i.e. 2 above).  Both @nsuvarnaiari and I have read the provided paper.  @nsuvarnaiari suggested that the sentence you might be trying to annotate is this one: 

"We sequenced cells from Drosophila pupal brains that were labeled by the astrocyte driver alrm-GAL4 (Doherty et al., 2009) and olfactory projection neurons (PNs) labeled by the GH146-GAL4 driver, which is expressed in 40 of 50 PN classes (Stocker et al., 1997; Jefferis et al., 2001) (Figure 1C)."

If this is so, then I believe that the labeled cells were identified 'a priori' because they express GFP.  ECO has the evidence term 'green fluorescent protein immunolocalization evidence'.  Will this term work for you?

Please let me know what I can do to help.

James

**Comment by ANiknejad** [comment]
Dear James, @jbmunro 

Thank you very much for your kind attention and efforts to support my messy request!
Yes, I was looking for "1. A series of evidence terms that are applicable to the identification of a cell's type."
But your colleague @nsuvarnaiari (please say thank you to him from my side!) is right too, for this paper I was looking to report the evidence for the 'a priori' brain cells, that are actually 2 different cell types identified by GFP.
In bgee.org, we annotate RNAseq from 'bulk' and now 'single cells' libraries, and the annotation procedure is obviously not the same, due to the results the authors usually provide after scRNA-seq sequencing.
At the end we decided to annotate only papers with clear transcriptomics of cell-type, without dealing with complex clusters of 'new' sub-sub-cell types.
Once again, thank you very much for your help, James, and thank you for your time and your patience.
Kind regards,

Anne

**Comment by jbmunro** [comment]
Hi @ANiknejad,

No problem at all.

So - where do we stand with this?  It sounds like you have resolved the issue of annotating the paper at hand, but what about the series of evidence terms that describe the identification of a cell's type?

I would like to suggest that we close this ticket and that as you come across the need for additional terms, you open new tickets and request new terms as needed.

Please let me know how you wish to proceed.

James

**Comment by ANiknejad** [comment]
Hi @jbmunro ,
I agree, we can close this ticket. Also some work is in progress concerning the set up of minimal requirements for single-cell RNA-seq data, maybe you could have a look at this document here:
https://docs.google.com/document/d/1UglgMOlmzbZQPe4JG5v8-75iaQ1ezt97Dz83qKncuA8/edit#

**Comment by jbmunro** [comment]
Hi @ANiknejad,

OK - closing the ticket.  Thanks for the link to the manuscript.  Feel free to create new tickets for new term requests as they arise.

James
