### ISSUE TITLE
Non-simple property in cardinality restrictions

### ISSUE THREAD

**Issue by balhoff** [evidenceontology/evidenceontology#197]
ECO uses 'has part' in several different cardinality restrictions, for example:

`'combinatorial computational evidence' SubClassOf 'has part' min 2 'computational evidence'`

Non-simple properties (here caused by 'has part' being transitive) in these axioms are disallowed in OWL so this prevents using ECO with a reasoner that handles cardinality restrictions (like HermiT); see [Global Restrictions on Axioms in OWL 2 DL](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Global_Restrictions_on_Axioms_in_OWL_2_DL).

**Comment by rctauber** [comment]
These axioms do not exist in `eco-basic.owl`. We can make another version to support your use case, if necessary. Which product are you using now?

**Comment by balhoff** [comment]
We have been using eco-base. Probably we could switch to eco-basic, thanks. I would think you would want to modify the axioms in any case though, since they make ECO invalid OWL.

**Comment by beckyjackson** [comment]
These axioms have been updated to use `some` instead of `min` to resolve this issue.
