### ISSUE TITLE
NTR: Spheroplast Fusion Assay

### ISSUE THREAD

**Issue by sandyl27** [evidenceontology/evidenceontology#198]
NTR: Spheroplast Fusion Assay evidence used in manual assertion - membrane fusion

Definition: A type of membrane fusion assay evidence based on the fusion of spheroplasts used in manual assertion. 

Parent term: Suggested- Membrane fusion evidence used in manual assertion- probably under in vitro

Reference:PMID: 25870259

@jimhu-tamu

**Comment by jbmunro** [comment]
Hi @sandyl27, 

Thank you for the NTR.  I will start working on this and bring it up for discussion at the next ECO meeting.

James

**Comment by jbmunro** [comment]
Hi @sandyl27,

I plan on moving forward with the following NTRs:

**New term: 'membrane fusion assay evidence’**
child of: 'direct assay evidence'
def: A type of direct assay evidence in which a broad variety of physiological processes are measured when two separate membranes merge into a single contiguous membrane.
comment: Measurements can include but are not limited to: synaptic transmission, fertilization, and viral entry.
Xref: PMID:1836993

**New term: 'membrane fusion assay evidence’ used in automatic assertion
New term: 'membrane fusion assay evidence’ used in manual assertion**

**New term: ‘Spheroplast fusion assay evidence’**
child of: 'membrane fusion assay evidence’
def: A type of membrane fusion assay evidence based on the fusion of spheroplasts.
comment: A spheroplast is a Gram-negative bacterium cell in which the cell wall has been almost completely removed. 
Xref: PMID:25870259

**New term: ‘Spheroplast fusion assay evidence’ used in automatic assertion
New term: ‘Spheroplast fusion assay evidence’ used in manual assertion**

The updated terms will be pushed to GitHub in short order.

James

**Comment by jbmunro** [comment]
Above NTRs added and pushed to eco-edit.owl.  They will be more readily available with the next release.  Closing this ticket as the work is completed.

James
