### ISSUE TITLE
ECO:0000120 - ECO:0005027 relationship

### ISSUE THREAD

**Issue by ivanerill** [evidenceontology/evidenceontology#200]
We were wondering whether ECO:0000120 should be a child of ECO:0005027, since ECO:0000120 implies introduction of DNA for overexpression, which is covered by the ECO:0005027 transformation term.

**Comment by pgaudet** [comment]
I don't think transformation implies overexpression, it usually implies
exogenous expression.

Thanks, Pascale

Le mer. 20 févr. 2019 à 12:14 AM, Ivan Erill <notifications@github.com> a
écrit :

**Comment by ivanerill** [comment]
Hi @pgaudet ,

I agree. It may have come across wrongly, but our idea was the opposite: that overexpression (ECO:0000120) might imply transformation (ECO:0005027). At least the way it's worded out now, ECO:0000120 "...a transgenic organism that has been engineered to overexpress..." and ECO:0005027 "the introduction of exogenous DNA". Transgenic seems to me to imply exogenous DNA?

Cheers,

Ivan

**Comment by jbmunro** [comment]
Hi @ivanerill and @pgaudet 

Posting the terms and definitions to the above discussion below and putting the issue on the list of items for discussion at the next ECO meeting.

James

**ECO:0000120 'over expression analysis evidence'**
_child of: 'experimental phenotypic evidence'_
def: A type of experimental phenotypic evidence in which a gene and/or gene product is investigated in a transgenic organism that has been engineered to overexpress that gene product.
has_related_synonym: IMP: analysis of overexpression/ectopic expression phenotype

**ECO:0000059 'experimental phenotypic evidence'**
_current parent for 'over expression analysis evidence'_
def: A type of experimental evidence that is based on an observable characteristic trait, which is the result of the expression of an organisms genotype in an environment.

**ECO:0005027 'genetic transformation evidence'**
_suggested new parent for 'over expression analysis evidence'_
def: A type of mutant phenotype evidence resulting from the conversion of one genotype into another by the introduction of exogenous DNA.

**Comment by pgaudet** [comment]
That seems OK to me.

**Comment by ivanerill** [comment]
to complete the list:

**ECO:0005027 'mutant phenotype evidence'**
_Current parent for 'genetic transformation evidence'_
A type of experimental phenotypic evidence derived from the difference in two alleles of a corresponding gene that result from one or more changes in the genome.

**Comment by jbmunro** [comment]
Apologies for not getting to this sooner.  I checked the mapping files and making ECO:0000120 a child of  ECO:000502 will have no impact so I will make this change and get it pushed this morning.  

Closing this ticket.

James
