### ISSUE TITLE
NTR: polysome profiling

### ISSUE THREAD

**Issue by MABeebe** [evidenceontology/evidenceontology#201]
Name: polysome profiling
Definition: polysome profiling is a biochemical technique that is used to study the associations between multiple ribosome and mRNAs. 
Parent Term: Unclear
PMID: 30545912 
Will also require a "used in manual assertion" term 
@jimhu-tamu 
@sandyl27

**Comment by jbmunro** [comment]
Hi @jimhu-tamu and @sandyl27,

Thank you for the NTR, suggested definition and Xref.

I will get to work on this.

James

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

Apologies that this has taken so long.  I hope to discuss the following at our next ECO meeting.

James

**Issue:** no optical density evidence (possible parent) - what else could it be, or if appropriate, do I create new parent term?

**NTR: polysome profiling evidence**
**child of:** ???
**def:** A type of X evidence employed to study the associations between multiple ribosomes and mRNA that utilizes density gradient centrifugation to separate out the lysate of cells of interest with the objective of isolating polysomes/polyribosomes which are complexes of an mRNA molecule and two or more ribosomes that act to translate mRNA.  The optical density of the fractions is then determined.
**dbxref:** PMID:30545912
**comment:** Once isolated, gel electrophoresis, immunoblot, and other protein profiling techniques can be applied to garner more information

**NTR: polysome profiling evidence used in automatic assertion**
def: A type of polysome profiling evidence that is used in an automatic assertion.

**NTR: polysome profiling evidence used in manual assertion**
def: A type of polysome profiling evidence that is used in a manual assertion.

**Comment by mgiglio99** [comment]
How about making it a child of direct assay or even of experimental evidence?

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

As per Michelle's suggestion, this term (and its children) are children of 'experimental evidence'.  All have been added to ECO and will be pushed to GitHub later this morning.  Closing this ticket.

James
