### ISSUE TITLE
children of 'protein assay evidence' ECO:0000039

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#203]
Just making a ticket for this so we can keep track.
@rctauber  suggested removing  'protein assay evidence' ECO:0000039.
Many of its children have dual parentage and the ECO:0000039 parent is not adding value. 
Becky will make suggestions for rehoming any children that do not have a second parent, and overall new structure.

**Comment by rctauber** [comment]
## Suggested Changes

* 'protein assay evidence' -> deprecate
* 'immunoprecipiatation assay evidence' -> SEE BELOW (maybe 'physical interaction evidence')
* 'specific protein inhibition evidence' -> 'physical interaction evidence'
* 'peptide array evidnece' -> 'physical interaction evidence' (based on definition)
* 'phosphoamino acid analysis evidence' -> SEE BELOW
* 'enzyme assay evidence' -> deprecate
* 'TACE activity assay evidence' -> 'protein detection evidence'

## 'phosphoamino acid analysis evidence' 

'protein kinase assay evidence' has an almost the EXACT defintion of 'phosphoamino acid analysis evidence', but they are not actually the same. In short, protein kinase assays look at the *activity* of the enzyme (protein kinase). Phosphoamino acid analyses look at the resulting phosphoproteins.

Here is a new suggested definition for 'protein kinase assay evidence':
> A type of X that measures transfer of a phosphate to a peptide or protein substrate by a protein kinase. [https://www.ncbi.nlm.nih.gov/books/NBK91991/]

I would argue that, based on this defintion, 'protein kinase assay' could be a child of 'physical interaction evidence' (currently it is under 'direct assay evidence').

Suggested definition for 'phosphoamino acid analysis evidence':
> A type of X that identifies which amino acids in a protein are have been phosphorylated. [PMID:11680867, https://en.wikipedia.org/wiki/Phosphoamino_acid_analysis]

I'm not sure if this would belong under 'physical interaction evidence' or not. In my opinion, this seems to be a type of 'small molecule detection assay evidence'.

## 'immunoprecipiatation assay evidence'

OBI defines an 'immunoprecipitation assay' as testing a mixture of antibodies and bound antigen for "presence of a specific antigen" or "presence of antigen specific antibodies". Does this seem like it would fall under 'physical interaction evidence', as you are using the interaction between the antigen and the antibodies?

**Comment by rctauber** [comment]
> 'protein assay evidence' -> deprecate 

We will proceed with this change.

> 'immunoprecipitation assay evidence' -> SEE BELOW (maybe 'protein binding')
 
This node will be moved to 'protein binding evidence'.

> 'specific protein inhibition evidence' -> 'protein binding evidence' 

This will be moved to 'direct assay evidence' and 'specific' will be removed from the label.

> 'peptide array evidence' -> 'protein binding evidence'

We will proceed with this change. See #211 for related issue.

> 'phosphoamino acid analysis evidence' -> SEE BELOW

This will be moved to 'direct assay evidence'. The definition will be refined.

> 'enzyme assay evidence' -> deprecate

This will not be deprecated. Instead, we will move this to 'direct assay evidence' and rename it to 'enzymatic activity assay evidence'. Finally, we will make a new term 'ribozyme activity assay evidence', subclass of this term.

> 'TACE activity assay evidence' -> 'protein detection evidence'

This will remain a child of 'enzymatic activity assay evidence' ('enzyme assay evidence').

> 'protein kinase assay evidence': A type of X that measures transfer of a phosphate to a peptide or protein substrate by a protein kinase. [https://www.ncbi.nlm.nih.gov/books/NBK91991/]

This will be moved to 'enzymatic activity assay evidence' and will get the new definition.

**Comment by rctauber** [comment]
Changes implemented in 264463f
