### ISSUE TITLE
mass spec evidence 

### ISSUE THREAD

**Issue by sandyl27** [evidenceontology/evidenceontology#204]
We have several students in CACAO who are annotating different mass spec evidences and we were wondering how specific you were planning on having terms. 

for example we have a paper that shows ion trapping and weren't sure how to define it yet because we don't know how specific to be. 

@jimhu-tamu
@jrr-cpt

**Comment by jrr-cpt** [comment]
One term request related to this discussion that has been submitted is in [issue 205](https://github.com/evidenceontology/evidenceontology/issues/205).

**Comment by jbmunro** [comment]
Hi @sandyl27, @jrr-cpt, and @jimhu-tamu,

We are more than happy to to work with you to develop more specific terms - as requested.  Examples include, but are not limited to, your request https://github.com/evidenceontology/evidenceontology/issues/205, ion trap, quadrupole mass filter, ion cyclotron resonance, time of flight, sector magnet.

James

**Comment by jbmunro** [comment]
Closing this ticket. 

Please open a new ticket with future mass spec related term requests.  

Thanks.  

James
