### ISSUE TITLE
NTR: Liquid chromatography mass spectrometry evidence

### ISSUE THREAD

**Issue by jaydclark** [evidenceontology/evidenceontology#205]
Proposed name(s): Liquid chromatography coupled with tandem mass spectrometry evidence (one for use in manual assertion and one for use in automatic assertion)
Proposed definition: A type of spectrometry evidence using liquid chromatography to separate particles in solution, followed by identifying the amount and type of material entities present in a sample by fragmenting it and measuring the mass-to-charge ratio of the resulting particles.
Relationships: parent term - ECO:0001096 (mass spectrometry evidence)
References: PMID:30366363

NTR for CACAO class.
@jimhu-tamu, @sandyl27, @jrr-cpt

**Comment by jrr-cpt** [comment]
This term request is related to the discussion in [issue 204](https://github.com/evidenceontology/evidenceontology/issues/204).

**Comment by jbmunro** [comment]
Hi @jaydclark, @jimhu-tamu, @sandyl27, @jrr-cpt,

The following were added and pushed to GitHub.

**NTR: liquid chromatography coupled with tandem mass spectrometry evidence**
child of: mass spectrometry evidence
def: A type of mass spectrometry evidence where liquid chromatography is used to separate particles in solution, followed by fragmentation and measurement of the mass-to-charge ratio of the resulting particles to identify the amount and type of material entities present in a sample.
xref: PMID:30366363
 
**NTR: liquid chromatography coupled with tandem mass spectrometry evidence used in automatic assertion**
child of: liquid chromatography coupled with tandem mass spectrometry evidence
def: A type of liquid chromatography coupled with tandem mass spectrometry evidence that is used in an automatic assertion
 
**NTR: liquid chromatography coupled with tandem mass spectrometry evidence used in manual assertion**
child of: liquid chromatography coupled with tandem mass spectrometry evidence
def: A type of liquid chromatography coupled with tandem mass spectrometry evidence that is used in a manual assertion
 
Reaching out to @rctauber for help with OBI logical def.

Closing this ticket.

James
