### ISSUE TITLE
NTR: Ion Trap Mass Spectrometry

### ISSUE THREAD

**Issue by alexisjmoreno** [evidenceontology/evidenceontology#206]
Name: Ion Trap Mass Spectrometry Evidence
Definition: Ion trap mass spectrometry is a type of spectrometry evidence that utilizes a combination of magnetic and/or electric fields to capture charged particles in tandem with mass spectrometry. 
Parent Term: Mass Spectrometry Evidence (ECO:0001096)
Suggested child terms: Ion Trap Mass Spectrometry Evidence used in Manual Assertion, Ion Trap Mass Spectrometry Evidence used in Automatic Assertion
PMID: 15613308
@jimhu-tamu, @cross12tamu, @jrr-cpt, @sandyl27

**Comment by jbmunro** [comment]
Hi @alexisjmoreno, @jimhu-tamu, @cross12tamu, @jrr-cpt, @sandyl27,

Thank you for the NTR.  I will review the request shortly.

James

**Comment by jbmunro** [comment]
Hi @alexisjmoreno, @jimhu-tamu, @cross12tamu, @jrr-cpt, @sandyl27,

Sorry this has taken so long.  I hope to push forward with the following a.s.a.p.

James

**NTR: ion trap mass spectrometry evidence**
**child of:** mass spectrometry evidence
**def:** A type of mass spectrometry evidence where a combination of magnetic and/or electric fields are utilized to capture charged particles in tandem with mass spectrometry.
**dbxref:** PMID:15613308
 
**NTR:** ion trap mass spectrometry evidence used in automatic assertion
**def:** A type of ion trap mass spectrometry evidence that is used in an automatic assertion.
 
**NTR:** ion trap mass spectrometry evidence used in manual assertion
**def:** A type of ion trap mass spectrometry evidence that is used in a manual assertion.

**Comment by jbmunro** [comment]
Hi @alexisjmoreno, @jimhu-tamu, @cross12tamu, @jrr-cpt, @sandyl27,

The requested terms have been added to ECO and will be pushed to GitHub later this morning. Closing this ticket.

James
