### ISSUE TITLE
Atomic Force Microscopy

### ISSUE THREAD

**Issue by ehobbs2** [evidenceontology/evidenceontology#207]
Atomic Force Microscopy

Synonym: AFM

Generated from sentence in Pubmed id 22479184:
"AFM revealed loop structures stabilized by multiple EspR dimer of dimers suggesting the presence of several distant EspR binding sites in the espACD upstream region."

Parent term -- ECO:0001098, microscopy evidence. However, ECO:0001098 has this definition: "A type of direct assay evidence where a microscope was used to view a sample." I'm not sure if "viewing a sample" is the right parent or root for atomic force microscopy.

Definition -- I found 2 at Science Direct Topics that reference other sources.
https://www.sciencedirect.com/topics/engineering/atomic-force-microscopy:
"Atomic force microscopy (AFM) is a technique which maps the surface of a material using a microfabricated cantilever as a scanning probe." From: Monitoring and Evaluation of Biomaterials and their Performance In Vivo, 2017
OR
https://www.sciencedirect.com/topics/chemistry/atomic-force-microscopy:
"Atomic force microscopy (AFM) is a powerful imaging technique that, by scanning a sharp tip (typical end diameter 5–10 nm) over a surface, can produce topographical images which quantify surface morphology on an area scale comparable to that encountered by a colloid interacting with that surface (Binnig et al., 1986)." From: Nanocoatings and Ultra-Thin Films, 2011

**Comment by jbmunro** [comment]
Hi @ehobbs2 ,

Thank you for the NTR. I will review the request shortly.

James

**Comment by jbmunro** [comment]
Hi @ehobbs2,

Apologies for not getting back to you sooner.  

I agree - given the capabilities of AFM, the proposed parent definition needs to be modified.  I hope to bring the following up at the next ECO meeting and will keep you posted.

James

**'microscopy evidence'**
**current def:** A type of direct assay evidence where a microscope was used to view a sample.
**new def:** A type of direct assay evidence resulting from the use of a microscope.
**new comment:** Microscopy may be either: optical, electron, scanning probe, or X-ray.
 
**NB:** As crummy as this proposed definition might be, it fits the style of the sibling term defs.  Typically, one thinks of using a microscope to view a sample - be it directly with your eyes (light microscopy) or even an image - printed on on-screen (electron microscopy).  However, in this case, one can do more than just view a sample (see comment 2 below).
 
**NTR: atomic force microscopy evidence**
**child of: microscopy evidence**
**def:** A type of microscopy evidence where a mechanical probe is applied to a sample (i.e. a type of scanning probe microscopy) which can result in production of an image (with resolution in the order of fractions of a nanometer), force measurement, or sample manipulation.
**comment 1:** Example sentence provided by CollecTF from PMID:22479184: "AFM revealed loop structures stabilized by multiple EspR dimer of dimers suggesting the presence of several distant EspR binding sites in the espACD upstream region."
**comment 2:** Atomic force microscopy can be used for force measurement (force spectroscopy), imaging (rendering a three-dimensional shape (topography)), and manipulation of the sample.
**exact synonym:** AFM
**exact synonym:** scanning force microscopy
**exact synonym:** SFM
 
**NTR: atomic force microscopy evidence used in automatic assertion**
def: A type of atomic force microscopy evidence that is used in an automatic assertion
 
**NTR: atomic force microscopy evidence used in manual assertion**
def: A type of atomic force microscopy evidence that is used in a manual assertion

**Comment by jbmunro** [comment]
Hi @ehobbs2 

The above changes have been made and will be pushed to GitHub shortly.  Closing the ticket.

James
