### ISSUE TITLE
redefine 'immunoprecipitation evidence' (ECO:0000085)

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#212]
Definition of  ECO:0000085 is confusing.

**Comment by rctauber** [comment]
Current defintion:
> A type of protein binding evidence that involves precipitation of a multivalent antigen by a bivalent antibody for protein isolation.

**Comment by mgiglio99** [comment]
How about:
A type of protein binding evidence where an antibody specific for a target protein is used to precipitate the target protein along with any other molecules (e.g. protein, nucleic acid) that are bound to the target protein.

**Comment by nsuvarnaiari** [comment]
Revised definition has been pushed in April release, 2023.
