### ISSUE TITLE
Children of 'used in X assertion' terms

### ISSUE THREAD

**Issue by beckyjackson** [evidenceontology/evidenceontology#213]
We have a few 'used in X assertion' terms that have children. Typically, the 'used in X assertion' term for a class should not have any children, but there are a few special cases:

* imported information used in automatic assertion (ECO:0000313)
* evidence based on computational logical inference used in automatic assertion (ECO:0000363)

We should take a look at these and see if they make sense in the context of how we typically build our 'used in X assertion' terms.

**Comment by mgiglio99** [comment]
The 'imported information...' term is being handled in issue #239

**Comment by mgiglio99** [comment]
The ECO:0000363 issue is #240

**Comment by mgiglio99** [comment]
Closing this since these are handled in other issues.
