### ISSUE TITLE
NTR: siRNA knockdown

### ISSUE THREAD

**Issue by MABeebe** [evidenceontology/evidenceontology#215]
Name: siRNA knockdown
Definition: technique used to disrupt expression of a gene through the use of siRNA.
Parent Term: ECO:0000018 (anti-sense experiment evidence)
PMID:     25544610
Will also require a "used in manual assertion" term
@jimhu-tamu
@sandyl27

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

Hoping to discuss the following proposal at the next ECO meeting.

James

**NTR: small interfering RNA knockdown evidence**
**child of:** anti-sense experiment evidence
**def:** A type of anti-sense experiment evidence where gene expression is disrupted through the introduction of double-stranded RNA molecules, 20-25 base pairs in length, which operate within the RNA interference pathway.
**dbxref:** PMID:25544610
**exact synonym:** siRNA
**exact synonym:** short interfering RNA
**exact synonym:** silencing RNA

**NTR: small interfering RNA knockdown evidence used in automatic assertion**
**def:** A type of small interfering RNA knockdown evidence that is used in an automatic assertion.
**NTR: small interfering RNA knockdown evidence used in manual assertion**
**def:** A type of small interfering RNA knockdown evidence that is used in a manual assertion.

**Comment by jbmunro** [comment]
Hi @MABeebe, @jimhu-tamu, and @sandyl27,

New terms added and committed to GitHub.  Closing this ticket.

James
