### ISSUE TITLE
ECO:0006095 not IGI?

### ISSUE THREAD

**Issue by tberardini** [evidenceontology/evidenceontology#216]
This is the total IGI list in 
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

ECO:0006093	IGI	
ECO:0006094	IGI	
ECO:0006096	IGI	
ECO:0006097	IGI	
ECO:0000316 IGI Default

Please add (back?) 

[Term]
id: ECO:0006095
name: double mutant phenotypic evidence used in manual assertion
def: "A type of double mutant phenotypic evidence that is used in a manual assertion." [ECO:RCT]
synonym: "double mutant phenotype evidence used in manual assertion" EXACT []
synonym: "IGI: double mutant analysis" BROAD []
is_a: ECO:0000054 ! double mutant phenotypic evidence
is_a: ECO:0000315 {is_inferred="true"} ! mutant phenotype evidence used in manual assertion
intersection_of: ECO:0000054 ! double mutant phenotypic evidence
intersection_of: used_in ECO:0000218 ! manual assertion
relationship: used_in ECO:0000218 ! manual assertion
created_by: rctauber
creation_date: 2017-09-14T09:19:40

Thanks.

@lreiser

**Comment by rctauber** [comment]
Hi @tberardini - thanks for bringing this to our attention.

We discussed this today, and we are going to put in a temporary fix for this issue now. The `gaf-eco-mapping-derived.txt` file is automatically generated with a SPARQL query, and it assigns the codes based on the parentage.

Currently, `ECO:0006095` is assigned to `IMP`, as it is a child of 'mutant phenotype evidence'. We understand that this is causing a bug in your front-end, so we are adding a line to the code to manually update `ECO:0006095` to `IGI`.

We plan to discuss this in further detail, as we do not want to introduce dual-mappings for these classes, but we want to make sure that nothing in your pipelines break.

**Comment by tberardini** [comment]
@rctauber  Thanks very much for the update. We'll keep an eye out for the new file so that we can update the mapping in our front end.  We think that ECO:0006095 should be a child of ECO:0000316 (genetic interaction evidence used in manual assertion).

**Comment by mgiglio99** [comment]
We'll deal with continued mapping tasks in other issues. Closing this one. Please reopen if needed.
