### ISSUE TITLE
review of 'inference from experimental data evidence' (ECO:0005611)

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#217]
Hi @gthayman 

As part of  ongoing curation of ECO, we are reviewing a number of terms, one of which is the RGD-requested term 'inference from experimental data evidence' (ECO:0005611).  Currently, this term is a child of 'direct assay evidence used in manual assertion' (ECO:000031).

Here is the definition for ECO:0005611:
"A type of direct assay evidence used in manual assertion where phenotype or disease association is made with the gene because of involvement in the molecular mechanism of disease or involvement in a pathway known to contribute to a disease."
There was also a comment in the original ticket for this term that talked about inferring a gene was part of a disease process when a treatment for the disease affected the gene's expression.
We feel that this definition indicates a situation where a curator draws a logical conclusion based upon transitive association of experimental results.  (gene A is in pathway Y, pathway Y is involved in disease X therefore gene A is associated with disease X.)
As such, this term should not be a child of 'direct assay evidence', rather we think it would be better placed as a child of 'combinatorial experimental and curator inference evidence' (ECO:0007012).

In addition, we feel the term label doesn't completely reflect what is in the definition and it is too similar to 'experimental evidence' ECO:0000006.
We suggest: 'curator inference from transitivity of experimental evidence'

Finally, we have some concerns about the definition in that it refers to phenotype and disease, but such associations could be made for other assertions as well. We'd prefer to make the definition more general and then put some specific examples in comments.

Before making any of these changes we wanted to reach out to you and make sure this is consistent with your meaning and use of the term.

Links to: https://github.com/evidenceontology/evidenceontology/issues/85

**Comment by gthayman** [comment]
Hi @mgiglio99 
We recently switched from using disease-specific evidence codes IED and IPM to IDA and IMP, respectively, so the first two can be obsoleted. I understand your concern about a transitive association. I myself don't make disease annotations based on a gene's involvement in a pathway, and after consulting with fellow curators, we think the definition phrase "or involvement in a pathway known to contribute to a disease" is inappropriate and can be removed, hopefully resolving the transitive association issue.

**Comment by mgiglio99** [comment]
Thanks @gthayman
We will go ahead and and obsolete those two terms.

**Comment by nsuvarnaiari** [comment]
This term and its assertion terms have been deprecated.
ECO:0005611 - inference from experimental data evidence
ECO:0007293 - inference from experimental data evidence used in automatic assertion
ECO:0007189 - inference from experimental data evidence used in manual assertion

Thanks,
Suvvi
