### ISSUE TITLE
NTR: Secretion assay evidence

### ISSUE THREAD

**Issue by apowell37** [evidenceontology/evidenceontology#219]
secretion assay evidence in which secreted factors from cells are used to determine presence of a constituent

proposed parent term: ECO:0000181 - in vitro assay evidence

example of use: PMID:23357388

**Comment by apowell37** [comment]
@sandyl27
@jimhu-tamu

**Comment by pgaudet** [comment]
I may have mentioned before - I don't know what is the intended use of this term, but to annotate wit GO terms it's not very informative - we end up with statements like 'GO:secretion ECO: secretion assay'. 

Just wanted to point that out. 

Thanks, Pascale

**Comment by mgiglio99** [comment]
@apowell37 
The definition suggested seems kind of circular. Could you give an example of what you are trying to annotate - and maybe a paper?
This might help to deal with Pascale's concern as well. Maybe we can make something more precise.

**Comment by jbmunro** [comment]
Hi @apowell37, @sandy127, and @jimhu-tamu,

Following up to see where things stand with the suggestions made by @mgiglio99's and wondering what I can do to help.

James

**Comment by sandyl27** [comment]
Sorry for the late reply but I think ECO:0000040 will work

**Comment by jbmunro** [comment]
Hi @apowell37, @sandy127, and @jimhu-tamu,

No problem.  Glad that worked for you.  Closing the ticket but feel free to re-open it if need be.

James
