### ISSUE TITLE
Is there a way to find a list of systems, data collections, ontologies that make use of ECO evidence codes?

### ISSUE THREAD

**Issue by realmarcin** [evidenceontology/evidenceontology#223]
Is there a way to find a list of ontologies that incorporate ECO evidence codes?
I know GO and HPO use it, but looking for a list and ideally a way to generate by search perhaps?

many thanks,
marcin

**Comment by ivanerill** [comment]
Hi @realmarcin ,

[CollecTF](http://www.collectf.org/) is not an ontology, but it does use ECO.

**Comment by realmarcin** [comment]
Thanks, adding it the list.

And I've edited my initial question to include any system or data collection that uses ECO.

**Comment by ivanerill** [comment]
Hi @realmarcin ,

Don't know if you have it in already (it's a GO annotation resource), but [GONUTS/CACAO](https://gowiki.tamu.edu/wiki/index.php/Category:CACAO) switched this year from GO evidence codes to ECO.

**Comment by mgiglio99** [comment]
Hi @realmarcin  - there is a list of ECO users on our web page here:
http://evidenceontology.org/about_us/#usergroups
However, this list is outdated and we are in the process of updating it.
May I ask what you are collecting this info for?
Michelle

**Comment by mgiglio99** [comment]
Closing this for now. Please watch for updates to the website.
Let us know if you have any other questions.
