### ISSUE TITLE
New Term Request: ECO term for gene/gene product identification via database search

### ISSUE THREAD

**Issue by stephengoralski** [evidenceontology/evidenceontology#225]
>"These genes encode proteins of several different classes **according to the Welcome Trust Sanger Institute S. coelicolor genome database** [37]: 72 of the genes are involved in metabolism of small molecules, including seven playing a role in electron transport (e.g. SLI0755-SLI0754, cydAB operons) (Table 1);  _8 encode proteins involved in secondary metabolism, for example the cchA-cchF gene cluster (SLI0459-0454) involved in coelichelin biosynthesis_ [43] and the SLI0339-0359 cluster encoding the putative deoxysugar synthase/glycosyltransferase."

As far as the UMBC team and I are aware, there does not currently exist an ECO term which captures the sort of evidence being used above, a condition by which a researcher uses a biological database to identify the function of a protein. I petition that a term should be made to capture this sort of evidence, as databases are becoming a more pertinent form of evidence for researchers. This term could fit into the ontology as a child of similarity evidence, and could further be broken down into protein and DNA databases if there was a need for it.

**Comment by jbmunro** [comment]
Hi @stephengoralski and @ivanerill,

Thanks for the NTR.  I am looking into it.

James

**Comment by jbmunro** [comment]
Hi @stephengoralski and @ivanerill,

We discussed your NTR and have a concern.  As the above reads, it seems like one has a set of gene ids, they look those up in a database, and find the annotations on those genes.  As such, no new assertion is made - rather, existing assertions are being accessed.  Is this a correct interpretation of the above?  If so, if no new assertion is made, rather, a gene is simply looked up in a database, we feel that there is no evidence.

James

**Comment by ivanerill** [comment]
Hi @jbmunro,

I guess it depends on how you interpret it. Yes, the authors are looking up a gene in a DB, and then pulling whatever annotation is there and asserting that X is the function of the gene. They will typically be collating that information with other evidence threads, so the way I see it the DB lookup can be a form of evidence.

Let's assume that the authors have predicted transmembrane helices using a published algorithm, then they look up the gene in a domain database and see it contains a kinase domain, and they use both sources to assert that the protein is a sensory kinase. The DB lookup is in this context a crucial source of evidence.

More generally, looking up a DB by index search or by BLASTing if conceptually equivalent (DB lookups). The author eventually determines that query and DB accession are a match and asserts that the function/process... of the DB sequence applies to the query. That is, a DB lookup, if vetted by the author and used to make an assertion constitutes a source of evidence (in much the same way that a bibliographical search and interpretation of previous results about a gene function does [ECO:0000033]).

Ivan

**Comment by mgiglio99** [comment]
Hi @ivanerill 
The example that Stephen posted originally sounded like going to a genome database  ("S. coelicolor genome database") and looking up what that database  had recorded as the functions of the proteins of interest. 
What you described was very different. You talked of an author combining transmembrane predictions that the author did with domain predictions that someone else did and arriving at a new annotation. In that case the evidence would be the  two prediction methods. One could use 'computational evidence' or 'combinatorial computational evidence', or the separate evidence types of 'transmembrane prediction evidence' plus a term to capture the kinase domain prediction (not sure which ECO term to use - there are a couple might apply). I think we have terms to cover what you said in the second paragraph.
I didn't totally follow what you're saying in the third paragraph. The only way blasting and looking up an existing entity in a database would be equivalent is if you get a 100% match. Is that what you mean?

**Comment by pgaudet** [comment]
In most (all?) cases the database cites evidence; shouldn't that primary evidence be used ?

**Comment by ivanerill** [comment]
@pgaudet 	
>In most (all?) cases the database cites evidence; shouldn't that primary evidence be used ?

You could, as a curator, but the question is whether to consider it evidence if the author does not cite the primary evidence.

@jbmunro 
>One could use 'computational evidence' or 'combinatorial computational evidence', or the separate evidence types of 'transmembrane prediction evidence' plus a term to capture the kinase domain prediction (not sure which ECO term to use - there are a couple might apply). I think we have terms to cover what you said in the second paragraph.

I was under the impression that this was not the intent of 'computational evidence' [ECO:0007672](https://www.ebi.ac.uk/QuickGO/term/ECO:0007672) and its derivatives? Is the computer 'generating' the data when you do a DB lookup?

>I didn't totally follow what you're saying in the third paragraph. The only way blasting and looking up an existing entity in a database would be equivalent is if you get a 100% match. Is that what you mean?

In most use cases, BLAST is used to query a DB. You can also query a DB with inexact word searches (say you look for 'tyrosine kinase inhibitor' in _E. coli_, you get a couple of partial match results and decide that one of them is a match for whatever protein you are looking at. You make that call and then assert that the annotated function is the function of your protein. To me, that is formally equivalent to making a call based on a BLAST search. Then again, we may be tilting at windmills here, but we found a couple of examples where the authors clearly leveraged the DB info to make a point.

**Comment by mgiglio99** [comment]
Hi @ivanerill 
When I suggested the computational-related terms, that was because your example talked about the author running their own transmembrane predictions plus looking something up in a domain database which presumably used some algorithm to find the domains. I was thinking that you would site the type of evidence the domain db used - such as 'sequence model evidence' or 'sequence similarity evidence' . 
This example can't just be db lookup since the transmembrane analysis was run. So at minimum it is a combination of db lookup and new analysis.

> In most use cases, BLAST is used to query a DB.
This is not how I think of blast searches being used as evidence - certainly they can and are used in this way to look things up, but I don't call that evidence.
If you look up the annotation of a protein in UniProt either by blasting or keyword search you are accessing assertions that someone else, or some algorithm, has made. If you use them that feels more like referencing other people's work like you would any other piece of information you get from someone else.

Could you give a ref to an example paper for this? Might help me to see what your are needing to capture.

**Comment by jbmunro** [comment]
Hi @ivanerill 

Checking in to see where we stand on this.  Would it be possible to reference an example or two?

Thanks.

James

**Comment by ivanerill** [comment]
@mgiglio99 you are probably right in that you are leveraging previous assertions. This came up during a review session of the ECO annotation team, based on the example Stephen posted. So I am fine with this not being proper evidence.

**Comment by jbmunro** [comment]
Closing the ticket.
James
