### ISSUE TITLE
Changed format for ECO creation date

### ISSUE THREAD

**Issue by doughowe** [evidenceontology/evidenceontology#227]
Hi ECO'ers,
Two items.
1.  Our ontology parser is choking when trying to load ECO into ZFIN.  It appears related to the format of the date.  The error we are getting is below.  Was the date format changed on purpose, or will it be changing back to what it used to be?

[java] 5531 - ERROR: Error while parsing Obo file
 [java] Error: Badly formatted creation date: 2017-09-14T09:19:19
 [java] on line: 10251 of file:/opt/zfin/www_homes/zfin.org/server_apps/data_transfer/LoadOntology/obo-files/eco-ontology.obo
 [java] charnum: 14
 [java] line: creation_date: 2017-09-14T09:19:19

2.  ZFIN is now using ECO if you want to add us to your list of ECO users.

**Comment by rctauber** [comment]
Thanks for reporting this! I will take a look at the dates and fix this so it loads properly.

**Comment by rctauber** [comment]
So our standard creation date is in this format: `yyyy-mm-ddThh:mm:ssZ`. It looks like some of the creation dates are missing a `Z` at the end. I added the `Z` back to these terms and made a new release. Please let me know if this solves the problem for you.

**Comment by mgiglio99** [comment]
Hi Doug,
That's great news for us that you are using ECO now! We will happily add you to our users list.
Thanks so much,
Michelle

**Comment by doughowe** [comment]
Here is a higher resolution ZFIN logo you can use if desired.  Feel free to scale it or change formats, but use the complete logo as provided.

Thanks!
Doug
![zfinlogo_1200dpi](https://user-images.githubusercontent.com/7142077/57788734-77749800-76ec-11e9-98fa-90031f43545f.png)

**Comment by mgiglio99** [comment]
Perfect, thanks Doug!

@nsuvarnaiari - send this logo to Dustin for use on the page. Thanks

**Comment by doughowe** [comment]
It looks like your changes haven't solved our problem.  It looks like maybe there is a long dash in some of the creation_date lines between the month and the day?  Here are some examples:

[Term]
id: ECO:0007000
name: high throughput mutant phenotypic evidence
def: "A type of high throughput evidence derived from high throughput analysis of differences in alleles of a corresponding gene." [GO:IMP]
synonym: "high throughput mutant phenotype evidence" EXACT []
is_a: ECO:0000015 ! mutant phenotype evidence
is_a: ECO:0006055 ! high throughput evidence
property_value: IAO:0000234 "GOC" xsd:string
created_by: rctauber
creation_date: 2017-10–05T07:39:47Z

[Term]
id: ECO:0007001
name: high throughput mutant phenotypic evidence used in manual assertion
def: "A type of high throughput mutant phenotypic evidence that is used in a manual assertion." [GO:IMP]
comment: When using the HMP evidence code, the guidelines for IMP should be adhered to (http://geneontology.org/page/imp-inferred-mutant-phenotype)
synonym: "high throughput mutant phenotype evidence used in manual assertion" EXACT []
synonym: "HMP" EXACT [GOECO:HMP]
synonym: "inferred from high throughput mutant phenotype" EXACT [GOECO:HMP]
xref: GOECO:HMP "inferred from high throughput mutant phenotype"
is_a: ECO:0000315 {is_inferred="true"} ! mutant phenotype evidence used in manual assertion
is_a: ECO:0006056 {is_inferred="true"} ! high throughput evidence used in manual assertion
is_a: ECO:0007000 ! high throughput mutant phenotypic evidence
intersection_of: ECO:0007000 ! high throughput mutant phenotypic evidence
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: IAO:0000234 "GOC" xsd:string
created_by: rctauber
creation_date: 2017-10–05T07:39:47Z

[Term]
id: ECO:0007002
name: high throughput genetic interaction phenotypic evidence
def: "A type of high throughput evidence resulting from the high throughput analysis of the effect that a given gene has on another gene or genes, and products." [PMID:11822023]
synonym: "high throughput genetic interaction evidence" EXACT []
is_a: ECO:0000011 ! genetic interaction evidence
is_a: ECO:0006055 ! high throughput evidence
property_value: IAO:0000234 "GOC" xsd:string
created_by: rctauber
creation_date: 2017-10–05T07:39:47Z

**Comment by doughowe** [comment]
...or maybe it's a short dash between the year and the month...I'm not sure which is correct.

**Comment by rctauber** [comment]
I changed the dashes in our edit file. Which release file are you using? I will push a new version of that file for you to try out before making a release.

**Comment by doughowe** [comment]
It looks like we fetch the obo file from here:
https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.obo

**Comment by doughowe** [comment]
Hey!  I just looked at your profile...are you in Bend, Oregon?  I love it there.  I'm in Eugene.  We go to Bend multiple times a year to mountain bike!  Got stuck in Bend in the last major snow storm a few months back.

**Comment by rctauber** [comment]
Thanks! I just pushed a new version of `eco.obo`. When you get a chance, please let me know if that loads properly. Sorry for all the back and forth here.

Yes, I live in Bend OR! That was a bad snow storm... we were stuck inside for a few days 🙂

**Comment by doughowe** [comment]
One problem gone I think...new issue found.  Our loader is choking on this term:

[Term]
id: Subset
is_a: IAO:0000102 ! data about an ontology part

It is reporting "[java] Term with id Subset has no name attribute"

Is that normal to have a term with no name attribute?

**Comment by rctauber** [comment]
That's very strange. I'll look into that. In the mean time, would `eco-basic` work for your purposes? It wouldn't include that term: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco-basic.obo

**Comment by rctauber** [comment]
I have just released a new `eco.obo` that does not include that incorrect term. Please reopen if you have any other problems with this. Thanks!

**Comment by doughowe** [comment]
Problem solved!  Thanks!
