### ISSUE TITLE
NTR: enhancer activity similarity evidence

### ISSUE THREAD

**Issue by ANiknejad** [evidenceontology/evidenceontology#228]
Hello,

Based on the definition for ECO_0000075 (gene expression similarity evidence), we would propose a new term to capture evidence based on enhancer activity similarity, please see this recent paper:
https://www.biorxiv.org/content/biorxiv/early/2019/05/09/633651.full.pdf
"Early origin and deep conservation of enhancers in animals"

Proposed name: enhancer activity similarity evidence
Definition: A type of phenotypic similarity evidence that is based on the categorization of DNA enhancer sequences by the similarity of functional activity.

Thank you in advance and best regards,

Anne

Anne Niknejad
Bgee curator
(bgee.org)

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Thanks for the NTR.  I will get to work on it and keep you updated.

James

**Comment by jbmunro** [comment]
Hi @ANiknejad,

I have a favor - would you please point me to where in the paper you wish to use this proposed NTR?  Line number or the sentence pasted in the discussion work equally as well.  

Thanks,

James

**Comment by ANiknejad** [comment]
I am sorry, James, I am afraid I was a bit too much enthusiastic about homology of enhancers, and currently at least there is no specific annotation we could link to this new ECO term, I mean, from our Bgee side, no homology of anatomical structures (UBERON classes) to link to this potentially new ECO term. But anyway, such sentences as here below are very promising:
"We validated the eISL enhancer activity of predicted human and mouse sequences in zebrafish and showed both candidate enhancer homologues were able to direct GFP reporter expression in a similar manner to their sponge enhancer counterpart. To assess homology of functional activity between mammal and sponge enhancers, we made stable fish lines for the human and mouse ISL enhancers"

"Sponge enhancers can direct similar cell-type specific expression patterns compared to mammalian sequences, thus these appear to be deeply conserved homologous enhancers."

Thank you again for your patience, James, and for opening my eyes.

Anne

**Comment by jbmunro** [comment]
Hi @ANiknejad,

Apologies for not getting back to you sooner.  

We discussed your paper and request and decided that what appears to be the actual type of evidence that is being used - regardless of the conclusion being drawn - is gene expression.  The sentences you subsequently provided above reaffirm this. 

OK - I will close the ticket.  Please feel free to re-open it if need be and post new issues as needed.

Best.

James
