### ISSUE TITLE
Inference from background scientific knowledge about apoptosis used in manual assertion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#23]
```
Hi Marcus,

I don't think I ever requested the new ECO term for using GO:IC with apoptosis 
terms.
Here is the information.

It should be a child of ECO:0000306 inference from background scientific 
knowledge used in manual assertion

Name: inference from background scientific knowledge about apoptosis used in 
manual assertion

Def: A type of inference from background scientific knowledge about apoptotic 
processes that is used in a manual assertion.

xref: GO_REF:0000057 "Gene Ontology annotations inferred by curators' judgment 
using experimental data and prior knowledge of apoptotic mechanisms."

The evidence type should have the restriction that it may only be used with 
apoptotic process terms (in GO these are terms under GO:0006915).

Thanks,
Rachael.

```

Original issue reported on code.google.com by `rachhunt...@hotmail.com` on 5 Jul 2013 at 10:23

**Comment by paolaroncaglia** [comment]
Hi Marcus,

I’d support the addition of the specific ECO code above. I wouldn’t worry too much about setting a precedent for “inference from background scientific knowledge about [process x] used in manual assertion”. The rationale behind asking for that particular code was one we came across while working on a specific ontology development and curation effort (exactly the apoptosis one). Often a paper will describe the ‘stimulus’ that causes apoptosis, but will not specify whether the apoptotic route undertaken is intrinsic or extrinsic. In at least some (if not most) of those cases, curators can use their judgment (their knowledge of apoptosis, a point we were trying to make during the annotation effort, which was completed long ago) to tell. See the apoptosis curation manual here http://wiki.geneontology.org/index.php/Apoptosis_Curation_Manual#Extrinsic_and_intrinsic_apoptosis.
So, there might be similar requests in the future but they’d have to be related to a specific curation effort, one where collective knowledge is gained and shared about a specific branch of the ontology. In all other cases, curators would use the parent code ECO:0000306 inference from background scientific 
knowledge used in manual assertion.

Thanks,

Paola

**Comment by srengel** [comment]
this is an odd and unusually specific code.  Paola says don't worry about setting a precedent, but i specifically worry about setting a precedent.  this is an 'instance', something that we really try to avoid in ontologies.  

i would hesitate on adding this, and really consider the possibility of unintended downstream consequences.

stacia

**Comment by mchibucos** [comment]
@srengel I agree with you and I am very uncomfortable adding specific terms that are "about [process/thing/concept/whatever]" for the reason you mention. The suggested term 'inference from background scientific knowledge about apoptosis used in manual assertion' might be intended as a one off for this particular application, but I can easily see other curators then wanting to request other such terms about whatever they study. It seems far to broad to me. I can imagine a curator wanting a term 'inference from background scientific knowledge **about glycolysis** used in manual assertion' and so forth ad infinitum. But my concerns are deeper than that. I also worry about this issue not just for the "inference" types of terms, but more broadly when it concerns specifying the target of any evidence term used in an annotation. For example, if we followed the suggested pattern, we could just as easily start creating subclasses of 'physical interaction evidence used in manual assertion' such as 'physical interaction evidence **about cytokinesis** used in manual assertion' or things like that. I am afraid that I just don't think that coding such information into ECO is the answer, @paolaroncaglia.

**Comment by paolaroncaglia** [comment]
Thanks for your feedback @srengel and @mchibucos . Fine then, let's not have that ECO code; I suspect that few curators would remember about it anyway, now that the apoptosis curation effort has long been completed. Though you may wish to inform @rachhuntley of this resolution too, as she requested that ECO code originally. Thanks.

**Comment by rachhuntley** [comment]
Fine by me, I can barely remember this and we obviously haven't had a need for it yet!
