### ISSUE TITLE
'random mutagenesis evidence' vs. 'induced mutation evidence'

### ISSUE THREAD

**Issue by jbmunro** [evidenceontology/evidenceontology#234]
This issue stems from #174.

Hi @ivanerill and @pgaudet,

In reviewing the 'experimental phenotypic evidence' branch I have questions about a two similar terms that I am hoping you might be able to answer.  The terms are 'random mutagenesis evidence' and 'induced mutation evidence'.  

**'random mutagenesis evidence':**
A type of experimental phenotypic evidence where radiation or a DNA-damaging agent in vivo, or PCR with degenerate primers in vitro, are used for non-targeted mutagenesis.

**'induced mutation evidence':**
A type of genetic transformation evidence resulting from a mutation induced by a mutagenic compounds or irradiation.

Are these terms really meant to be distinct?  

- Both terms imply or state an intentional attempt to cause/induce mutations.  Is this a correct assumption?

- 'random mutagenesis evidence' implies that the position of the mutation within the genome is random (as opposed to specifically targeting a region), while 'induced mutation evidence' does not state whether the mutations are random or targeted.  Is there supposed to be a difference?

- As a child of 'genetic transformation evidence', 'induced mutation evidence' inherits from the parent definition "...resulting from the conversion of one genotype into another by the introduction of exogenous DNA.", i.e. in addition to a mutagenic compound or radiation, exogenous DNA is involved.  
-- Is 'induced mutation evidence' supposed to imply the introduction of exogenous DNA?
 Is this the original intent of the term that DNA originating from outside the organism is introduced?
-- If not, shouldn't this term be a child of 'mutant phenotype evidence'?

- Is there perhaps a better term for 'random mutagenesis evidence'?
To me it sounds very much like "random mutation" which conveys the idea that the mutations (point mutation, nonsynonymous mutation, etc.) occur at any random position in the genome and that such mutations are not intentional or "guided" - mutations occur "naturally". As noted above, 'random mutagenesis evidence' seems to intentionally induce mutations.

- Should 'random mutagenesis evidence' be moved from 'experimental phenotypic evidence' to 'mutant phenotype evidence'?  Currently there is no mention of observing the phenotypic expression of a mutation but am I correct in assuming that this was the intent? 

Thanks.

James

**Comment by pgaudet** [comment]
Hi James, 

I think the two terms are indeed the same. I would merge. 

> Should 'random mutagenesis evidence' be moved from 'experimental phenotypic evidence' to 'mutant phenotype evidence'? Currently there is no mention of observing the phenotypic expression of a mutation but am I correct in assuming that this was the intent?

Yes I think so. I wanted to add more structure to the terms we had requested a few years back, but we never got to it. 

Thanks, Pascale

**Comment by ivanerill** [comment]
Hi @jbmunro ,

I would probably opt to keep them separate, but with a re-write. 

I agree that given its inheritance from "genetic transformation evidence" ECO:0005027, the current wording of "induced mutation evidence" ECO:0001056 does not make a lot of sense. But there are techniques wherein researchers _do_ introduce exogenous DNA to induce mutations, such as [transposon mutagenesis](https://en.wikipedia.org/wiki/Transposon_mutagenesis) and the derived [Transposon sequencing (Tn-seq)](https://en.wikipedia.org/wiki/Transposon_sequencing). These techniques, beyond causing knockouts, often incorporate markers or reporters, so they are bona fide "genetic transformation". I believe ECO:0005027 should capture these. Alternatively, you can merge the two existing terms as proposed (for compatibility with existing annotations) and add a new branch for the transposon mutagenesis-like terms.

I would also split 'random mutagenesis evidence' ECO:0005529 to differentiate between _in vivo_ (e.g. radiation) and _in vitro_ (e.g. PCR) protocols. Several reasons for this. The _in vitro_ protocol requires that the mutated fragment be cloned back into the target organism. It also targets a specific DNA fragment, so it is not "random" in the same sense than irradiating a cell and hitting _any_ segment of DNA.

Cheers,

Ivan

**Comment by pgaudet** [comment]
Right, I was thinking that after I wrote the comment. I think random mutagenesis is done by PCR, with an inbalanced pool of nucleotides. The definition is confusing, we should remove ' radiation or a DNA-damaging agent in vivo'. 

Thanks, Pascale

**Comment by jbmunro** [comment]
Hi @pgaudet and @ivanerill 

Thank you both for the advice!  I'll get to work on this and touch base with everyone.

James

**Comment by jbmunro** [comment]
Hi @ivanerill and @pgaudet 

Here is an update from our discussions.  Your thoughts and suggestions are welcome.

James

**Obsolete term: induced mutation evidence**
This term will be made obsolete for a couple of reasons: the def doesn’t make sense as the suggested means of mutagenesis fail to introduce exogenous DNA (it is a child of genetic transformation evidence) and the def. is too much like random mutagenesis evidence.
 
**Update term: random mutagenesis evidence -> random mutagenesis phenotypic evidence**
**old def.:** A type of experimental phenotypic evidence where radiation or a DNA-damaging agent in vivo, or PCR with degenerate primers in vitro, are used for non-targeted mutagenesis.
**new def.:** A type of mutant phenotype evidence where a mutagenic product or process is used to alter the nucleotide sequence and thus induce genetic mutation.  Examples include, but are not limited to mutagenic compounds, irradiation, PCR w/ degenerate primers, etc.
narrow syn.: random mutagenesis evidence
 
**New term: random mutagenesis of specific target DNA evidence**
**new def.:** A type of random mutagenesis evidence resulting from the random mutation of a specifically targeted region of DNA.

Ivan’s point about transposon sequencing and especially transposon mutagenesis, sparked a lot of discussion: it can be random or site-specific, it is indeed a type of ‘genetic transformation evidence’ as exogenous DNA is introduced, yet a second (inferred) parent could be ‘random mutagenesis evidence’ or ‘random mutagenesis of specific target DNA evidence’, etc.  However, after much deliberation, we decided that transposon mutagenesis and Tn-seq are more of a protocol/technique and the actual type of evidence - that upon which an assertion is based - can vary greatly. (Additionally, we are striving to focus on evidence rather than protocol.)
 
For now, we have decided not to add any transposon-related terms and to address this issue in the future should a request for such terms arise.

**Comment by ivanerill** [comment]
Sounds good to me.

**Comment by pgaudet** [comment]
Sounds good to me too, thanks !

**Comment by jbmunro** [comment]
Thank you!

Proposed changes made and pushed to GitHub.  Closing this ticket.

James
