### ISSUE TITLE
NTR: Bulk Culture Assay Evidence

### ISSUE THREAD

**Issue by jason-snow58** [evidenceontology/evidenceontology#238]
* Term Name: Bulk culture assay evidence 
* Definition 1: Bulk culture assay evidence is a cell-based assay evidence that can be used to measure populations of cells
* Definition 2: Measurement of a population of cells
* Parent Term:  Cell-based assay evidence ECO:0001565
* References: PMID:30135120, 15862883

We also have an accompanying NTR that is a child of the above term. 

* Term Name: Optical density measurement of bulk culture assay
* Synonym(s): lysis curve
* Definition1: optical density measurement of bulk culture assay uses optical density measurements at various wavelengths to monitor cell culture growth
* Parent term: Bulk culture assay evidence 
* Reference: PMID:30135120

**Comment by jbmunro** [comment]
Hi @jason-snow58, 

Thanks for the NTRs.  I will get on this a.s.a.p.  May I ask what organization or ontology you work for so that I might add it to our "ontology requester" field?

More later...

James

**Comment by jason-snow58** [comment]
This is for the CACAO course at Texas A&M University.

**Comment by jbmunro** [comment]
Thanks @jason-snow58.

James

**Comment by ivanerill** [comment]
Hi @jason-snow58 ,

How would this be different from [ECO:0001563](https://www.ebi.ac.uk/QuickGO/term/ECO:0001563) (cell growth assay evidence)? And/or how would it relate to it?

Ivan

**Comment by jrr-cpt** [comment]
Pulling in @jimhu-tamu @cross12tamu

@ivanerill in this case we are measuring only the cells that are present, not whether they have grown. Importantly for spec measurements, we aren't always measuring growth, sometimes it is shape change. And for our lysis assays that use the spec, it is the loss of population.

Right now @jason-snow58 is suggesting it be under Cell-based assay evidence [ECO:0001565](https://www.ebi.ac.uk/QuickGO/term/ECO:0001565), which put it on the same level as cell growth assay.

**Comment by jbmunro** [comment]
Hi everyone,

I am working on some ideas to discuss with the ECO team at our next meeting but in the meantime, I would like some clarification with the NTRs.  

First, I would like to point out that where possible, we are trying to get away from 1) catch-all parent terms and 2) generating new terms that differ from established terms on the basis of the protocol used but not the type of evidence and 3) generating single child parents.  So, with that said...

Right now, I am not understanding how the NTR 'bulk cell culture assay evidence' differs from the established term 'cell-based assay evidence' and why it is needed as a parent to the NTR 'optical density measurement of bulk culture assay'.  Couldn't the NTR 'optical density measurement of bulk culture assay' be appropriately placed as a child of 'cell-based assay evidence'?

I am also trying to understand the need for the NTR 'optical density measurement of bulk culture assay'.  The provided definition states that cell growth is what is measured and used as evidence.  Ivan pointed out that 'cell growth assay evidence' would be appropriate, and I agree.  Yet it is then pointed out that "... we aren't always measuring growth, sometimes it is shape change. And for our lysis assays that use the spec, it is the loss of population."  If that is the case, then wouldn't an NTR that addresses cell/colony shape or morphology be more appropriate and if the evidence is the loss of cells in a population, then wouldn't one of the established terms 'cell proliferation assay evidence' or 'cell counting evidence' be appropriate?

Thanks for your patience,

James

**Comment by jimhu-tamu** [comment]
I'm not entirely sure I understand all aspects of the NTR, but...

Cell growth assay evidence runs into the problem with growth terms in GO. Cell growth is technically the increase in size and mass of individual cells, not a change in number. As an aside, changes in size and mass can be shrinkage as well as growth, which I think is not reflected in this term (ECO:0001563) and its relatives.

The problem with proposing to use shape or cell number is that optical density measurements of cell cultures (which are actually better described as light scattering measurements) are not directly measuring those properties. If the OD decreases after induction of a lysis protein the experimenter infers that this is due to lysis and a decrease in cell number rather than a shape change. But the OD change per se doesn't tell us that. We bring additional knowledge to the process of making the inference.

**Comment by ivanerill** [comment]
Hi @jimhu-tamu ,
So I take it that the right thing to do here (which would catch the existing [ECO:0001563](https://www.ebi.ac.uk/QuickGO/term/ECO:0001563) as well as these new terms), would be to rename  ECO:0001563 as "optical density assay", and then derive as needed?
Ivan

**Comment by jimhu-tamu** [comment]
@ivanerill, and modify the definition? But then it's a new term.

**Comment by jason-snow58** [comment]
Also that term would need to specify what is being measured with OD. Things like DNA and protein purity can also be measured using OD.

I have revised the NTR for 'Optical density measurement of bulk culture assay':

Change to term name: Optical density of cell culture assay evidence
Definition: Optical density of cell culture assay evidence uses optical density measurements at various wavelengths to monitor changes in a population of cells. 

This can fall under ECO:0001563 ‘cell-based assay evidence’, however we still need a term to capture the use of OD measurements of cell cultures because this is a standard laboratory procedure that is not represented by any current ECO term. This term cannot fall under:

- Cell growth/cell proliferation - because OD, along with cell growth, can also be used to monitor cell death, changes in cell shape, cellular production of light scattering components, etc.

- Cell counting assay - because you cannot directly count cells using OD measurements, you can only approximate.

**Comment by mgiglio99** [comment]
We agree that the term you want does not fit well into any existing terms under 'cell-based assay'. We feel that that the OD measurements you describe are measuring something about the populations of cells but cannot discriminate exactly what is being measured. So we suggest the following new term which will be a child of 'cell-based assay evidence':

'cell population optical density evidence'
definition: A type of cell-based assay evidence in which optical density is used to measure some aspect of a population of cells. Examples of aspects that can effect optical density measurements include, but are not limited to, cell number and cell shape.

Please let us know your thoughts.

**Comment by mgiglio99** [comment]
@jimhu-tamu @jason-snow58 
Hi, have you had a chance to look at this suggestion?
Thanks,
Michelle

**Comment by jrr-cpt** [comment]
The suggestion for 'cell population optical density evidence' would be suitable for the annotations that @jason-snow58 would like to capture for the @jimhu-tamu CACAO class.

**Comment by jbmunro** [comment]
NTR added and pushed.  It will be available with the next release.

Closing this ticket.
