### ISSUE TITLE
Fix cardinality restriction axioms

### ISSUE THREAD

**Issue by beckyjackson** [evidenceontology/evidenceontology#243]
The 'has part' object property is currently used in some axioms containing min/max restrictions. 

This should not be done because it is a "non-simple" property. 'has part' is transitive so it is not a simple property, and OWL 2 does not allow non-simple properties in cardinality restrictions (`min` and `max`). I apologize that I didn't catch this earlier.

If we create a child property of 'has part' specifically for talking about evidence parts, we do not need to make it a transitive property, but that means this new 'has evidence part' should only be used for combinatorial evidence (because it is *not* transitive). I think that would be accurate.

The current `make test` methods use the ELK reasoner, which is a very simple reasoner and doesn't catch problems like this. I will switch the reasoner to HermiT, which will catch these sorts of issues.

**Comment by beckyjackson** [comment]
For transitive properties:
human 'has part' brain and brain 'has part' brain cell, therefore it can be inferred that human 'has part' brain cell.

This is how I understand it:
If you say that `human SubClassOf ('has part' max 1 brain)` then a human can *only* have part one brain - a human **cannot** have part "brain cell", even if you say that the `brain SubClassOf ('has part' some 'brain cell')`. That is why OWL 2 does not allow cardinality restrictions on non-simple properties; they are part of property chains.

**Comment by mgiglio99** [comment]
Not sure I'm totally following this. Let's chat about it during Wednesday's meeting.

**Comment by beckyjackson** [comment]
Instead of creating this new property, we will change all cardinality restrictions to `some`.

**Comment by beckyjackson** [comment]
Resolve by 47569d4
