### ISSUE TITLE
Should 'curator inference' always be manual?

### ISSUE THREAD

**Issue by beckyjackson** [evidenceontology/evidenceontology#244]
It seems to make sense that curator inference should always be used in a manual assertion.

We currently have many "automatic assertion" classes under curator inference. Does this make sense in any situation? If not, we should deprecate these classes. 

That would only leave "manual assertion" classes. Could we merge the "manual assertion" classes and the raw evidence types? Will that cause issues for users, particular GO curators? Currently, "curator inference used in manual assertion" is equivalent to IC. The ID for this term would stay the same, but the parent class would be merged into it and the label would become "curator inference".

The same would happen with all the children terms. This is parallel to the other discussions in #240 and #242. I'd just like to make sure that these changes wouldn't break any downstream applications.

**Comment by ivanerill** [comment]
>It seems to make sense that curator inference should always be used in a manual assertion.
I agree. I can't seem to think of a curator inference resulting in an automatic assertion.

>We currently have many "automatic assertion" classes under curator inference. Does this make sense in any situation? If not, we should deprecate these classes.
The could easily be obsoleted.

>That would only leave "manual assertion" classes. Could we merge the "manual assertion" classes and the raw evidence types? 
I would not do that. I don't really see what it accomplishes and I believe it is better to preserve consistency across the ontology.

Ivan

**Comment by beckyjackson** [comment]
> I don't really see what it accomplishes and I believe it is better to preserve consistency across the ontology.

The consistency is a good point. The point of merging manual terms up would be so as not to have classes that only have a single child.

**Comment by ivanerill** [comment]
Right, but conceptually it's a cross-product, so I would keep it that way
for consistency.

**Comment by beckyjackson** [comment]
Seems fine to me. Closing for now.
