### ISSUE TITLE
Missing name tag in OBO file

### ISSUE THREAD

**Issue by cmpich** [evidenceontology/evidenceontology#245]
In the latest obo file the following error is happening:
Term with id GO:1904796 has no name attribute

I am not sure why there are GO terms in this OBO file.

[Term]
id: GO:1904796
is_a: GO:0050789 {is_inferred="true"}

[Term]
id: GO:1904797
is_a: GO:0048519 {is_inferred="true"}

[Term]
id: GO:1904798
is_a: GO:0048518 {is_inferred="true"}

**Comment by beckyjackson** [comment]
Thanks so much for finding this. Since we run the reasoner on ECO before converting to OBO, it looks like there was some logic in the GO import that caused these terms to be reasoned and their parents asserted. These terms should not appear in the OBO file and I have removed them.

I just published a new release, `v2020-01-07`, that resolves this.

**Comment by cmpich** [comment]
Does this term stanza look right?

`[Term]
id: ECO:0000006
name: experimental evidence
alt_id: ECO:0005023
def: "A type of evidence resulting from manipulation of variables in order to discover cause and effect." [url:http\://holah.co.uk/page/experimental/]
subset: go_groupings
is_a: ECO:0000000 ! evidence
is_a: IAO:0000030 {is_inferred="true"}`

The IAO reference makes our OBO parser choke.

**Comment by beckyjackson** [comment]
This looks correct because we've integrated OBI in. So due to logical definitions, there may be new inferences to external terms. I think it makes more sense to take all external references out of the OBO file, though. I'll work on this.

**Comment by beckyjackson** [comment]
Can you take a look at this file and see if it works with your parser? Thanks!
https://github.com/evidenceontology/evidenceontology/blob/rc2020-01-08/eco.obo

**Comment by cmpich** [comment]
Worked just fine!

**Comment by beckyjackson** [comment]
Great! I've published this file as the release file. Thank you for your help.
