### ISSUE TITLE
Question about format of some synonyms that use GO three-letter codes

### ISSUE THREAD

**Issue by vanaukenk** [evidenceontology/evidenceontology#247]
Hi,

The GO Consortium uses the full set of ECO terms in the Noctua annotation tool.

We've come across an interesting issue, though, with how the autocomplete works for ECO terms that refer to the GO three-letter codes.  

In nearly all cases, curators can enter the three-letter GO code and the autocomplete (which returns ten possible results) will contain the correct ECO term in the results, e.g. IMP -> ECO:0000315.

The exception, however, is IDA.  When a curator types in 'IDA', ECO:0000314 is not returned in the top-ten list.  We think this may be a signal-to-noise issue in that a number of ECO:0000314 child terms contain broad synonyms that preface a text string with 'IDA:'.  For example:
    IDA: enzyme assay for ECO:0005801

We are wondering if there is a known use for this synonym format and if not, would it be possible to remove the three-letter GO prefix for any broad synonyms that have this format?  

This type of synonym does not appear to be universally applied to all relevant child terms for the ECO parent terms that correspond to GO codes, so I wasn't sure if the existing subset was chosen for a specific reason.

Please let us know.  Thx.

**Comment by nsuvarnaiari** [comment]
Hi @vanaukenk 

Thanks for letting us know. We will look into it and update you soon.

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Thanks @nsuvarnaiari 

Feel free to get in touch if you guys would like to discuss anything in person.

**Comment by nsuvarnaiari** [comment]
Hi @vanaukenk ,

We removed the three letter GO code prefixes from synonyms in our eco-edit.owl version. These changes will be visible in the release files after our Feb release this Friday (Feb 7th).

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Thank you @nsuvarnaiari !

**Comment by kltm** [comment]
Thank you so much @nsuvarnaiari !
