### ISSUE TITLE
Add missing field and docs gaf-eco-mapping-derived.txt

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#249]
A while ago I worked with Marcus on this https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt

This provides a mapping from a GAF code + GO_REF to an ECO class

There is a PURL for this, so that people can use a PURL rather than a github URL http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

all good

at some point some groups started needing a derived version of this so they didn't have to walk to the ECO graph

Here:
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

This essentially has materialized inferences

However, it lacks a GO_REF. It also lacks documentation at the start of the file

Can these be added? The docs should state exactly what the file is an how it's derived

I also recommend the PURL is advertised in the header:

http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt

cc @kltm

**Comment by mgiglio99** [comment]
Hi Chris
Thanks for alerting us to this. We'll work on getting it fixed.
Michelle

**Comment by cmungall** [comment]
Can you also add a link to this in the wiki page?

**Comment by cmungall** [comment]
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt resolves to HTML, it needs to resolve to the raw github URL

```
$ curl -L -s https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt | head






<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
```

**Comment by mgiglio99** [comment]
@nsuvarnaiari 
Hi Suvvi - let's review this one to see if there is anything else to do - I think it can be closed.
Michelle

**Comment by nsuvarnaiari** [comment]
All the issues have been resolved.
1)PURL has been added in the header of http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt file. The header also contains details on how the file is generated. 
2)The file does not have mappings to GO:REFs (mapping from a GAF code + GO_REF to an ECO class is in https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt). 
3) The PURLs to 'gaf-eco-mapping.txt' and 'gaf-eco-mapping-derived.txt' have been added to wiki page (https://github.com/evidenceontology/evidenceontology/wiki/Gene-Ontology-GafEcoMapping)
