### ISSUE TITLE
comments in gaf-eco-mapping-derived.txt

### ISSUE THREAD

**Issue by ukemi** [evidenceontology/evidenceontology#252]
The comments added to the above file is causing our loads to fail. Is there any way to remove them until we can update our code to accommodate for them?

**Comment by beckyjackson** [comment]
Sure, these were added for #249 but I will remove them for the moment. I'm going to keep this issue open until we can add them back in.

Thanks for your patience!

**Comment by loricorbani** [comment]
The new "comments" looks like this:

# a child of ECO:0000353 'physical interaction evidence used in manual assertion', which is
$ equivalent to IPI
#

with both "#" and "$" appearing in the first column.
Is this the format?  
Do we have to check for both?

Thanks.

**Comment by loricorbani** [comment]
sorry...my paste doesn't look correct:

# xxxxx
$ equivalent to IPI
# xxxxx

**Comment by loricorbani** [comment]
ok...the file is using both "#" and "$" to signify "comments".  
need to know if this is correct format.
so we can ignore on our end.
thanks.

**Comment by beckyjackson** [comment]
It should just be `#`, my apologies.

**Comment by loricorbani** [comment]
can we have a TEST file so we can test our fix?

**Comment by loricorbani** [comment]
ok, we saved the last file and were able to test with our change to ignore comments.  you can put your comments back in.  we are checking "#" and "$",  just in case.
thanks.

**Comment by beckyjackson** [comment]
Thanks so much! I will update this now.

**Comment by beckyjackson** [comment]
OK, comments are back in, only using `#`. Please let me know if you have any other problems. Thanks again for your patience.

**Comment by cmungall** [comment]
I think this can be closed?
