### ISSUE TITLE
Minimum Inhibitory Concentration measured with epsilometer 

### ISSUE THREAD

**Issue by Gabrporter** [evidenceontology/evidenceontology#253]

**Comment by Gabrporter** [comment]
I need a new term added to ECO.

**Comment by mgiglio99** [comment]
Hello @Gabrporter 
Apologies for the delay in responding to your request.
To help us understand better what you are trying to capture with this new term, please provide the following information:
1. Where in the ontology do you see the new term being placed?
2. What is the definition you propose for the new term?

Thanks,
Michelle

**Comment by mgiglio99** [comment]
We will close this issue since there has been no reply. Please reopen if you want to discuss this further.
