### ISSUE TITLE
ECO terms and GO synonyms - EXACT vs RELATED

### ISSUE THREAD

**Issue by vanaukenk** [evidenceontology/evidenceontology#255]
Hi,

I'm getting ready to import full ECO into WormBase, but have a quick question about synonym types and the GO three-letter codes.

Looking at the latest ECO release (2020-05-01), it looks like most of the three-letter GO codes are listed as EXACT synonyms for the corresponding ECO term, however IDA and IMP are listed as RELATED synonyms.

Can someone remind me of why that is?  I was checking this so I can give the WB web developers instructions on what to display in our GO annotation table.

Here's the breakdown:

EXACT synonym:
IGI
IGC
RCA
ISA
ISM
ISO
IEA
EXP
IEP
NAS
TAS
IC
ND
IBA
IBD
IKR
IRD
IPI
HEP
HGI
HTP
HMP
HDA

RELATED synonym:
IDA
IMP

Thanks!

**Comment by vanaukenk** [comment]
Here are the IDA and IGI entries for comparison:

[Term]
id: ECO:0000314
name: direct assay evidence used in manual assertion
def: "A type of direct assay evidence that is used in a manual assertion." [ECO:MCC]
subset: valid_with_chemical_entity
synonym: "IDA" RELATED [GOECO:IDA]
synonym: "inferred from direct assay" EXACT [GOECO:IDA]
xref: GOECO:IDA "inferred from direct assay"
is_a: ECO:0000002 ! direct assay evidence
is_a: ECO:0000269 {is_inferred="true"} ! experimental evidence used in manual assertion
intersection_of: ECO:0000002 ! direct assay evidence
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: seeAlso http://geneontology.org/page/ida-inferred-direct-assay xsd:string
created_by: mchibucos
creation_date: 2011-10-28T04:59:31Z


[Term]
id: ECO:0000316
name: genetic interaction evidence used in manual assertion
def: "A type of genetic interaction experiment evidence that is used in a manual assertion." [ECO:MCC]
subset: valid_with_gene
subset: valid_with_protein
subset: valid_with_protein_complex
synonym: "IGI" EXACT [GOECO:IGI]
synonym: "inferred from genetic interaction" EXACT [GOECO:IGI]
xref: GOECO:IGI "inferred from genetic interaction"
is_a: ECO:0000011 ! genetic interaction evidence
is_a: ECO:0007634 {is_inferred="true"} ! experimental phenotypic evidence used in manual assertion
intersection_of: ECO:0000011 ! genetic interaction evidence
intersection_of: used_in ECO:0000218 ! manual assertion
property_value: seeAlso http://geneontology.org/page/igi-inferred-genetic-interaction xsd:string
created_by: mchibucos
creation_date: 2011-10-28T05:14:42Z

**Comment by nsuvarnaiari** [comment]
Hi Kimberly,

Thanks for bringing it to our notice. We have changed both IMP and IDA to be the "EXACT" synonyms of the ECO terms. I made a release just now with these changes reflecting in the files.

Closing the ticket now but reopen if needed. 

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Thank you @nsuvarnaiari 
I wasn't sure if there might be a reason for this, but thanks for making all the GO entries consistent.
