### ISSUE TITLE
children of 'author statement' ECO:0000204

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#256]
Def of 'author statement supported by traceable reference' is not consistent with that term's children.

**Comment by ivanerill** [comment]
In what sense? a published clinical study would be a traceable statement, wouldn't it?

**Comment by mgiglio99** [comment]
Getting back to this late. 
In looking it over more I think that the child does fit based on the defnition, but the name is a little ambiguous -  it just could use some def and name revisions. 

**ECO:0006016**
**name**
-current name: 'author statement from published clinical study'
-new name: 'author statement supported from referenced clinical study'
**definition**
-current def: "A type of traceable author statement that is based on a publication about a clinical study."
-new def: "A type of author statement supported by traceable reference in which the traceable reference is a clinical study."

Thoughts?
@ivanerill @nsuvarnaiari

**Comment by nsuvarnaiari** [comment]
Revised label and definition for 'ECO:0006016' have been pushed in April release.

name
-current name: 'author statement from published clinical study'
-new name: 'author statement supported from referenced clinical study'
definition
-current def: "A type of traceable author statement that is based on a publication about a clinical study."
-new def: "A type of author statement supported by traceable reference in which the traceable reference is a clinical study."

The labels and definitions for manual and automatic assertion terms have also been updated.
