### ISSUE TITLE
quantitative   immunoblotting

### ISSUE THREAD

**Issue by ValWood** [evidenceontology/evidenceontology#257]
I was looking for a term for 

quantitative   immunoblotting

and found
protein expression level evidence based on western blot used in manual assertion
Go to external page http://purl.obolibrary.org/obo/ECO_0007183  Copy
Search ECO
Search
A type of protein expression level evidence based on western blot that is used in a manual assertion. [ http://www.evidenceontology.org/browse/#ECO_RCT ]

is this the term I need, and if so would 
quantitative   immunoblotting be a better name? The name and definition sound almost identical

**Comment by mgiglio99** [comment]
Hi Val,
I think that ECO:0007183 could work for you. Although, I'm thinking that 'quantitative immunoblot'  might actually be a more specific child of ECO:0007183 since not all western blotting is quantitative. 
I agree that the names of these terms are a little cumbersome. And could possibly be revised.

What are your thoughts on whether you want a new more specific child for the quantitative term?

Michelle

**Comment by ValWood** [comment]
Oh yes of course it is more specific,  I think a descendant.

**Comment by mgiglio99** [comment]
Hi Val,
In looking at the terms around the above term a bit more, I realize that there is more work to be done in this region of the tree for this all to make sense. How quickly do you need this term?
Michelle

**Comment by ValWood** [comment]
Not quickly. Nothing is ever needed quickly... In your own time ;)

**Comment by mgiglio99** [comment]
Thank you!  :)

**Comment by mgiglio99** [comment]
Hi Val - sorry it took so long to get back to this. There are a lot of things that disturb me about the terms in this node, but I don't have to address all of those to get you the term you want.
Here is my proposal:
We are thinking of merging 'protein expression level evidence based on western blot' into its parent 'western blot evidence'. (As currently I don't see how they are different.) This would result in a term that is for 'qualitative western blot' which would encompass all types of western blot.
For your term, we were then thinking we'd make a child of 'qualitative western blot' that would be 'quantitative western blot'.
Does this sound ok?

**Comment by ValWood** [comment]
Yes,  that sounds good. I  can't remember which paper I needed it for  (why didn't I include the PMID?!)
but I'm sure it will come back to me!

**Comment by mgiglio99** [comment]
Ok good - (sorry again for the huge delay making you forget what annotation this was for)

I've actually decided to merge three terms together.
Plan:
-merge ECO:0005602 'protein expression level evidence based on western blot'
and ECO:0000112 'western blot evidence'
into ECO:0000333 'sodium dodecyl sulfate polyacrylamide gel electrophoresis evidence'
change name of merged term to: 'qualitative western immunoblotting evidence'
with synonyms of all three old names.
New definition: "A type of protein expression evidence where proteins are separated using gel electrophoresis, blotted onto a membrane, and probed with an antibody that can be detected via light or radioactive emission."
reference: https://pubmed.ncbi.nlm.nih.gov/23050259/
Add parent 'protein expression level evidence' to the merged term.
 
Likewise merge the automatic/manual assertion children of each of these into each other:
merge ECO:0000112 and ECO:0007287 into ECO:0007770
merge ECO:0000279 and ECO:0007183 into ECO:0007689

New term: 'quantitative western blot'
child of ECO:0000333 (the newly merged term from above)
def: "A type of qualitative western blot evidence where detection of the signal is carried out through digital imaging and the signal is normalized with methods such as standard curves built from reference housekeeping proteins or total transferred protein measurements."
reference: https://pubmed.ncbi.nlm.nih.gov/25852189/
child terms: make automatic and manual assertion children for this.

@ValWood  - do these definitions look ok?

**Comment by ValWood** [comment]
This sounds good to me. I'm not  great with  evidence codes so also copying in @mah11 who may need to know about the proposed  for historical  HTP curation reasons.

No worries about the timeframe, I know how it is. I sometimes return to tickets on my todo list after years 👍 
totally my fault for not recording my PMID here!

**Comment by ValWood** [comment]
Note to self PMID:26527280 courtesy of Midori

**Comment by mgiglio99** [comment]
Revised plan: we are going to leave ECO:0000333 'sodium dodecyl sulfate polyacrylamide gel electrophoresis evidence' alone for now and just do the merge of the two western terms. Everything else stays as planned.

**Comment by nsuvarnaiari** [comment]
Hi @ValWood 

As per the revised plan, the following changes have been made.

1. Changed the label of ECO:0000112 'western blot evidence' to "qualitative western immunoblotting evidence".
2. Merged ECO:0005602 'protein expression level evidence based on western blot' into "qualitative western immunoblotting evidence" (ECO:0000112).
3. Merged the automatic/manual assertion children of 'protein expression level evidence based on western blot' into 
automatic/manual assertion children of "qualitative western immunoblotting evidence".
         Merged ECO:0007183 into ECO:0000279
         Merged ECO:0007287 into ECO:0007306
4. Created a new child term "quantitative western immunoblotting evidence" (ECO:0006169) under "qualitative western immunoblotting evidence".
 Children under this:
quantitative western immunoblotting evidence used in automatic assertion (ECO:0006171)
quantitative western immunoblotting evidence used in manual evidence (ECO:0006170)
5. Added one more parent 'protein expression evidence' (ECO:0000010) to "qualitative western immunoblotting evidence".

Closing the ticket now but reopen if needed.
Thanks,
Suvvi
