### ISSUE TITLE
Code for N/A (not applicable)

### ISSUE THREAD

**Issue by marcadella** [evidenceontology/evidenceontology#259]
I am looking for a code meaning "Not applicable" (N/A). It would be loosely related to [ECO:0000035](https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000035) as they both qualify an empty attribute value. The code would mean: "After evaluation, this attribute was left empty because no value logically fits."

If there is none, could it be added in a later version?

**Comment by mgiglio99** [comment]
Hello,
Thanks for suggesting this new term for ECO.
In order to help me better understand what you need, could you provide an example of a situation where you would wish to assign this new term?
Thanks,
Michelle

**Comment by tkl014** [comment]
Hi,
I think the use of 'no biological data found (ECO:0000035)' is limited for cases where the target data do not relate directly to any biological entity. This can occur if no data on physical tools, methods or programs are to be listed by a curator. Thus, a wider options within this scope would be welcome.
Best,
Terje

**Comment by marcadella** [comment]
> I think the use of 'no biological data found (ECO:0000035)' is limited for cases where the target data do not relate directly to any biological entity.

@tkl014 I created a separate [issue](https://github.com/evidenceontology/evidenceontology/issues/260) regarding this remark.

Going back to "not applicable", as a curator, in some cases I would like to leave an attribute blank, not because the data is missing (ECO:0000035), but because the context (i.e. value taken by other attributes) is such that no data applies to that field.
For instance assuming a record containing those fields:
```
host_state: [alive|dead]
age_at_death_time: [date]
```
If the sample is alive, then I would like to tag `age_at_death_time` as "not applicable". I do not want to write in the field `N/A` though because the field expects a date with a specific format and `N/A` would not fit in there.

**Comment by mgiglio99** [comment]
Hello @marcadella 

We are trying to figure out if such a term as this is within the scope of ECO. It is not a type of evidence. However, it is possible that we could capture it as a type of assertion.
In looking around at other ontologies, we did find 'not applicable' terms in two ontologies: 
GENEPIO http://purl.obolibrary.org/obo/GENEPIO_0001619
NCIT http://purl.obolibrary.org/obo/NCIT_C48660

In addition, we are wondering if it should be part of IAO (Information Artifact Ontology). Maybe as a 'datum quality' or something like that under the 'information content entity' node - http://purl.obolibrary.org/obo/IAO_0000030

Tagging @cmungall for his input on this.
Chris, what do you think?

**Comment by mgiglio99** [comment]
@marcadella
Apologies for not returning to touch base on this issue sooner.
In reviewing this some more, we don't feel that 'not applicable' fits within the scope of ECO. We encourage you to explore IAO as a possible source for something you can use.
Regards,
Michelle

**Comment by ms-966** [comment]
host_state: [alive|dead]
age_at_death_time: [date]
