### ISSUE TITLE
ECO_0000035 should be generic and not tied to a specific domain

### ISSUE THREAD

**Issue by marcadella** [evidenceontology/evidenceontology#260]
As a curator I would like to be able to use ECO_0000035 to tag attributes where no information could be found despite research. The problem is that ECO_0000035 is tied to "biological data" for some reason.
Would it be possible to remove "biological" from the definition so that it could be applied to any domain?

**Comment by mgiglio99** [comment]
Thanks for alerting us to this. We agree that there is no reason to restrict this.

We will rename the term to 'no evidence data found'.

And reword the definition as follows:
"A curator inference that results when research finds no evidence information in the scientific literature, at reference databases, or from other resources."

Does this sound ok?

**Comment by nsuvarnaiari** [comment]
Hi @marcadella 

The label for ECO:0000035  has been changed from "no biological data found"  to "no evidence data found".
The new definition is "An inference that results when research finds no evidence information in the scientific literature, at reference databases, or from other resources."

Thanks,
Suvvi
