### ISSUE TITLE
ECO id with GO annotations, but no mapping to GO evidence codes

### ISSUE THREAD

**Issue by alexsign** [evidenceontology/evidenceontology#262]
Here is the list I have in GOA/Protein2GO:
ECO:0005544
ECO:0005610
ECO:0005543
ECO:0005547
ECO:0005546

**Comment by nsuvarnaiari** [comment]
Hi @alexsign ,

Thanks for providing us the list. We will take a look and try to map to a GO evidence code soon.

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
Hi @alexsign 
All of these terms are together in the 'biological system reconstruction' node of ECO. We feel that the only GO evidence code that these can be mapped to is IC - inferred by curator.
Does that sound ok to you?

@pgaudet - does this sound ok to you?

**Comment by alexsign** [comment]
@mgiglio99 @pgaudet I think it's up to curators to make a decision.

**Comment by pgaudet** [comment]
@alexsign Can you get the list of annotations/sources using those evidence codes ?

**Comment by alexsign** [comment]
@pgaudet shhh... it's a secret, you have to use QuickGO for this. 
https://www.ebi.ac.uk/QuickGO/annotations?evidenceCode=ECO:0005546,ECO:0005547,ECO:0005543,ECO:0005610,ECO:0005544&evidenceCodeUsage=descendants

**Comment by pgaudet** [comment]
;) sorry I should have known, thanks !

**Comment by pgaudet** [comment]
Those are all assigned by ComplexPortal. @bmeldal  can you help us map this to a 3-letter GO evidence code ?

**Comment by bmeldal** [comment]
None of these have specific GO 3-letter codes as they were created separately for CP. They are children of `ECO:0000088 biological system reconstruction evidence`, which has a synonym `ISR` in OLS. I don't know if that is a GO code.

And yes, they are effectively "like IC" but there is a separate GO/ECO branch for IC (`ECO:0000305 curator inference used in manual assertion`).

But looking at ECO:0000305 I guess all of the children of ECO:0000088 that are "...evidence used in manual assertion" can/should also be children of ECO:0000305. At the moment they are siblings with the common parent `ECO:0000352 evidence used in manual assertion`.

Curiously, there is also `ECO:0007746 biological system reconstruction evidence used in manual assertion` which is not a parent of the above list but should be. This latter term has no children...

@mgiglio99 shall I open a ticket in the ECO tracker so we can fix the missing relationships?

**Comment by pgaudet** [comment]
Can you explain what experiments you are curating ? Are those experiments where all subunits of a complex are added together in vitro ?

**Comment by mgiglio99** [comment]
@bmeldal Thanks for the heads up on the relationships, I will add this to another ticket that I made for reviewing the placement of this node in ECO - https://github.com/evidenceontology/evidenceontology/issues/264

**Comment by bmeldal** [comment]
> Can you explain what experiments you are curating ? Are those experiments where all subunits of a complex are added together in vitro ?

Apologies for the delay.

ECO:0005547:
We use this code when there isn't a single experiment available to show that a complex exists or what its function is.

E.g. 
- Composition: 5 subunits are identified by gel filtration while a crystal has been purified using 3 of those SUs and an extra one. There might also be a cell-extract pull-down that includes all but additional ones that might be FPs. So, we have to "stitch these together".

- Composition: there is no clear IPI but the specialist community always assumes the complex is made up of X SUs. There might be IDA/IPI evidence from lower organisms but for mammals there are only functional ko expts that don't tell us exactly what in the complex. e.g. some acetylcholine receptors.

- Function: only the catalytic subunit has been clearly identified in the functional assay but IPI expts are clearly showing that it always contains x other subunits. These SUs may be present in the functional assay but haven't been purified.

Full complex annotation is a lot of guess-work!

I don't have any nice examples for MF & BP right at hand but I can look for them if you need them.

ECO:0005610 (and children):
Infer by homology. We can't use the ISS code as homology of complexes is by sequence, composition and function. Most commonly used btw mouse and human, but also others.

ECO:0005543:
When the experiment is using a mix of species, e.g. human-mouse heteromer. Happens not infrequently although we try to find an expt using only one species. Probably only used for complex itself, not CC location, MF or BP. (I couldn't find other examples but for component)
e.g. https://www.ebi.ac.uk/complexportal/complex/CPX-702, mixed crystal IPI evidence: https://www.ebi.ac.uk/pdbe/entry/pdb/1wm0

Does that help?

**Comment by vanaukenk** [comment]
I'm getting ready for the next WB GO data upload and in parsing the GOA GPAD file, see that annotations assigned by ComplexPortal don't have a corresponding three-letter code, so we can't bring them into WB to produce a GAF.

The two ECO codes we have in the WB file are ECO:0005547 and ECO:0005546 which, as has been suggested, could map to GO's IC evidence code, although it looks like the parentage for that is not currently present in ECO.

Can we revive this ticket and #264?

@alexsign - In the meantime, since GO still produces, and many tools rely on GAF, do you think we should temporarily suppress outputting GPAD annotations where the ECO code doesn't map to a three-letter code?

In the short term, I've removed the ComplexPortal annotations from the WB upload, since they will generate errors in our display, production GAF, and automated gene descriptions pipeline.

Let me know if I can help in any other way.

@mgiglio99 @alexsign @pgaudet

**Comment by alexsign** [comment]
@vanaukenk I'm not sure it's a good idea to remove annotations from GPAD based on missing ECO2GO evidence mapping. It's not hard to implement, but we will have to take into account potential non Complex Portal annotations without GO evidence codes as well. For groups which still have GAF centric GO annotations storage will be better to skip the annotation without mappings on import stage.

**Comment by vanaukenk** [comment]
@alexsign Yes, in the end, that's what I did: I'm removing the ComplexPortal annotations from the WB import. Our WB data model can accommodate ECO codes, but we still produce a GAF for GO and it would be nice to include as many annotations as we possibly can.
If we can figure out how to map these ECO codes up to an existing GO code, or perhaps even propose a new three-letter code (!), that might be a reasonable interim solution while we're still living in a GAF-consuming world.

**Comment by mgiglio99** [comment]
Hi all - apologies for totally dropping the ball on this issue. I'm looking through this and trying to get my head in the right space to make an intelligent comment. 
Quick note for now - we can assign GO code mappings independent of the ECO hierarchy.
And let me confirm that you are using the gaf-eco-mapping-derived.txt file to generate mappings - is that correct?

**Comment by mgiglio99** [comment]
We think that IC is the safest mapping for these terms. These terms are challenging because they combine different types of evidence together to infer the presence of a complete system, thus they can't map to any of the more specific codes such as ISS or EXP.
Would everyone be ok with mapping these to IC?
If so, we can make those mappings and push a new release that will produce an updated gaf-eco-mapping-derived.txt file.
Let us know if this sounds good.

**Comment by vanaukenk** [comment]
Thanks @mgiglio99 !
So if we mapped these codes to IC, do we need to do anything with their parentage in ECO, i.e. make them descendants of ECO:0000305?
Or is that already there and I'm not seeing it in OLS?

**Comment by mgiglio99** [comment]
Hi @vanaukenk 
We have changed the way we map GO codes to ECO terms such that the mappings no longer have to be reflected in ECO parentage. (I mentioned this in my presentation at the last GOC meeting.) For various reasons, including GO including multiple types of evidence within one ev code, we felt that the mappings had to be independent of the ECO structure. We now have a field associated with each term called "has GO evidence" where we indicate which GO ev code is the correct mapping for that term. This info is then pulled into the gaf-eco-mapping-derived.txt file when we push releases.
Are you using the gaf-eco-mapping-derived.txt file to get mappings? Or are you traversing the graph yourself for mappings?

**Comment by vanaukenk** [comment]
Thanks @mgiglio99 
These annotations come into WB via UniProt-GOA, so I'll let @alexsign comment on what mapping file he's using.
@pgaudet are you also okay with mapping these ECO codes to IC? Is there anyone else we should check with?

**Comment by mgiglio99** [comment]
We can also add IC as an equivalence mapping to the 'biological system reconstruction evidence used in manual assertion' parent in the gaf-eco-mapping.txt file (as opposed to the derived file) - that will work for anyone doing their own graph traversing. At least I think it will as I understand it.

**Comment by bmeldal** [comment]
Hi everyone, hope you are all ok. I'm still getting notifications and as this was sort of my ticket I'll bud in ;-)

Yes, using the ECO hierarchy independently from the GO 3-letter codes sounds good. But in this case, ECO:0000088 can be a child of IC ECO:0000305 as well. I think it's fine. This whole branch is curator inferred.

But you are also right, it cannot be mapped to ISS as homology in ECO:00005610 and children is more than just by sequence.

**Comment by pgaudet** [comment]
If @bmeldal agrees that IC is correct, that's fine for me. 

WRT to the hierarchy, I think at least in AmiGO we need to be able to follow the hierarchy to group certain evidence to higher level classes such as IEA and EXP. Let's try it like this (maybe after the upcoming GO release, which will hopefully happen this week?) so we can test it ahead of the next release. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Thanks @bmeldal @pgaudet @mgiglio99   I am fine with IC, then, as well.
If we can ultimately get all the desired parentage in the hierarchy, that'd be great.

**Comment by pgaudet** [comment]
> Do I understand that you don't want us to change anything until after the next GO release?

Yes, thank you

**Comment by mgiglio99** [comment]
Ok - we'll hold on this until the new year then (as almost everyone here is taking off starting on Monday).
@vanaukenk will you be able to do the mappings even before we make the change? I hate for that data to be excluded due to lack of mappings.

**Comment by vanaukenk** [comment]
Thanks @mgiglio99 
Our WB data upload was this past Tuesday, so I had to hold off on those annotations for now.
We'll get them in next time!!

**Comment by mgiglio99** [comment]
OK -  apologies for not getting this sorted faster. 
Is next time a long time away?

**Comment by vanaukenk** [comment]
WB is on a three-month build cycle, so our next upload will be in March.
No worries, though.  That should give us plenty of time to have this sorted out, and I appreciate your help!

**Comment by nsuvarnaiari** [comment]
Hi @vanaukenk @pgaudet  @bmeldal  @alexsign @mgiglio99 

Based on the discussion, 'biological system reconstruction' (ECO:0000088) branch has been moved under 'curator inference' (ECO:0000205). I also fixed the issues that @bmeldal mentioned in her comment (Oct 19, 2020) regarding missing relationships.

The following ECO ids now map to 'IC' in gaf-eco-mapping-derived.txt file.
ECO:0005544
ECO:0005610
ECO:0005543
ECO:0005547
ECO:0005546

This is a pic of the the relationships with 'biological system reconstruction' manual assertion terms. Please take a look and let me know if something is not right. (NOTE: 'curator inference used in manual assertion' maps to GO code 'IC')

![Screen Shot 2022-01-04 at 11 13 24 AM](https://user-images.githubusercontent.com/13201743/148090871-4e47725c-2426-4a33-ab79-f793cf5a5d58.png)


Thanks,
Suvvi

**Comment by vanaukenk** [comment]
Thanks very much @nsuvarnaiari !
This should now give us a GO code translation in a GAF for the annotations that use these ECO ids.

**Comment by sandraorchard** [comment]
Hi

This isn't working because there is now an obligate requirement to fill the with/from column [GORULE:0000016] - the Complex Portal has nothing to put in there.

**Comment by nsuvarnaiari** [comment]
Hi @sandraorchard @kltm @pgaudet @vanaukenk @suzialeksander

Looks like ECO:0005547 (mapping to IC) is causing some issues at your end. Please let us know if there is anything we can do to help resolve the issue.

Thanks,
Suvvi

**Comment by pgaudet** [comment]
We would need to find a new parent for ECO:0005547.  GO rules require that there is a with/from information for IC.

**Comment by nsuvarnaiari** [comment]
Hi @pgaudet 

Michelle and I will look into it and get back to you early next week with a workaround.

Thanks,
Suvvi

**Comment by sandraorchard** [comment]
Thank you

**Comment by mgiglio99** [comment]
Hi all,
We moved the whole 'biological system reconstruction ...' branch to be under IC so that Complex Portal annotations would map to a GO code. Now it appears that is causing a problem due to the GO rules for IC. At the time we made the shift to IC for this node, that was the only GO code that seemed appropriate. We can remove that mapping but then Complex Portal will be back to not having a GO code and that will cause issues for WormBase imports. What alternative GO code do you think this branch should have? 

We can try to figure out where to better place this branch or leave it in IC but give it different GO mappings. Recall that ECO now has the ability to give parent and child nodes different GO ev code mappings. And then users should use the gaf-eco-mapping-derived.txt file to get the appropriate GO code for each ECO term. Traversing the ECO hierarchy will not give the correct GO code in these cases. (I know that some people are uncomfortable with that and I need to to schedule a meeting to talk about it but our feeling is that is required for ECO to be internally consistent.)

Michelle

**Comment by pgaudet** [comment]
How about NAS?

**Comment by mgiglio99** [comment]
That seems unsatisfactory because they do have lots of traceable information that is backing up their assertions. Would it be possible to allow a GO_REF in the with/from column for IC such that they could describe their process for biological system reconstruction?

**Comment by vanaukenk** [comment]
Could we possibly make use of experimentally based annotations to individual complex members from the same paper and use those GO ids in the With/From?

I don't know if such experimental annotations exist for all of the papers CPX has annotated using reconstruction-type evidence codes, but something along those lines would be in the spirit of what GO is trying to achieve by populating the With/From field for IC annotations.

If there weren't experimental annotations for the individual members in a single paper, then maybe combining all terms from experimental annotations and a GO_REF is another option.  The list of annotations in the With/From field might then get very long for some genes, though.

We'd need to look at some examples.

**Comment by mgiglio99** [comment]
Would it be possible for GO to expand it's definition of IC such that inferences based on more than just other GO annotations are allowed?

**Comment by pgaudet** [comment]
But then, how can we enforce that IC do have support from another GO anontation?

**Comment by mgiglio99** [comment]
This issue was resolved in issue:
https://github.com/evidenceontology/evidenceontology/issues/289
