### ISSUE TITLE
review placement of 'biological system reconstruction' node

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#264]
'biological system reconstruction' node could be placed under 'similarity evidence'.
Review implications of this.
Also review overlap between 'biological system reconstruction' and 'combinatorial evidence'
Also the 'background knowledge' term under the 'biological system reconstruction' node is very similar to curator inference terms - review overlap.

**Comment by mgiglio99** [comment]
Need to add missing relationships per Birgit's comment in  https://github.com/evidenceontology/evidenceontology/issues/262

**Comment by pgaudet** [comment]
Hi @mgiglio99 This is creating problems in Protein2GO. Could the 'biological system reconstruction' node be moved directly under ECO:0007751 inferential evidence used in manual assertion? 

@vanaukenk
@hattrill

**Comment by mgiglio99** [comment]
This was discussed in other issues:
https://github.com/evidenceontology/evidenceontology/issues/262
https://github.com/evidenceontology/evidenceontology/issues/289
Resolution was to move the 'biological system reconstruction' branch to be a child of 'curator inference'. Specific 'manual' child term mappings to things other than IC were made to avoid the GO rule about requiring a GO term in the with field for IC annotations.
