### ISSUE TITLE
DisProt term requests - batch 1

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#266]
We are working with the Disordered Protein (DisProt) database to enter new terms into ECO to correspond to DisProt's Detection Methods.

**Comment by mgiglio99** [comment]
Dear Michelle and others,

We started working with Federica on the terms that we'll need. We agreed to have regular sessions on Tuesdays when we work on this together, followed by individual work. This ideally means that each week we'll have a bunch of terms we draft, plus a bunch of questions we might have. To be less annoying, we'll aim to collect and send our questions once a week in one go. For now we are focusing on methods that are often used, including CD, X-ray, NMR, cryo EM, SAXS, SANS and FTIR. Below are a couple of technical and conceptual questions related to that - if you could give guidance, we'd be grateful so we don't write up term definitions that do not fit ECO.

Questions (with a more generic description, followed by a condensed actionable question):

1) which methods should be children of structure determination (ECO:0005031)? The definition says "A type of experimental evidence resulting from the visualization and examination of chemical and/or molecular structures", which for me hints at atomic level resolution, such as structure determination by X-ray or EM. However, e.g. dynamic light scattering is also a child term of structure determination, and with that method we only get a lower resolution information on structural properties. Thus, we are unsure if e.g. CD spectroscopy should be a child term of structure determination or not (as it gives information about secondary structure content but in a fairly indirect way). Also, should NMR be under structure determination? Right now it isn't, but the information we derive from NMR experiments are very structural.

    --- specific question: should SAXS, SANS and CD have "structure determination" as ancestor terms in addition to having their respective ancestors where applicable (e.g. spectrometry for CD)?

2) X-ray crystallography (manual assertion) already exists as ECO:0005670. However, we use X-ray structures in two very different ways. We can look at the structure to assess binding events (e.g. we see two proteins interacting) or to assess that an otherwise disordered region can become ordered under certain conditions. However, we often infer disorder based on missing residues (if a segment of a protein was present in the construct but has no coordinates assigned). Hence, X-ray crystallography can give us information based on the presence or the absence of coordinates and it would be important for us to distinguish these two. The same goes for cryo-EM (which we'll define under ECO:0006003, electron microscopy, manual assertion).

    --- specific question: can we define two child terms under X-ray crystallography (ECO:0005670), one for detection of structure via coherent interference pattern and detection of flexibility via lack of coherent interference pattern (or something similar)?

3) we want to define SAXS (small angle X-ray scattering) and SANS (small angle neutron scattering). The setup is similar for the two methods but the radiation used is very different. We think both should go under structure determination (ECO:0005031). Should they have a common ancestor, such as small angle scattering experiments, or should they both have separate ancestors reflecting the different types of radiation?

    --- specific questions: under structure determination, should we A) define "X-ray scattering" and "neutron scattering" and then define SAXS and SANS under these two terms respectively or B) should we define "small angle scattering experiment" under structure determination, with SAXS and SANS both being children of this term?

4) the definition of spectrophotometry, ECO:0001126 is "A type of spectrometry evidence resulting from the evaluation of a molecule in a fluid by its ability to alter the transmission of light at specific wavelengths". Does "light" include infrared too or only visible light? We think this should decide if Fourier transform infrared spectroscopy (FTIR) should go under spectrophotometry (ECO:0001126) or its ancestor spectrometry (ECO:0005504)

    --- specific questions: should the direct ancestor of FTIR be spectrophotometry (ECO:0001126) or spectrometry (ECO:0005504)?

5) we have cases where the conclusion that a protein is disordered comes from the amalgamation of the results of several experiments. This means that the evidence is an inference made by someone interpreting these results. For us there is a fairly important difference if that inference was made by the authors of the paper we're curating (and the inference is e.g. written in the discussion) or if the inference is done by one of our curators. Can this distinction be made under the term inferential evidence (ECO:0000361)? Right now that term has a child "curator inference", ECO:0000205 but does not have author inference

    --- specific questions: can we define "author inference" under "inferential evidence", ECO:0000361 or is that distinction between authors and curators incompatible with ECO?

Thank you very much for your help!

Best,

Balint

**Comment by mgiglio99** [comment]
Hello Federica and Balint

Item number 1:
Everything you mentioned should be a child of 'structure determination evidence' or a child of one of its children. In looking at the definition, we see how it can give the impression that it is meant for the atomic level, however, we don't feel that is the case. We are going to modify the definition to make that more clear.
Proposed new def: "A type of experimental evidence resulting from the use of techniques for the visualization and elucidation of the structure of molecules and macromolecules."
Regarding NMR, we suggest making a new child of the existing 'nuclear magnetic resonance spectroscopy evidence' ECO:0006163 with specificity for NMR based structure determination, that will have as a second parent 'structure determination evidence'.  

[Note to ECO team - decide what parent should be inferred vs asserted.]

Item number 2:
Do you feel that the term describing the ability to become ordered under certain conditions is still a 'structure determination evidence'? I ask to see if we should consider pulling X-ray crystallography out from under 'structure determination evidence'. Assuming that both are still considered structural evidence, which I think they are, then we propose the following:
-Use the existing term for your first case since I feel that is already covered with that term (and we can modify the def to include language about coherent interference patterns if needed)
-Create a new term for 'differential X-ray crystallography evidence' or something along those lines to indicate when you are comparing two different structures and see differences in coordinates that indicate flexibility.
Let us know if we are thinking in the correct direction.

Item number 3:
-We feel the terms should be organized according to radiation rather than angle. Therefore we suggest that 'small angle X-ray scattering evidence' be made a child of 'light scattering assay evidence' since X-rays are a type of EM radiation.  We will not make a parent 'X-ray scattering' term now but if other types of angles are later requested then we can create a grouping term as needed. 
-In looking at this we realize that the def for 'light scattering assay evidence' is a bit too specific and we will broaden to be the following: "A type of direct assay evidence derived from determining the properties of a sample such as size, shape, structure, molecular weight, diffusion and interaction strength by illuminating the sample with a beam of electromagnetic radiation and detecting the scattered intensity at a certain angle."
-A question we have is: should the X-ray scattering term have any relation to X-ray crystallography? 
-The new 'small angle neutron scattering' term would be a direct child of 'structure determination evidence'.

Item number 4:
Yes, infrared is light and we should change that def to say electromagnetic radiation.
New def of 'spectrophotometry evidence' would be: "A type of spectrometry evidence resulting from the evaluation of a molecule in a fluid by its ability to alter the transmission of electromagentic radiation at specific wavelengths."
Therefore, Fourier transform infrared spectroscopy (FTIR)  should go under 'spectrophotometry evidence', ECO:0001126.

Item number 5:
We absolutely agree there should be both curator inference and author inference terms. Currently, 'author inference' is a synonym for 'author statement' ECO:0000204.
In looking at this in light of your question, we are now wondering if we should make a new 'author inference' term as a child of 'author statement' and 'inferential evidence'. Please take a look at the 'author statement' term and let us know what you think.

Thanks,
Michelle and Suvvi


[Note for ECO team: if we do make 'author inference' then we need to change the equivalence axiom for 'combinatorial experimental and author inference evidence', ECO:0007011 - (and we need to revisit this whole node as well) and we need to remove the equivalent synonym of 'author inference' on 'author statement'.]

**Comment by mgiglio99** [comment]
Response from Balint on 1/28:

Hi Michelle,
Thank you for this, this is super helpful. My comments:

Item #1 - perfect, will do that.

Item #2 - We'll keep thinking about this one. Actually I think wrote it in a very confusing way. When we infer order or disorder from structures solved by X-ray crystallography (or cryoEM), we are looking at only one structure. We first identify which is the protein construct that was used in crystallization. Then we compare this sequence to the residues that are visible in the structure (i.e. have atomic coordinates). The residues that have defined coordinates are considered ordered, the ones that were present in the construct that was crystallized but do not have visible coordinates are considered disordered (as they are so flexible that the authors decided that reliable position cannot be determined even using very high B-factors).

Item #3 - this sounds perfect, we agree. "A question we have is: should the X-ray scattering term have any relation to X-ray crystallography?" - I think yes, X-ray crystallography should be a child term of X-ray scattering. Crystallography is more specific by requiring the sample to be in a solid, ordered crystal form upon which the X-ray beam is scattered.

Item #4 - perfect.

Item #5 - Regarding this: "we are now wondering if we should make a new 'author inference' term as a child of 'author statement' and 'inferential evidence'" - there is indeed a difference between inferences and statements so in theory it makes sense to separate them. For me (although English is not my native language so I might be wrong) 'inference' is a conclusion reached by an argument based on observations gained from the experiments. A statement is the verbal formulation of an inference, i.e. putting the conclusion into words. Whenever we read a paper to create annotations from it, we are reading statements that tell us about the inferences the authors made. While the two things are conceptually different, from the end user point of view (in this case the curators' point of view), they are pretty much the same thing. Same goes for curator inference and curator statement - the curator will write a statement into a database that expresses her/his inference. Therefore, for the sake of simplicity I might opt for keeping inference and statement as synonyms, maybe with a slightly modified definition to express that we are aware the conceptual difference between these but choose to merge them for practical reasons. I totally agree that author and curator inference/statements should be separated as it should be traceable who exactly made the inference.

Well get on with writing the new terms and we'll get back to you soon.

Best,
Balint

**Comment by mgiglio99** [comment]
Hi Balint,

Here are some follow-up thoughts from Suvvi and me on items 2 and 5.

For item 2, thanks for the explanation, we think we understand now. We agree that it makes sense to have two terms for these two situations. However, we are having a hard time coming up with suggestions for term names that we feel work well. Here are some suggestions below. Let us know if these are along the lines of what you were thinking? Please feel free to suggest alternatives to these and we can always add synonyms to make things more clear.

new term1 name: 'coherent interference pattern x-ray crystallography evidence'
OR name: 'ordered structure x-ray crystallography evidence'

new term 2 name: 'non-coherent interference pattern x-ray crystallography evidence'
OR name: 'disordered structure x-ray crystallography evidence'
-------------
For item 5, 
We completely agree with you on the meanings of inference vs. statement. For a little background, the 'author statement' terms arose historically from the Gene Ontology evidence codes "non-traceable author statement" and "traceable author statement". These were used by GO curators to describe when an author said something in a paper, such as "protein x is a kinase", but there were no experiments or analysis in the paper to support that claim. If in these cases the authors cited a reference for the statement, then it was "traceable" if they didn't then it was "non-traceable". Current GO annotation practices prohibit the annotation of information that is not traceable, so that one is really a legacy term.
We are struggling with whether we should merge the concepts of inference and statement, as you discussed, and change the curator inference terms to curator statement terms (with appropriate synonyms). We are going to think about that some more. But we do think an author inference term is needed, so we propose a new term called 'author inference statement' that will have both 'inferential evidence' and 'author statement' parents for now. But we will keep thinking about this to sort out the curator inference side of things.

Thanks so much,

Michelle and Suvvi

**Comment by nsuvarnaiari** [comment]
Hi Balint/ Federica,

Batch1 terms are now available in today's ECO release.
Here is the list of 21 new terms in batch1 and their ECO ids,
| ECO IDs     | New Term Label                                                                           |
|-------------|------------------------------------------------------------------------------------------|
| ECO:0006175 | nuclear magnetic resonance spectroscopy-based hydrogen-deuterium exchange evidence       |
| ECO:0006176 | proton-based nuclear magnetic resonance evidence                                         |
| ECO:0006177 | circular dichroism evidence                                                              |
| ECO:0006178 | synchrotron radiation circular dichroism evidence                                        |
| ECO:0006179 | far-UV circular dichroism evidence                                                       |
| ECO:0006180 | near-UV circular dichroism evidence                                                      |
| ECO:0006181 | cryogenic electron microscopy evidence                                                   |
| ECO:0006182 | small-angle X-ray scattering evidence                                                    |
| ECO:0006183 | particle scattering evidence                                                             |
| ECO:0006184 | small-angle neutron scattering evidence                                                  |
| ECO:0006185 | author inference                                                                         |
| ECO:0006186 | combinatorial experimental and author inference evidence contained in single publication |
| ECO:0006187 | X-ray crystollagraphy-based structural model with missing residue coordinates            |
| ECO:0006188 | X-ray crystollagraphy-based structural model with high relative B-factor values          |
| ECO:0006189 | cryogenic electron microscopy-based structural model with missing residue coordinates    |
| ECO:0006190 | cryogenic electron microscopy-based structural model with high relative B-factor values  |
| ECO:0006191 | Fourier-transform infrared spectroscopy evidence                                         |
| ECO:0006192 | heat capacity-based evidence                                                             |
| ECO:0006193 | differential scanning calorimetry evidence                                               |
| ECO:0006194 | selective antibody-based structural conformation evidence                                |
| ECO:0006195 | protein hydrogen-deuterium exchange mass spectrometry evidence                           |
