### ISSUE TITLE
Additional RNAseq support term

### ISSUE THREAD

**Issue by murphyte** [evidenceontology/evidenceontology#267]
I'd like to request a variation of ECO:0000343:
MIXED SUPPORT OF INTRON POSITIONS BY RNA-SEQUENCING ALIGNMENT EVIDENCE

Definition: A type of support of intron position by RNA-seq alignment evidence where RNA-seq alignments from a mixture of samples support all of the intron positions (exon pairs) predicted for a transcript.

Comment: Mixed support entails that all exon pairs represented in the transcript are supported, but require a combination of evidence from multiple samples. For example, for a transcript containing five exons, if liver RNA-seq reads support the first two introns and brain RNA-seq supports the last three introns, then neither sample meets the criteria for full support (ECO:0000343) but the combination of samples qualifies as Mixed support. Mixed support may result from differential expression, or low expression levels that benefit from combining data.

And also for ECO:0000343, I suggest revising the name to say "INTRON POSITIONS" (plural) instead of the current singular, to better convey that the code applies to the set of introns in a transcript.

**Comment by nsuvarnaiari** [comment]
Hi @murphyte 

We'd be happy to take a look at your new term request. Also, thanks for your suggestion regarding the name revision. Will write to you in case need any extra information.

Thanks,
Suvvi

**Comment by murphyte** [comment]
FYI, the original request for ECO:0000343 came from my group, if that's pertinent.

**Comment by nsuvarnaiari** [comment]
Hi @murphyte 

May I ask which organization you work for, just to fill "ontology_term_requester" field for the new term you requested.

Thanks,
Suvvi

**Comment by murphyte** [comment]
NCBI (RefSeq group)

**Comment by nsuvarnaiari** [comment]
Hi @murphyte 

The new term is now available in today's release of ECO. I also made the name revisions. Let me know if something is incorrect.

Thanks for your request. Closing the ticket.

Suvvi
