### ISSUE TITLE
synonym requests

### ISSUE THREAD

**Issue by tberardini** [evidenceontology/evidenceontology#268]
https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000295&viewMode=All&siblings=false

Add synonym: RNAseq evidence

https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000009&viewMode=All&siblings=false

Add synonym: transcriptomics evidence

**Comment by nsuvarnaiari** [comment]
Hi @tberardini 

The synonyms look good. You should see them in the next release which is tomorrow.

Thanks,
Suvvi

**Comment by tberardini** [comment]
Thanks, Suvvi.  Will look for the updates on Monday.

@lreiser FYI

**Comment by nsuvarnaiari** [comment]
Hi @tberardini 

The synonyms are now in today's release of ECO. 

Thanks for your request. Closing the ticket.
Suvvi

**Comment by tberardini** [comment]
Hi Suvvi,

Additonal request, since I didn't realize I also needed to do this:


[Term]
id: ECO:0000291
name: transcript expression evidence used in manual assertion
**synonym: transcriptomics evidence used in manual assertion**

[Term]
id: ECO:0006068
name: RNA-sequencing evidence used in manual assertion
**synonym: RNAseq evidence used in manual assertion**

Please edit as you see fit.  I need to have the 'manual assertion' ones retrieved when I search for 'RNAseq' or 'transcriptomics'.

Thanks again.

**Comment by nsuvarnaiari** [comment]
Hi Tanya,

Sorry, should have remembered to add other synonyms too. Anyways, they have been added and an emergency release was done. Please let me know if something is not right.

Thanks,
Suvvi

**Comment by tberardini** [comment]
Yay! Thanks for pushing an emergency release. We've incorporated the changes into our tool using our regular update protocol.  Really appreciate your help.

Tanya
