### ISSUE TITLE
"polyadenylated transcript evidence" term request

### ISSUE THREAD

**Issue by murphyte** [evidenceontology/evidenceontology#274]
I'd like to request a new ECO code for "polyadenylated transcript evidence", as a child of "transcript expression evidence" ECO:0000009

Definition: A type of transcript expression evidence based on sequencing of the 3' ends of cDNA molecules that are selected by presence of a polyadenylated tail.

There are many references. PMID: 31617559 is a recent paper for a resource that consolidates data from many sources, so you could use that or use something like PMID: 5288383 (1971) if you want to use one of the earliest references.

Thanks!

-Terence Murphy
terence.murphy@nih.gov
NCBI RefSeq

**Comment by nsuvarnaiari** [comment]
Hi @murphyte 

Thanks for suggesting this term. We will look into it soon.

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
Hi @murphyte 
This term looks good but we have a suggestion for a revision to the name. We'd like it to include sequencing in there somewhere to make it as specific as the definition. Would 'polyadenylated transcript 3' end sequence evidence' be ok with you?

**Comment by murphyte** [comment]
Thanks - I appreciate your timing since we're in the processing of coding this markup now!

I'd like to think 3' end is synonymous with polyadenylated transcript, since biologically there is no mechanism that can polyadenylate the 5' end of a transcript. It can happen as a library prep artifact, but that shouldn't be called "polyadenylated". I do see a few other existing terms with apostrophes, so if you think the added specificity is needed, it's fine with me.

Note for recording ECO codes in data (e.g. an INSDC flatfile), I like to have a human-readable text string and the machine-parseable ECO code. In that context, I generally find the ECO names to be too long, and wind up using something shorter and less specific. Here we're planning to use:
polyA evidence [ECO:TBD]

If you could provide the ECO code for this child when you have it, that would be super-helpful to finalize our code:
polyadenylated transcript 3' end sequence evidence used in automatic assertion

I think it can take a could of weeks before they show up on the web, and I'm hoping to push the code to production by then. 

Thanks!

**Comment by mgiglio99** [comment]
@murphyte 
I meant the "3' sequence" as a modifier to be capturing the location of where the sequence is being generated from, not a modifier of "polyadenylated transcript" - to indicate that this is sequencing of just the 3' ends.

As we look at this one some more we think using the word "sequencing" will make this more clear.
New suggested label:  'polyadenylated transcript 3'-end-sequencing evidence'
Would be child of ECO:0000295 'RNA-sequencing evidence'  (which is a child of 'transcript expression evidence' ECO:0000009)

Does this seem ok?

**Comment by murphyte** [comment]
yep, that all sounds great. thanks!

**Comment by nsuvarnaiari** [comment]
Hi @murphyte 

Your new term is now publicly available in the latest ECO release.

Name: polyadenylated transcript 3-end-sequencing evidence
ECO Id: ECO:0006239
Parent ECO id: ECO:0000295 (RNA-sequencing evidence)

Closing the ticket, but reopen if needed.

Thanks,
Suvvi,

**Comment by nsuvarnaiari** [comment]
Correction: Name: polyadenylated transcript 3'-end-sequencing evidence

**Comment by murphyte** [comment]
awesome, thanks!
