### ISSUE TITLE
NTR: galactokinase reporter gene assay evidence

### ISSUE THREAD

**Issue by dsiegele** [evidenceontology/evidenceontology#275]
Suggested definition: 
A type of reporter gene assay evidence based on the fusion of the galK gene to a specific promoter for the expression of the enzyme galactokinase. 

An assay for quantifying galactokinase activity is described in Wilson, DB and Hogness, DS (1966) Galactokinase and uridine diphosphogalactose 4-epimerase from Escherichia coli, Methods Enzymol. 8:229-240.

**Comment by mgiglio99** [comment]
Hi Debby - this looks good - we'll add it in the next release.

**Comment by dsiegele** [comment]
Thank you!
________________________________________

**Comment by nsuvarnaiari** [comment]
Hi @dsiegele 

Your new term is now publicly available in today's ECO release.

Name: galactokinase reporter gene assay evidence
ECO Id: ECO:0006238
Parent ECO id: ECO:0000049 (reporter gene assay evidence)

Closing the ticket now. Please reopen if needed.

Thanks,
Suvvi
