### ISSUE TITLE
Extending ontology with sex, ethnicity and age categories

### ISSUE THREAD

**Issue by DeniseSl22** [evidenceontology/evidenceontology#278]
Hi all,

We're in the process of allowing users of our [tool](https://pathvisio.github.io/) to use the Evidence and Conclusion Ontology to annotate pathways with more detailed information. Recently we stumbled on a [paper](https://doi.org/10.1038/s41592-021-01168-6), asking -omics databases for sex, ethnicity and age specific annotations.  We would like to do this in a structured manner through using ECO, however couldn't find terms describing this (see also [this issue](https://github.com/wikipathways/academy/issues/18)).

Would it be possible to add this information in your ontology?

**Comment by nsuvarnaiari** [comment]
Hi Denise,

Thanks for considering ECO to annotate pathways. We will take a look at the paper you mentioned and discuss your request in our next meeting which will be in three weeks (some of us will be out on vacation in coming weeks). 
If you want to use just the terms male, female, sex, ethnicity and age, there is Semanticscience Integrated Ontology (SIO), which can be useful.
Will get back to you soon.

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Forgot to ask, could you also let us know with an example how you would want to annotate pathways with sex, ethnicity and age details. It will be very helpful for us to understand your needs. Thanks again!

**Comment by DeniseSl22** [comment]
Hi @nsuvarnaiari , thank you for getting back to me so soon and considering my request. 
I've checked the SIO, but that's not what we're after. The SIO mentions the term "ethnicity" for example, but does not provide subclasses (Caucasian, African-American etc.). We were thinking in the line of adding cell line/culture evidence:
![image](https://user-images.githubusercontent.com/26277832/123776173-54f36800-d8cf-11eb-8f31-4723c7bdf4b3.png)

What we want to do, is add an annotation on interactions within a pathway, stating from what type of evidence this interaction is derived. For example, a publication describes a causal link between gene X and disease Y, where participants in the study were all male (probably no genotyping was performed to determine XY), 90% Caucasian participants (again probably no genotyping was performed, this is often done with a questionnaire), within an age range of 48 +- 8 years (again no reliable measure for this, mostly based on information from participants). As you can see from this example, there is some uncertainty on the study group and factors attributed to this group itself, which could be nice to capture in a pathway model, for example with the existing term [ECO:0005613 inference by association of genotype from phenotype](https://www.evidenceontology.org/browse/#ECO_0005613). However, if we would want to include the main features of this study group (results are relevant for Caucasian males between 40-56) within the model, we would need additional terminology. I'm not sure which cut-offs to use for the age-groups (some might be relevant for Inherited Metabolic Disorders for example, since these present differently between newborns, kids, and adults); this could be extended with age ranges relevant for certain sexes (e.g. post/pre menopausal for women, pregnancy trimesters, and other hormonal changes greatly influencing biological measurements). For ethnicity, I found this paper interesting: [Bhopal RGlossary of terms relating to ethnicity and race: for reflection and debateJournal of Epidemiology & Community Health 2004;](http://dx.doi.org/10.1136/jech.2003.013466). Hope my explanation helps, if not let me know :).

**Comment by ivanerill** [comment]
That's an interesting point, but hard to see how it could be easily articulated in ECO. A specialized term could be derived from ECO:0005613 (inference by association of genotype from phenotype), to something like "gender-biased inference by association of genotype from phenotype", but providing more granularity (e.g. the percentage of male/female) is not something that ECO is set up to capture (in the same way it is not meant to capture proportions of reagents in a Western blot).

An interesting derivative here would be to think of biases as an orthogonal entity type, since they are not really "evidence" in a meaningful way, nor assertion types either, but they modulate both. So a subontology could be derived for experimental biases, and terms derived by cross-linking bias, evidence and assertion terms.

**Comment by DeniseSl22** [comment]
@ivanerill : yes, the % is not something we also think we should capture (because it's also depending on amount of study participant, if the findings are statistically significant).... that is a bit too detailed for now. But having a term stating "male sex-biased ..." vs "female sex biased" would already be a great addition. And this being considered evidence yes/no --> I leave that up to your group (since its in the name of the ontology ;) ). However I do feel it is a certain level of evidence, as finding result in cell cultures are considered to be of less evidential value as compared to the same findings in modeling organism, which is then of less evidential value as findings in humans (with again a difference between preclinical and clinical studies).... to make it all even more complex...

**Comment by DeniseSl22** [comment]
Another interesting paper I just came across: [The misuses of “biological sex” by Katrina Karkazis, Lancet 2019](https://doi.org/10.1016/S0140-6736(19)32764-3).

**Comment by mgiglio99** [comment]
@DeniseSl22 
Upon further review of this issue, we don't think the types of terms you are looking for (e.g. "male-sex biased...")  are a good fit for ECO. They don't seem to be evidence for an assertion so much as modifiers to attach to results (which themselves might be evidence for an assertion.)
With regard for terms for sex, gender, ethnicity you might want to consider SNOMED CT for this - which we have used to capture some of this information for other projects.
With regard to your comment - "However I do feel it is a certain level of evidence, as finding result in cell cultures are considered to be of less evidential value as compared to the same findings in modeling organism, which is then of less evidential value as findings in humans..." - we could have (and do have some) terms describing cell culture, animal model, and other system derived evidence, what you seem to be wanting is some kind of confidence assessment, which ECO is not set up to provide.
I'm going to close this issue, but please reopen it if you'd like to discuss this further - we'd be happy to explore further as needed.
Thanks,
Michelle
