### ISSUE TITLE
ECO:0000320 should map to IKR as a 3-letter code, not IMR

### ISSUE THREAD

**Issue by ukemi** [evidenceontology/evidenceontology#281]
In the gaf-eco-mapping-derived.txt file, the mapping for ECO:0000320 has two mappings:

ECO:0000320	IKR	Default
ECO:0000320	IMR	Default	
but according to 
http://wiki.geneontology.org/index.php/Inferred_from_Key_Residues_(IKR) the code should be IKR.
@loricorbani

**Comment by nsuvarnaiari** [comment]
Hi David,

Looks like IKR is also referred as IMR. Was "IMR" a GO code before?
I will remove "has_GO_evidence_code IMR" annotation attached to the term ECO:0000320 which will fix gaf-eco-mapping-derived.txt file. We are scheduled to push a release on Friday, can I wait till Friday to make this change? I can do an emergency release if this is breaking things at your end.

Thanks,
Suvvi

**Comment by ukemi** [comment]
Thanks Suvvi. It's only a couple of annotations that are coming in through a testing pipeline at the moment, so Friday is fine.
@loricorbani

**Comment by pgaudet** [comment]
> Was "IMR" a GO code before?

Yes it was, we changed to IKR several years ago.

**Comment by nsuvarnaiari** [comment]
Hi David,
This is fixed in today's release.
ECO:0000320 is now mapping only to IKR.
Both gaf-eco-mapping.txt and gaf-eco-mapping-derived.txt have "ECO:0000320 IKR Default" only.

Thanks,
Suvvi
