### ISSUE TITLE
ECO codes https://github.com/evidenceontology do not have a grouping designation

### ISSUE THREAD

**Issue by dvklopfenstein** [evidenceontology/evidenceontology#285]
## ECO codes https://github.com/evidenceontology do not have a grouping designation

These ECO codes are seen in gpa files from ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/ and https://github.com/evidenceontology/evidenceontology/blob/master/eco-basic.obo, but not seen in https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt:

```
**ERROR:     14,035 INSTANCES OF ECO:0005547 IN GPAs
**ERROR:      3,390 INSTANCES OF ECO:0005544 IN GPAs
**ERROR:        712 INSTANCES OF ECO:0005546 IN GPAs
**ERROR:        470 INSTANCES OF ECO:0005610 IN GPAs
**ERROR:        152 INSTANCES OF ECO:0005543 IN GPAs
```

Is it expected that some ECO codes will have no group designation, such as ISA, IEA, ISS, etc.?

Many researchers use the grouping designation, rather than the ECO codes. If some ECO codes have no grouping designation, then we need to update our annotation file readers to reflect this. Currently, there are only five ECO codes that have no grouping designation.

FYI, these annotation files contain ECO codes that do not exist in the ECO definition file:
```
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/ARABIDOPSIS/goa_arabidopsis.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/CHICKEN/goa_chicken.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/COW/goa_cow.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/FLY/goa_fly.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/PIG/goa_pig.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/RAT/goa_rat.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/WORM/goa_worm.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/YEAST/goa_yeast.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/ZEBRAFISH/goa_zebrafish.gpa.gz
```

## Additional context
All files downloaded Dec 21, 2021
https://github.com/geneontology/helpdesk/issues/372

**Comment by mgiglio99** [comment]
Hello,
These 5 terms should map to the GO evidence code IC.
We were asked to wait to make a mapping update until after the December GO release - but that has now happened so we will update these soon and push a new version of the derived file.

looping in @nsuvarnaiari

**Comment by mgiglio99** [comment]
Hello again, 
We are planning to push a new release of ECO and the derived file during the first week of January.
Is that soon enough to meet your needs?
Also, I realized that I didn't reply to one of your questions. In fact, not all ECO terms will map to a GO evidence code (as not all ECO terms contain evidence types that are covered by a GO evidence code), however we endeavor to make it such that all ECO terms that are relevant to a GO evidence code do have those mappings.
Michelle

**Comment by mgiglio99** [comment]
Hello,
The new mappings for the above terms are in the latest ECO release.
I'm going to close this issue. But please reopen if you have further questions or concerns.
Regards,
Michelle
