### ISSUE TITLE
Purl links are broken

### ISSUE THREAD

**Issue by cpauvert** [evidenceontology/evidenceontology#292]
Hi all,
I raised an issue in the ontobee repository as well (https://github.com/OntoZoo/ontobee/issues/174), but the purl links for the terms points to ontobee and indicate the term was not found.

Best,
Charlie

**Comment by nsuvarnaiari** [comment]
Hi Charlie,

Thanks for bringing this to our notice. We will follow https://github.com/OntoZoo/ontobee/issues/174 to to make sure they fix the issue.

Thanks again,
Suvvi

**Comment by yongqunh** [comment]
This should be fixed now. Thanks.
https://www.ontobee.org/ontology/ECO

**Comment by nsuvarnaiari** [comment]
Thanks @yongqunh and @cpauvert !
