### ISSUE TITLE
NTR: qualitative macroscopy evidence

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#294]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-05a1bed5-7fff-9e1d-58cb-1df5059aaea2"><div dir="ltr" style="margin-left:0pt;" align="center">

Label | qualitative macroscopy evidence
-- | --
Parent term | macroscopy evidence (ECO:0001094)
Definition | A type of qualitative experimental evidence that is visible to the naked eye cf. microscopy evidence which requires the aid of a microscope.
Definition reference | Existing definition from ECO:0001094
Requester name | Alayne Cuzick
Requester email | alayne.cuzick@rothamsted.ac.uk
Requester organization | PHI-base (Rothamsted Research)
Additional information |  

</div></b>
</body>
</html>

Tagging project members
@ValWood
@jseager7

**Comment by mgiglio99** [comment]
Hi @CuzickA 
We are happy to include this term in ECO. However, the current proposed definition does not describe how qualitative macroscopy is different than its parent.  The definition of the new term should begin "A type of macroscopy evidence that ...." and then proceed to describe the qualitative aspects that differentiate this term from its parent.
Please let us know your thoughts on how to define this.
Thanks

**Comment by mgiglio99** [comment]
@CuzickA 
Just following up on this one.

**Comment by CuzickA** [comment]
Hi @mgiglio99, thanks for the reminder. 
How about
"A type of macroscopy evidence that is assessed qualitatively (e.g. presence/absence)."

**Comment by mgiglio99** [comment]
Hi Alayne,
We are thinking the def should more explicit about what qualitative means. What do you think of this one:

A type of macroscopy evidence in which non-numerical observed characteristics or features are captured as text descriptions or categorical assignments.
def ref: https://en.wikipedia.org/wiki/Qualitative_property

**Comment by nsuvarnaiari** [comment]
HI @CuzickA 

The term "qualitative macroscopy evidence" (ECO:0006342) has been released.

Thanks,
Suvvi
