### ISSUE TITLE
NTR: quantitative macroscopy evidence

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#295]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-614d48ef-7fff-5856-91d7-bfd3adad9937"><div dir="ltr" style="margin-left:0pt;" align="center">

Label | quantitative macroscopy evidence
-- | --
Parent term | macroscopy evidence (ECO:0001094)
Definition | A type of quantitative experimental evidence that is visible to the naked eye cf. microscopy evidence which requires the aid of a microscope.
Definition reference | Existing definition from ECO:0001094
Requester name | Alayne Cuzick
Requester email | alayne.cuzick@rothamsted.ac.uk
Requester organization | PHI-base (Rothamsted Research)
Additional information |  

</div></b>
</body>
</html>

Tagging project members
@ValWood
@jseager7

**Comment by mgiglio99** [comment]
Hi @CuzickA 
We are happy to include this term in ECO. However, the current proposed definition does not describe how quantitative macroscopy is different than its parent.  The definition of the new term should begin "A type of macroscopy evidence that ...." and then proceed to describe the quantitative aspects that differentiate this term from its parent.
Please let us know your thoughts on how to define this.
Thanks

**Comment by mgiglio99** [comment]
Hi @CuzickA 
Just following up on the above question.
Michelle

**Comment by CuzickA** [comment]
Hi @mgiglio99,
How does this sound?
"A type of macroscopy evidence that is assessed quantitatively (using a numerical measure)."

**Comment by mgiglio99** [comment]
Hi Alayne,
We are thinking the def should more explicit about what quantitative means. What do you think of this one:

A type of macroscopy evidence in which measurement techniques result in numerical data. 
def ref: https://en.wikipedia.org/wiki/Quantitative_research

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

The term "quantitative macroscopy evidence" (ECO:0006343) has been released.

Thanks,
Suvvi
