### ISSUE TITLE
NTR: sporulation assay evidence

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#296]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5400c86b-7fff-1ad7-5ea5-0ba3f6638b14"><div dir="ltr" style="margin-left:0pt;" align="center">

Label | sporulation assay evidence
-- | --
Parent term | direct assay evidence (ECO:0000002)
Definition | A type of direct assay evidence resulting from the study of the occurrence of spore formation.
Definition reference | Sporulation Definition and Examples - Biology Online Dictionary or Sporulation Definition & Meaning - Merriam-Webster
Requester name | Alayne Cuzick
Requester email | alayne.cuzick@rothamsted.ac.uk
Requester organization | PHI-base (Rothamsted Research)
Additional information | See ‘sporulation’ at GO:0043934.Note that PHI-base distinguishes sporulation assays for sexual and asexual spores, but if ECO decides that this distinction is too fine-grained for the ontology, we can still infer this information from other annotations in our curated data.

</div></b>
</body>
</html>

Tagging project members
@ValWood
@jseager7

**Comment by mgiglio99** [comment]
Hello @CuzickA 

Thanks for requesting this term. We are wondering if we could make the definition include a bit more detail. How does the below suggestion sound to you?
Def: A type of direct assay evidence that reflects the presence, absence, and/or amount of spore formation.

We are happy to make asexual and sexual children of this term as well if you feel they will be of value.
Please send us your proposed definitions for them.

Thanks

**Comment by mgiglio99** [comment]
hello @CuzickA 
Just following up on the above comment/questions.
Michelle

**Comment by CuzickA** [comment]
Hello @mgiglio99,
Your proposed definition sounds good thanks.
Def: A type of direct assay evidence that reflects the presence, absence, and/or amount of spore formation.

Please could you also create the asexual and sexual child terms 

NTR: asexual sporulation assay evidence
Parent term: sporulation assay evidence
Definition: A type of sporulation assay evidence that observes asexual spore formation.
Additonal information: See ‘asexual sporulation’ at GO:0030436


NTR: sexual sporulation assay evidence
Parent term: sporulation assay evidence
Definition: A type of sporulation assay evidence that observes sexual spore formation.
Additonal information: See ‘sexual sporulation’ at GO:0034293

Many thanks, Alayne

**Comment by mgiglio99** [comment]
Thanks Alayne,
In thinking about this some more, we feel like using the more complete definition for the child terms will be easier for users. So we propose the following:

NTR: asexual sporulation assay evidence
Def: A type of sporulation assay evidence that reflects the presence, absence, and/or amount of asexual spore formation.

NTR: sexual sporulation assay evidence
Def: A type of sporulation assay evidence that reflects the presence, absence, and/or amount of sexual spore formation.

Is this ok with you?

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

The following terms have been released today:
sporulation assay evidence - ECO:0006344
asexual sporulation assay evidence - ECO:0006345
sexual sporulation assay evidence - ECO:0006346

Thanks,
Suvvi

**Comment by CuzickA** [comment]
Hi @nsuvarnaiari and @mgiglio99 
Many thanks for creating all the requested terms. Apologies for the delayed reply, I have been out of the office.
Best wishes,
Alayne
