### ISSUE TITLE
NTR: surrogate penetration assay evidence

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#297]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-3b239bfe-7fff-bd1b-b3ce-a7263c3a5976"><div dir="ltr" style="margin-left:0pt;" align="center">

Label | surrogate penetration assay evidence
-- | --
Parent term | experimental evidence (ECO:0000006)
Definition | A type of experimental evidence in which the extent of penetration into a surrogate (synthetic / non-living) barrier is measured.
Definition reference | PHI-base
Requester name | Alayne Cuzick
Requester email | alayne.cuzick@rothamsted.ac.uk
Requester organization | PHI-base (Rothamsted Research)
Additional information |  

</div></b>
</body>
</html>

Tagging project members
@ValWood
@jseager7

**Comment by mgiglio99** [comment]
This term looks good - one note we have is whether we should specify in the definition that this is specifically a host surrogate. Our suggestion would be:
Def: "A type of experimental evidence in which the extent of penetration into a host-surrogate material consisting of a synthetic or other non-living substance is measured.
Likewise, we would also suggest changing the name to 'host-surrogate penetration assay evidence'.
Please let us know your thoughts.
Thanks

**Comment by CuzickA** [comment]
Thanks, this sounds like a good idea. 
The suggested definition and term name change look good thanks.

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

The term "host-surrogate penetration assay evidence" (ECO:0006347) has been released today.

Thanks for your new term request.
Suvvi
