### ISSUE TITLE
NTR: host penetration assay evidence

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#298]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-fdb14215-7fff-5b45-69ad-4666ec0deaba"><div dir="ltr" style="margin-left:0pt;" align="center">

Label | host penetration assay evidence
-- | --
Parent term | host colonization assay evidence (ECO:0001830)
Definition | A type of host colonization assay evidence in which the extent of penetration into host tissue is measured.
Definition reference | PHI-base
Requester name | Alayne Cuzick
Requester email | alayne.cuzick@rothamsted.ac.uk
Requester organization | PHI-base (Rothamsted Research)
Additional information | See ‘entry into host’ at GO:0044409.

</div></b>
</body>
</html>

Tagging project members
@ValWood
@jseager7

**Comment by mgiglio99** [comment]
Looks good - we will include this in our next release which will happen by the end of July.

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

The term has been released today. 
host penetration assay evidence: ECO:0006348

Thanks for your new term request.
Suvvi
