### ISSUE TITLE
Edit comment for host colonization assay evidence (ECO:0001830)

### ISSUE THREAD

**Issue by CuzickA** [evidenceontology/evidenceontology#299]
Requesting that the comment be changed from

> Has to do with the ability of the bacterium or virus to bind to a host.

to the following:

> Has to do with the ability of the bacterium, fungus, protist or virus to bind to a host.

or, alternatively:

> Has to do with the ability of a microorganism to bind to a host.

PHI-base uses ECO terms to annotate pathogen-host interactions involving bacteria, fungi and protists. We recently requested a new term for ‘host penetration assay evidence’ (see issue #298), with ‘host colonization assay evidence’ as the parent. For this reason, we'd like the comment on the latter term to be broadened to include other types of organisms.

For reference, the NCI Thesaurus definition of [colonization](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C128361) uses ‘microorganisms’ instead of being restricted to bacteria and viruses.

Tagging project members
@ValWood
@jseager7

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

Thanks for suggesting a change to the definition. We will discuss internally and let you know our thoughts soon.

We will also look into your other new term requests soon. 

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
Hello @CuzickA 
Thanks so much for catching this.
Here is our suggestion for a new comment:
"Has to do with the ability of a symbiont (any organism living in close association with a host, including both beneficial and parasitic relationships) to bind to a host."
We decided to use symbiont because this is the terminology that we are using in GO to describe these kinds of interactions.
Does this sound ok?
Thanks

**Comment by CuzickA** [comment]
Hello @mgiglio99,
The suggested new comment sounds good thanks.

**Comment by nsuvarnaiari** [comment]
Hi @CuzickA 

The discussed change in the comment can be seen in today's release (08/05/2022).

Thanks for your suggestion,
Suvvi
