### ISSUE TITLE
New terms for MimicDB

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#300]
Balint has requested some new terms on behalf of the MimicDB.
MimicDB collects and annotates protein-protein interactions formed by a class of human cell surface receptors called integrins.

Spreadsheet of terms:
https://docs.google.com/spreadsheets/d/1UF_NFUFAkA8JtSq85xIqTN1OwRLEUJwadxP-LHSHf9k/edit?usp=sharing

Two new terms will be added and one term resurrected from obsolete land.

New terms:
name: iodine-125-labeled ligand binding evidence 
def: A type of radioligand binding assay evidence in which iodine-125 label is used to measure receptor-ligand interactions, such as in determining selectivity for a particular ligand.

name: bio-layer interferometry evidence
def: A type of molecule detection assay evidence in which the detection of the interaction between molecules is done without the use of labels and is instead based on the phase shift-wavelength correlation created between interference patterns off of two unique surfaces on the tip of a biosensor, where the ligand is immobilized onto a bio compatible biosensor while the analyte is in solution.

Resurrected term:
ECO:0006249
name: bait-prey protein pull-down evidence
def: A type of protein binding evidence resulting from an affinity purification in-vitro technique used to detect physical interactions between two or more proteins, where a molecule of interest - a "bait" - is immobilized and incubated with a protein source containing putative "prey" proteins.

We also suggested the possibiliity of a grouping parent for the resurrected bait-prey term and the other existing bait-prey term ECO:0000025, 'bait-prey hybrid interaction evidence'.

**Comment by mgiglio99** [comment]
email from Katalin:
Thank you for the comments on the proposed new terms, and sorry for my late answer.
We went through your comments, and in the case of bait-prey protein pull-down evidence, it is perfect if you reinstate the old term and create a grouping parent for the restored one and the 'bait-prey hybrid interaction evidence'; thanks.
The bio-layer interferometry evidence: 
It is right that IRIS and BLI are very similar techniques, but we think BLI should not be a child term of IRIS. Both are label-free detection methods, but BLI is not a subtype of IRIS technique. 
If you agree with us, it can be a solution to create a 'label-free molecule detection assay evidence' under the 'molecule detection assay evidence' term.
Into this label-free group can go IRIS and BLI as child terms and maybe SPR could also have this 'label-free molecule detection assay evidence' term as a parent.
I put in the table our idea about the definition of the 'label-free molecule detection assay evidence'.
Another solution can be to have BLI under the 'direct assay evidence', so it would be on the same level as SPR.
What do you think about these above-mentioned ideas?
Best regards,
Kata


Outcome
New grouping parent term for the existing bait-prey term and the resurrected term.
name: bait-prey interaction evidence
def: A type of protein binding evidence in which the use of "bait" molecules or proteins allows the purification or identification of a binding partner, the "prey". 
parent:  ECO:0000024 (protein binding evidence)

This term will have two children:
Resurrected: ECO:0006249, 'bait-prey protein pull-down evidence'
AND
ECO:0000025, 'bait-prey hybrid interaction evidence'

Regarding the new 'bio-layer interferometry evidence' term above and the related existing term ECO:0005520 'interferometric reflectance imaging sensor evidence' - Katalin suggested making a parent grouping term for these called 'label-free molecule detection assay evidence', however, we decided not to do this since that would then require us to classify all of the children of 'molecule detection evidence' as either using labels or label-free. So we are making the two interferometry terms as direct children of 'molecule detection evidence'. 
Katalin also suggested that 'surface plasmon resonance evidence' could also be grouped with the above terms. For now, we prefer to leave 'surface plasmon...' where it is under 'physical interaction evidence.'

**Comment by nsuvarnaiari** [comment]
The terms have been released on 08/05/2022.
The terms and their ECO ids are in the google spreadsheet:
https://docs.google.com/spreadsheets/d/1UF_NFUFAkA8JtSq85xIqTN1OwRLEUJwadxP-LHSHf9k/edit?usp=sharing
