### ISSUE TITLE
question on ECO:0001032 'constitutively active mutant evidence'

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#302]
@pgaudet

Hi Pascale,
I'm trying to clean out old ECO issues and found this in one of them.
Looks like we never made any changes based on the exchange below:

> 6. 'constitutively active mutant evidence' ECO:0001032
>     current def: A type of experimental phenotypic evidence resulting from a constitutively active mutant (CAM), resulting in mutant proteins that remain active in the absence of upstream signals.
>     Should we consider modifying the current definition? A constitutive mutation = a mutation usually in the operator gene or regulator gene resulting in unregulated expression of structural genes.
>     Response: This is not what we meant - this was done with kinases in mind, but probably other regulated proteins can have this behavior: some mutations make them catalytically active without any stimulation.
>     I believe that the mutation is within the DNA, so would this term be better placed as a child of 'mutant phenotype evidence'?
>     Response: As I mentioned above, we meant something different. You might want to create that other term, although personally I would use 'overexpression evidence' for this (not sure what the exact ECO term is).
>     We would like to change the label to 'constitutively active mutant phenotypic evidence'.
>     Response: If this covers mutated gene products (proteins), sure.

I'm trying to understand the discussion - and I realize this was a long time ago that you had this conversation with James, but my question is this: Is the above term meant to capture when this happens naturally and is observed? As opposed to when something is engineered?

Thanks,
Michelle

**Comment by pgaudet** [comment]
Hi Michelle, 

For me a constitutionally active mutation (in a protein) is when a normally regulated protein is always active, regardless of the stimulus , for example as in 
https://www.tandfonline.com/doi/pdf/10.4161/cc.4.11.2170
or https://scholars.duke.edu/display/pub642769

This was different from 'constitutively expressed'. 

Thanks, Pascale

**Comment by mgiglio99** [comment]
I see, thanks for the clarification.
Maybe the addition of the word "protein" in the term name would help reduce the possibility of future confusion.
New name would be: 'constitutively active mutant protein evidence'
Also, I think it could move to be a child of 'mutant phenotype evidence'
Do both of those changes sound ok?
Thanks again

**Comment by pgaudet** [comment]
That works for me. 

Thanks! 

Pascale

**Comment by mgiglio99** [comment]
To sum up:
'constitutively active mutant evidence' ECO:0001032
parent: 'mutant phenotype evidence' ECO:0000015
def: A type of mutant phenotypic evidence resulting from a mutation causing a change to a protein sequence that produces a constitutively active mutant protein (CAM), that remains active in the absence of upstream signals.

This change is going into the next release.

**Comment by nsuvarnaiari** [comment]
The term 'constitutively active mutant evidence' ECO:0001032 has been moved under 'mutant phenotype evidence' ECO:0000015 from 'experimental phenotypic evidence' ECO:0000059. 
The definition is updated.
These edits have been pushed in April, 2023 release.

**Comment by mgiglio99** [comment]
In my summary above, I realize that I failed to change the label to the new name:
'constitutively active mutant protein evidence'
We can make that small edit in the next release.
Sorry for my oversight.

**Comment by mgiglio99** [comment]
We caught this before the release was made. The name change will make it into this April release.

**Comment by mgiglio99** [comment]
One final note - this term will now be mapped to GO IMP instead of EXP.
