### ISSUE TITLE
NTR

### ISSUE THREAD

**Issue by docmattc** [evidenceontology/evidenceontology#303]
We have a series of biosynthetic pathways in which the intermediates (and therefore enzymes that may make them) are hypothetical. However I don't see any terms to indicate such occurrences. Thus, we have no way to indicate the evidence (or lack thereof) for these compounds and reactions
Before I generate suggestions for new terms, are these something you would consider?

**Comment by mgiglio99** [comment]
Hello @docmattc 
We'd be very glad to work with you, but before I can say whether the terms you want are within scope for ECO I'll need a bit more info. I'm not sure I understand the scenario you described. Could you give an example of the type of information you have and the assertion that you would use it for?
Best,
Michelle

**Comment by docmattc** [comment]
Hi Michelle,
    I am curating glycolipid synthesis pathways into wikipathways (which will in a future release have facility to capture ECO) for which some of the intermediates, and many of the enzymes are unknown.
For example on this graphic: https://lipidmaps.org/assets/images/pathways/SphinGOMAP_ganglio_20191015.jpg
those species with dotted boxes have not been characterized, but given the long sugar chains are made by adding sugars sequentially, many of them must exist (though branching adds complication)

**Comment by mgiglio99** [comment]
We have the term 'no evidence data found' ECO:0000035
It has both automatic and manual assertion childrend.
Would this be what you need?

**Comment by mgiglio99** [comment]
Hello again,
My colleague @nsuvarnaiari and I talked about this some more and another suggestion we have is to create a term under the 'curator inference' ECO:0000205 node.
We were thinking it might be similar to 'inference from background scientific knowledge' ECO0000001 (and perhaps a child of it) since you mentioned above that the intermediate structures are inferred because of knowledge about how sugars assemble. So perhaps something along the lines of 'inference from knowledge of molecule assembly patterns' (or something like that - not sure how to capture it.)
Let us know your thoughts,
Michelle

**Comment by docmattc** [comment]
Hi, 
   for the linear sugars this would work, but the branched ones are more complicated because the order of assembly is unknown, the species we have are hypothetical.  
    In a branched structure you may build all the the 'trunk' (to take a tree analogy) and then add branches, or you may add a branch as soon as the trunk is tall enough, or possibly both could happen. If there are two branches, are they built independently, or reliant on each other?

**Comment by mgiglio99** [comment]
Hi @docmattc 

Is the disassembly something that you do actually physically? Or  is it a computational process?
Also, what part does the combinatorial aspect play? If this is an experimental process that leads to a prediction, we could capture that as an evidence type.

Depending on the answers to above we might take a whole different approach - but if we stay on the current idea of putting it under 'curator inference', then we are thinking it would be good to try to make the term a bit general so it can encompass a whole category of things. Or maybe that's not possible, which is fine. 
What do you think of:
'inference of molecular structure from combinatorial disassembly of larger molecule'

But again, we might want to shift over to capturing the process used a bit more depending on what it is.

Michelle

**Comment by docmattc** [comment]
I think I shouldn't have used disassembly, this isn't what's done. 

We have a known product which can have been created via several plausible routes from several plausible substrates. What is not know is which of the plausible substrates are real and exist on the pathway.  

So 'inference of molecular structure from combinatorial disassembly of larger molecule' might work, but I'm not sure. 
I guess my main issue is that I'm not convinced any of these things being curated at all is helpful to science.

**Comment by mgiglio99** [comment]
Hi,

How about we go with something fairly general then:
'inference of intermediate molecular structure from structure of final molecule'

Or are you now thinking that maybe you don't want to capture this information at all?

Michelle

**Comment by mgiglio99** [comment]
Hi - just following up on this one - any new thoughts?
Thanks,
Michelle

**Comment by docmattc** [comment]
Sorry for the delay, I'd missed this. That does seem a sensible solution

Matt

**Comment by mgiglio99** [comment]
Apologies for the delay on this - we'll be back in touch with all of the details filled in soon.

**Comment by mgiglio99** [comment]
Hello @egonw and @docmattc 

Here are the proposed details for the above proposed term:

ECO:new:  'inference of intermediate molecular structure from structure of final molecule'
Def: A type of curator inference in which the structure of a possible intermediate molecule made during a biosynthetic process is inferred based on the structure of the final molecule in the process.
Parent: 'curator inference' ECO:0000205

Sorry for the delay on this - I had an overwhelmingly busy summer.
Michelle

**Comment by nsuvarnaiari** [comment]
Hi @egonw and @docmattc
I went ahead and created the term and associated assertion terms. They are made public in yesterday's release. In case you would like to make some edits to what Michelle proposed, we will incorporate those edits in the next release.
Term: 'inference of intermediate molecular structure from structure of final molecule'
Parent: 'curator inference' ECO:0000205

| ECO_id      | ECO_label                                                                                                   |
|-------------|-------------------------------------------------------------------------------------------------------------|
| ECO:0008015 | inference of intermediate molecular structure from structure of final molecule                              |
| ECO:0008029 | inference of intermediate molecular structure from structure of final molecule used in automatic assertion  |
| ECO:0008028 | inference of intermediate molecular structure from structure of final molecule used in manual assertion     |

Thanks,
Suvvi

**Comment by docmattc** [comment]
Thanks- that works for us. 
Apologies for the delay, as a non-developer I don't find github the most natural form of communication

**Comment by egonw** [comment]
Well, I use GitHub a lot, but had not find the time to reply. Thanks for the addition!
