### ISSUE TITLE
automatic assertions of geographic assignments by coordinates

### ISSUE THREAD

**Issue by Woolly-at-EBI** [evidenceontology/evidenceontology#304]
term: automatic assertions of geographic assignments by coordinates
definition: automatically assigning a geographic property by using coordinates that have been searched against polygons with geographic properties (shapefiles). 
parent:  [computational evidence used in automatic assertion](http://purl.obolibrary.org/obo/ECO_0007669)

Hi, 
I am a curator at ENA (part of EMBL-EBI). We are enhancing the metadata on 100,000's of sequenced samples that have GPS coordinates. We can assign multiple geographic attributes e.g. the sample was in a sea, a specific sea, coastal, land with relatively high confidence.  

Thanks,
Peter

**Comment by mgiglio99** [comment]
Hi Peter,
Thanks for your new term requests.
In ECO, our design pattern is to make terms specific to the type of evidence and then create assertion-type children of that term for manual and automatic curation.
Therefore, I suggest that the main term we would want might be something like:
'geographic assignment based on coordinate mapping'
Def: "Determination of a geographic property by searching coordinates against polygons with associated geographic properties (shapefiles)."
Then we would make the two children of this term that would be:
'geographic assignment based on coordinate mapping used in automatic assertion'
'geographic assignment based on coordinate mapping used in manual assertion'

The same would apply to the other new term you requested related to taxa.

Would this structure work for you? We'll have to figure out what the parent would be for the evidence-type term.

Best,
Michelle

**Comment by Woolly-at-EBI** [comment]
Hi Michelle,
Yes agree with your suggestions.
What about parent ECO:0007672 computational evidence, or could be a new intervening node in the ontology between that and 'geographic property assignment based on coordinate mapping' e.g. "computational geographic evidence"?

Thank you so much for the responsiveness and suggestions.

BTW: For further context, there are other geo-type data e.g. altitude, depth, tide-times, sunset etc. so there are multiple types of "geographic" evidence that could be used beyond coordinates.  Our marine domain expert has got a long tail of such metadata for me to investigate. Some of these will obviously be inferred using a combination of sample date/time and coordinates, so some existing terms in your ontology already apply. (first though we are concentrating on taxonomy and coordinate based metadata) All this metadata enhancement information will be going into the contextual clearinghouse https://www.ebi.ac.uk/ena/clearinghouse/api/.  This metadata will be displayed alongside the submitted archiving records in biosamples (this is where the sample data for all ENA and other archives goes). So using your ECO terms helps makes the metadata about the evidence concise and searchable for starters!

Kind Regards,
Peter

**Comment by mgiglio99** [comment]
Hi Peter,

Thanks for the additional info on the context. It's really helpful to have a sense of how our users are applying the terms.

My colleague @nsuvarnaiari  and I were thinking about a parent for these new terms and that led us to think about the wording of their names too.
We agree with your suggestions regarding 'computational evidence' and 'computational inference'
What do you think of this structure:
'computational evidence' ECO:0007672
---'computational inference' ECO:0000362
------'coordinate mapping to a reference' ECO:new
---------'coordinate mapping to geographic property shapefiles' ECO:new

Michelle

**Comment by mgiglio99** [comment]
Hi Peter,
Just following up on this. 

Are you ok with the proposed parentage structure? We decided to take out the grouping term since there is only one coordinate mapping term at this time (unless you have additional ones that you'd like to add now.)
'computational evidence' ECO:0007672
---'computational inference' ECO:0000362
-----'coordinate mapping to geographic property shapefiles' ECO:new

And with the following name and revised definition:
Name: 'coordinate mapping to geographic property shapefiles'
Def: "Determination of a geographic property of an entity by searching coordinates associated with the entity against polygons with associated geographic properties in the form of shapefiles."

Thanks,
Michelle

**Comment by mgiglio99** [comment]
Now it's my turn to apologize for tardiness!
We'll get this new term implemented and released in the next few weeks.

**Comment by nsuvarnaiari** [comment]
Hi @Woolly-at-EBI ,

The requested term and associated assertion terms have been created and released.
Term: 'coordinate mapping to geographic property shapefiles'
Parent: 'computational inference' ECO:0000362

| ECO_id      | ECO_label                                                                         |
|-------------|-----------------------------------------------------------------------------------|
| ECO:0008014 | coordinate mapping to geographic property shapefiles                              |
| ECO:0008027 | coordinate mapping to geographic property shapefiles used in automatic assertion  |
| ECO:0008026 | coordinate mapping to geographic property shapefiles used in manual assertion     |

Thanks,
Suvvi
