### ISSUE TITLE
automatic assertions of geographic inference by taxonomy

### ISSUE THREAD

**Issue by Woolly-at-EBI** [evidenceontology/evidenceontology#305]
term: automatic assertions of geographic inference by taxonomy
definition: automatically assigning a geographic property by using the known geographic domains of a species. 
parent:  [computational evidence used in automatic assertion](http://purl.obolibrary.org/obo/ECO_0007669)

Hi, 
I am a curator at ENA (part of EMBL-EBI). We are enhancing the metadata on 100,000's of sequenced samples, as well as GPS submitted earlier, we also use taxonomy.

Thanks,
Peter

**Comment by mgiglio99** [comment]
Hi Peter,
Similar to what I said on the coordinates issue: https://github.com/evidenceontology/evidenceontology/issues/304, we would structure this term more along the lines of:
'geographic property assignment based on taxonomy'
Def: "Determination of a geographic property by use of known species geographic domains" 
Then we would make the two children of this term that would be:
'geographic property assignment based on taxonomy used in automatic assertion'
'geographic property assignment based on taxonomy used in manual assertion'

Let me know what you think of these suggestions.

Best,
Michelle

**Comment by Woolly-at-EBI** [comment]
Hi Michelle,
Yes agree with your suggestions for this too, it makes it more consistent.

Again what about parent ECO:0007672 computational evidence, or could be a new intervening node in the ontology between that and 'geographic property assignment based on taxonomy' e.g. "computational geographic evidence"?

This is a type of inference so for this evidence, I will additionally supply: 
ECO:0000364 "evidence based on logical inference from manual annotation used in automatic assertion"

Kind Regards,
Peter

**Comment by Woolly-at-EBI** [comment]
Hi Again,
meant to say above, IMHO it is good to have a mix evidence tags, then several can be used at the same time.
For the clearinghouse metadata they kind of encourage one to apply all the relevant evidence types.

KR,
Peter

**Comment by mgiglio99** [comment]
Hi Peter,
I want to make sure I understand the situation for this term.
I'm interpreting it as you have a biosample and you are attaching metadata to the sample.
The coordinate term in the other issue is pretty clear (at least I think I understand it) - in that situation you know the coordinates from which the sample was collected and then you retrieve geographic info from a reference based on those coordinates.
In this taxonomy case, I want to make sure I understand where the species comes into play. Is it that there is a species in the biosample, or, that the species is the biosample?  
And are you attaching geographic metadata to the sample based on what is known about where this species generally lives?
Thanks,
Michelle

**Comment by mgiglio99** [comment]
Hi Peter,
Just checking on this again. Please let us know the answers to the above questions so we can properly understand how to construct the term.
Thanks,
Michelle

**Comment by mgiglio99** [comment]
Hi Peter, @Woolly-at-EBI
I'm going to close this issue since we haven't heard from you, but please open it back up if you still need it -  we're happy to continue the work on this one.
Michelle
