### ISSUE TITLE
Edits to gaf-eco-mapping.txt 

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#306]
Hello, 

GO would like to add the following 2 mappings: 

https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt

- [ ] GO_REF:0000004 ECO:0007322
- [ ] GO_REF_0000023  ECO:0007322

Thanks, Pascale

**Comment by nsuvarnaiari** [comment]
Hi Pascale,

We will add them in gaf-eco-mapping.txt and ontology as well. Is it ok if I get them in for April release ( on April 7th) or do you want them before that? If you need before that, I can do an emergency release.

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Hi Pascale,

The GO_REF:0000004 (Gene Ontology annotation based on UniProtKB keyword mapping) is already mapping to 'evidence used in automatic assertion' (ECO:0000501). In this ticket you suggested adding it to 'curator inference used in automatic assertion' (ECO:0007322) which seems to be incorrect to me (my knowledge is limited, so I might be wrong). Could you pls revisit and confirm that this GO_REF needs to be removed from ECO:0000501 and added to ECO:0007322?

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
Hi @pgaudet 
Just pinging this ticket again to get your input on Suvvi's post above.
Thanks,
Michelle

**Comment by pgaudet** [comment]
Hi @mgiglio99 

Yes please remove GO_REF:0000004  from  ECO:0000501 and add it to ECO:0007322. 

Thanks for checking. 

Pascale

**Comment by mgiglio99** [comment]
Thanks Pascale,
We'll make the change.
Michelle

**Comment by nsuvarnaiari** [comment]
HI @pgaudet 

Sorry for the delay in getting this done.

The following GO_REFs have been added, 
1) GO_REF:0000004 ECO:0007322  (GO_REF:0000004 was previously under 'evidence used in automatic assertion' ECO:0000501 which was removed)
2) GO_REF_0000023 ECO:0007322

The 'https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping.txt' was also updated.

Thanks,
Suvvi
