### ISSUE TITLE
NTR: smFISH assay evidence

### ISSUE THREAD

**Issue by ValWood** [evidenceontology/evidenceontology#309]
smFISH
A single molecule fluorescence in situ hybridization (smFISH) is a technique optimized for studying gene expression in single cells but is distinct in its ability to localize and quantify individual RNA molecules.

I guess this would be a child of
ECO:0005518
RNA detection assay evidence

**Comment by mgiglio99** [comment]
Hi @ValWood 

We already have a term for 'fluorescence in situ hybridization evidence' ECO:0001047.
This new term could be a child of that.

Currently, we don't have DNA and RNA versions of these FISH terms (they are just under 'nucleic acid localization evidence') but if if you think that we should, we can work on how to structure that.

Best,
Michelle

**Comment by ValWood** [comment]
Your call, I can stick with ECO:0005518 RNA detection assay evidence, since that is the critical part. The smFISH tends to be used for quantification.

**Comment by nsuvarnaiari** [comment]
@ValWood @mgiglio99 

Here is what the term is going to look like. In case it needs edits, I can do them for the next release.
Term: 'single molecule fluorescence in situ hybridization'
Definition: 'A type of fluorescence in situ hybridization evidence resulting from the use of fluorescent probes to localize and quantify individual RNA molecules in single cells for studying gene expression.'
Parents: 'fluorescence in situ hybridization evidence' ECO:0001047 and 'RNA detection assay evidence' ECO:0005518.

Thanks,
Suvvi

**Comment by ValWood** [comment]
Thanks! looks good.

**Comment by nsuvarnaiari** [comment]
HI @Val,

The requested term and associated assertion terms have been created and released.
Term: single molecule fluorescence in situ hybridization evidence 
Parents: 'fluorescence in situ hybridization evidence' ECO:0001047 and 'RNA detection assay evidence' ECO:0005518.
The 'single molecule fluorescence in situ hybridization evidence used in manual assertion ' is mapping to GO Evidence Code 'IEP' and 'single molecule fluorescence in situ hybridization evidence used in automatic assertion' is mapping to GO Evidence Code 'IEA'.

| ECO_id      | ECO_label                                                                                |
|-------------|------------------------------------------------------------------------------------------|
| ECO:0008009 | single molecule fluorescence in situ hybridization evidence                              |
| ECO:0008017 | single molecule fluorescence in situ hybridization evidence used in automatic assertion  |
| ECO:0008016 | single molecule fluorescence in situ hybridization evidence used in manual assertion     |


Thanks,
Suvvi
