### ISSUE TITLE
iedb mhc evidence codes

### ISSUE THREAD

**Issue by rvita** [evidenceontology/evidenceontology#310]
attached is a sheet of evidence codes that we have been working on together, at their current state. We expect to need one more zoom calls to finish these up, but we can wait until after the obi term requests for some new processes (@sebastianduesing)
[eco_iedb.xlsx](https://github.com/evidenceontology/evidenceontology/files/13208227/eco_iedb.xlsx)
thanks!

**Comment by rvita** [comment]
Hi, I have an updated sheet - this one has the newly created obi terms that we use in our eco requests (on their own tab & referred to in the eco template). the last 6 rows of iedb eco terms on the template are ones that we still need to meet to discuss. 
[eco_iedb.xlsx](https://github.com/evidenceontology/evidenceontology/files/14027994/eco_iedb.xlsx)

**Comment by mgiglio99** [comment]
Feb. 13th meeting - discussed remaining terms from the list.
Updated sheet from Randi as of Feb. 21 is attached.
[Feb21_eco_iedb.xlsx](https://github.com/evidenceontology/evidenceontology/files/14394346/Feb21_eco_iedb.xlsx)

**Comment by mgiglio99** [comment]
March 22 meeting - discussed remaining terms - whole list is finished now.
Randi is doing a final review and then the final list will be sent to us for entry into ECO.

**Comment by mgiglio99** [comment]
April 5 - Randi sent the final version of terms for ECO review @
[eco_iedb_terms.xlsx](https://github.com/evidenceontology/evidenceontology/files/15278973/eco_iedb_terms.xlsx)

**Comment by nsuvarnaiari** [comment]
Hi Randi,

Requested new ECO terms and associated assertion terms have been created and released today.
Please refer to this excel sheet for the list of ECO ids and labels for new terms.
Thanks for working with us to get these terms added to ECO. Appreciate your help.

[IEDB_ECOrelease _terms.xlsx](https://github.com/user-attachments/files/15755581/IEDB_ECOrelease._terms.xlsx)

I was not able to create logical axioms with OBI assay terms as OBI terms were not imported into ECO. I will create them soon. Closing this ticket now but will open another ticket to capture creation of logical axioms. 

Thanks,
Suvvi
