### ISSUE TITLE
Additional terms for DisProt - Winter 2024

### ISSUE THREAD

**Issue by mgiglio99** [evidenceontology/evidenceontology#311]
Federica Quaglia has requested additional terms for DisProt which can be found here:
https://docs.google.com/spreadsheets/d/1pyhpkaPkKB3aXcZezVX2_pwmSyz2fUMBUzrWnOtSbO4/edit?usp=sharing

**Comment by mgiglio99** [comment]
Michelle and Suvvi provided comments on the request on March 29.
Notes are in google doc.

**Comment by mgiglio99** [comment]
Federica provided feedback on April 2 via email:

Thanks for reviewing our new terms requests. Please, find my comments below.
intrinsic disorder prediction evidence: I think the parent term could be "computational evidence", if it's fine with you.

combinatorial intrinsic disorder prediction and author inference evidence and combinatorial intrinsic disorder prediction and curator inference evidence: Based on the provided comment, please let me know if these revised terms work for you: "Intrinsic disorder prediction with author inference evidence" and "Intrinsic disorder prediction with curator inference evidence". To answer your question: in this context, I am specifically referring to computational predictions.
Could these two terms, if approved, be child terms of the newly drafted "intrinsic disorder prediction evidence"?
Please let me know your thoughts on this and of course if needed we can schedule a call.

Thanks again, I wish you both a lovely day.

Federica

**Comment by mgiglio99** [comment]
Response back from Suvvi and Michelle via email on May 1:

Hi Federica,
Sorry for the huge delay in getting back to you.

Suvvi and I were looking at this and we like the terms that you suggested in your reply to our comments. There are two ways we could construct these terms – with the prediction part as the primary axis or with the inference part as the primary axis. They will have an asserted parent that is the primary axis and an inferred parent to include the secondary axis. These would be captured in logical axioms.

Here are possible options:

Inference as the primary axis:
author inference based on intrinsic disorder prediction
curator inference based on intrinsic disorder prediction

Prediction as the primary axis:
intrinsic disorder prediction employed in author inference
intrinsic disorder prediction employed in curator inference

**Comment by mgiglio99** [comment]
Federica chose option 1.
Suvvi and Michelle finalized terms May 17 and sent to Federica for review:

ECOnew: intrinsic disorder prediction evidence
Def: A type of computational evidence where one or more computational tools are used to predict regions of intrinsic disorder in a protein sequence.
Parent: ECO:0007672 'computational evidence'

ECOnew: author inference based on intrinsic disorder prediction
Def: A type of author inference evidence in which information from intrinsic disorder prediction tools has been employed. 
Parent:  ECO:0006185 'author inference'

ECOnew: curator inference based on intrinsic disorder prediction
Def: A type of curator inference evidence in which information from intrinsic disorder prediction tools has been employed. 
Parent: ECO:0000205 'curator inference'

**Comment by nsuvarnaiari** [comment]
The new eco terms and associated assertion terms have been created and released today.

ECO_id | ECO_label
-- | --
ECO:0008030 | intrinsic disorder prediction evidence
ECO:0008031 | author inference based on intrinsic disorder prediction
ECO:0008032 | curator inference based on intrinsic disorder prediction
ECO:0008033 | intrinsic disorder prediction evidence used in manual assertion
ECO:0008034 | intrinsic disorder prediction evidence used in automatic assertion
ECO:0008035 | author inference based on intrinsic disorder prediction used in manual assertion
ECO:0008036 | author inference based on intrinsic disorder prediction used in automatic assertion
ECO:0008037 | curator inference based on intrinsic disorder prediction used in manual assertion
ECO:0008038 | curator inference based on intrinsic disorder prediction used in automatic assertion

Thanks to Federica for her help on getting these terms into ECO.
