### ISSUE TITLE
Question about the meaning of "automatic assertion" evidence 

### ISSUE THREAD

**Issue by ValWood** [evidenceontology/evidenceontology#314]
Sorry, can of worms opening.....

Some of  our protein modification annotations, which are  experimental, but high-throughput use the ECO code

"tryptic phosphopeptide mapping assay evidence used in **automatic assertion"**

I was wondering exactly what this meant because, to me, **automatic assertion** is **non-experimental** and tryptic phosphopeptide mapping assay is clearly experimental  (we were importing some UniProt annotations which happen to use a different evidence code for the same paper "experimental evidence used in manual assertion" so they are not recognised as identical annotations)

I thought I would begin where I am familiar and so I looked up the definition of automatic assertion. This did not help me because 
**evidence used in automatic assertion**
is defined as
A type of evidence that is used in an automatic assertion.
author cjm @cmungall  ;)
This has the synonym (not sure of the scope) Synonym IEA inferred from electronic annotation

 in GO IEA is defined
Electronic annotation evidence code
‘Electronic’ (IEA) annotation are not manually reviewed (although the method itself is usually subjected to various quality assessments). IEA-supported annotations are ultimately based on either homology and/or other experimental or sequence information, but cannot generally be traced to an experimental source. Three methods make up the bulk of these annotations. The first, and most comprehensive, method is [InterPro2GO](https://www.ncbi.nlm.nih.gov/pubmed/27899635), which is based on the curated association of a GO term with a generalized sequence model (‘signature’) of a group of homologous proteins. Protein sequences with a statistically significant match to a signature are assigned the GO terms associated with the signature, a form of homology inference. A second method is the computational conversion of UniProt controlled vocabulary terms (including Enzyme Commission numbers describing enzymatic activities, and UniProt keywords describing subcellular locations), to associated GO terms. Lastly, annotations are made based on 1:1 orthologs inferred from Ensembl gene trees, an approach which automatically transfers annotations found experimentally in one gene, to its 1:1 orthologs in the same taxonomic clade (e.g. those within the vertebrate clade, and separately, those within the plant clade).

This  definition of automatic assertion doesn't really fit a tryptic phosphopeptide mapping assay 
but it seems that the ECO meaning of "automatic assertion" is not really equivalent to the GO 
"automatic assertion" in ECO is poorly defined, and  is used very loosely, this probably means that most descendants  might need to be revisited?

Thoughts? @cmungall   @mgiglio99

**Comment by ValWood** [comment]
For my reference. Consequences

every annotation from this dataset is duplicated :
<img width="1038" alt="consequences" src="https://github.com/user-attachments/assets/283e948c-7356-4dbc-8efa-31f5f406f266">

(we would filter if they were parent-child in the hierarchy, but these are in different parts. of the graph)
https://www.pombase.org/reference/PMID:18257517

**Comment by cmungall** [comment]
This is the relevant definition:

ECO:0000203 ! automatic assertion "An assertion method that does not involve human review."

This doesn't precisely align with the GO definition "but cannot generally be traced to an experimental source", but I don't know what the GO text means. We propagate EC2GO as IEA but these are clearly traceable to an experimental source. IMO IEA is just some legacy thing that is hard to formalize, convenient for GO, but also that confuses users.

The term in question here has 2 subtypes for automated and manual (but both tracing to experimental)

<img width="653" alt="image" src="https://github.com/user-attachments/assets/adad9978-0747-4ff8-a8d8-cd970f4c111f">

I'm not sure if this triad pattern is the most meaningful or useful or intuitive but it's how ECO has worked for a while....

**Comment by ivanerill** [comment]
The way I understand it, "automatic assertion" is a type of assertion (the other one being manual), which generate cross products with evidence terms via the "used in" relationship. An automatic assertion is an assertion that is made by a machine, without human involvement. This can be "classic" algorithm (e.g. BLAST search), where the algorithm determines what are relevant hits for a sequence query. But it can also be an experimental setup where the apparatus makes calls on what is relevant or significant. For instance, in a _phosphopeptide mapping assay_, the mass spectrometry setup may make _automatic assertions_ based on attributes of the spectra. If that is what is reported (e.g. in a table) that would be an _automatic assertion_. Same for up- or downregulated genes at some pre-defined log-value cutoff in RNA-seq. If the researchers interpret some of their findings and conclude that some residues are clearly phosphorylated (or some genes most certainly induced) that would be a _manual assertion_ on the same ECO evidence. That is, at least, how I have always interpreted it, which means that it is not necessarily true that "automatic assertion" is "non-experimental".

**Comment by ValWood** [comment]
OK, got it!
So most  high throughput datasets would be "automatic assertions"

**Comment by mgiglio99** [comment]
Hi all, sorry to be late coming to the thread.
Thanks Chris and Ivan for jumping in.
Indeed 'automatic assertion' in ECO is not equivalent to "not experimental".
And Val, as for high-throughput datasets,  you are right that most will likely be automatic, but some could definitely be manual - it will come down to whether a human reviewed the output or not. 
Best,
Michelle

**Comment by ValWood** [comment]
Thanks all.

It seems that the GO evidence codes for HDA maps to the manual assertion evidence code (most are certainly automatic).
https://www.ebi.ac.uk/ols4/ontologies/eco/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FECO_0007005?lang=en

There may be some confusion here about what constitutes "manual". Just because a curator is happy with the method, and the threshold, and has done spot check validation, doesn't make it "manual"

and IEA is a synonym of high throughput direct assay evidence used in automatic assertion
which also doesn't seem quite right.

I'll open a ticket on the GO tracker about this (the correct usage isn't totally clear from the guidelines).

**Comment by hattrill** [comment]
Hi @ValWood HDA should be manual as the data should have been reviewed by a curator and added by 'hand' not by automatic propagation.

**Comment by ValWood** [comment]
I don't understand :)


I looked at the HTP paper, and it wasn't clear what the curator's role would be. It only describes reviewing the threshold, method and spot checking? It doesn't say that they need to "manually apply each annotation". What  would the curator be doing in these cases that a computer wasn't doing?

**Comment by hattrill** [comment]
You might add the IDs for the genes 'in bulk' but there will be checking and verification that does not happen with electronic annotation. You could add in bulk for IDAs, if the experiment didn't meet a HTP threshold.

We can also remove individual HTPs annotations if they conflict with other knowledge. 

Note IBAs are classed as manual.

**Comment by ValWood** [comment]
OK got it.

**Comment by mgiglio99** [comment]
Hi @ValWood 
Regarding this comment above:  "and IEA is a synonym of high throughput direct assay evidence used in automatic assertion which also doesn't seem quite right."
In fact, IEA is not a synonym of 'high throughput direct assay evidence used in automatic assertion' ECO:0007589, rather, it is the value in the "has GO evidence code" property. Term ECO:0007589 has no synonyms. We realize that the name of this property is confusing - we are working on changing it - what is should be is "maps to GO evidence code". The ECO:0007589 term should map to IEA if one was "rolling-up" annotations on more granular terms up to more general terms. IEA is a synonym for only one ECO term - that is ECO:0000501 'evidence used in automatic assertion'.
But many ECO terms that are more granular than GO evidence codes would map to IEA.
We described the process we adopted a few years ago for mapping GO evidence codes to ECO terms in the [2022 ECO NAR](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8728134/) paper in the "New ECO-to-GO evidence code mapping process" section. Also talked about it at a GO meeting a few years ago. Happy to delve into that more if you wish.
And clearly we need to change the name of that property since many people are getting confused by it.

**Comment by ValWood** [comment]
Thanks Michelle, that's clear now. I don't look at ECO often as we tend to use a limited set of evidence codes.

My issue will be resolved by UniProt  changing the evidence code they used from 
ECO:0001265 tryptic peptide phosphopeptide mapping assay used in manual assertion 
to match our 
ECO:0007464 tryptic peptide phosphopeptide mapping assay used in automatic assertion 
to suppress the duplication
so this one can close

**Comment by mgiglio99** [comment]
Ok, Thanks Val
