### ISSUE TITLE
OWL translation of restrictions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#33]
```
subsets should be translated to ONLY

See email
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 19 Dec 2013 at 7:04

**Comment by mchibucos** [comment]
@cmungall so to be clear, are you saying "subsetdef: valid_with_protein_complex 'Protein complex IDs should be used in the GO with/from field'" should be reworded as "subsetdef: valid_with_**only**_protein_complex 'Protein complex IDs should be used in the GO with/from field'". Or am I completely not understanding your [very old] request? Thank for advice!

**Comment by rctauber** [comment]
Hi @cmungall -
Curious to know if you'd still like to translate the subsets to OWL logical defs, as recommended in #26?

E.g.
Currently 'genetic interaction evidence used in manual assertion' has the following annotations:
`in_subset valid_with_gene`
`in_subset valid_with_protein`
`in_subset valid_with_protein_complex`

We would remove these and replace with:
`with only (protein or gene or 'protein complex')`

There is no `with` (or `valid with`) property that I know of, though. Do you have suggestions for what to use here?

**Comment by mchibucos** [comment]
Closing. Reopen if update is received from Chris.
