### ISSUE TITLE
Migrate to github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#44]
```
https://docs.google.com/document/d/1NfaeHWdZ7BcnaGFfh09X63L4LL7VG_8RNCrLyNdZ8wk/
edit#
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 13 Mar 2015 at 4:04

**Comment by mchibucos** [comment]
Added the logo to the organization. New logo reads "(EO)" instead of "(ECO)". In the future we might want to consider a different design than this one, which I created previously. I'm happy to have someone with logo/branding experience try to make a new logo.
