### ISSUE TITLE
IMP for non-GO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#47]
```
If I observe a mutant mouse has a phenotype P, is my observation backed by an 
IMP? Or is this intended purely from phenotype->function?
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 1 May 2015 at 6:06

**Comment by mchibucos** [comment]
Hi @cmungall We have been considering your question, but I'm afraid we require a bit more clarification. Can you elaborate a bit, or perhaps give us some examples?
Thanks!
Marcus & Suvvi

**Comment by rctauber** [comment]
Hi @cmungall - do you still have questions regarding this? We are still confused by the question and would appreciate more explanation. Thanks!

**Comment by mgiglio99** [comment]
We think this is more of annotation policy issue. Closing. Reopen if you feel term adjustments are needed.
