### ISSUE TITLE
IMP children terms 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#48]
```
In perusing Eco for mapping to the standard GO evidence codes, I am finding 
things that I would think should be children of the IMP and IGI terms in GO

example:
ECO:0000015 mutant phenotype evidence  DBXref GO:IMP

I would think
mutant visible phenotype evidence ECO:0000176
mutant physiological response evidence ECO:0000174

should be children of ECO:0000015, but they are not.

In fact, many of the terms that would be used to make an IMP annotation have no 
relationship to the IMP (eg, RNAi evidence, etc.).

ECO:0000011, genetic interaction evidence. SO I would have thought this would 
be equivalent to IGI. However, neither Dbxref or synonym is listed.
There IS genetic interaction evidence used in manual assertion ECO:0000316, 
which has an EXACT synonym to IGI, but no dbxref.
I would think however that ECO:0000011 would be the right mapping via dbxref to 
GO:IGI, since the child terms are all type of evidence used to claim IGI 
(complementation, double mutant pheno, etc., 

Harold Drabkin
```

Original issue reported on code.google.com by `hdrab...@gmail.com` on 8 Jun 2015 at 9:36

**Comment by nsuvarnaiari** [comment]
Hi Harold,

Thank you for your suggestions.  We have discussed the points you made in your comments.

First, we agree with your suggestion about moving mutant visible phenotype evidence ECO:0000176 and mutant physiological response evidence ECO:0000174 to be children of ECO:0000015. I will move them soon.

Regarding your question about IGI mapping to ECO:0000011, there is some established history here: All the GO codes were previously mapped to ECO terms in consensus with GO people (we worked with Chris Mungall @cmungall [LBL/GO] and Rachael Huntley [EMBL-EBI/UniProt GOA] on this in 2013). The file created by Rachael/Chris that contains the full set of ECO classes mapped to individual GO codes & GO references is here: http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt. These mappings have been in use by the GO. For example, look at AmiGO and try to filter on evidence: http://amigo.geneontology.org/amigo/search/annotation . You'll see the "...used in manual assertion" terms. Other groups beyond UniProt & GO have been starting to use the "evidence x assertion" terms, as well.

If there is a concern about these being improper mappings between GO codes & ECO terms, then I think GO tracker is probably a more appropriate place to initiate the discussion (unless it is to add a mapping using the same pattern). I do not think that it would be appropriate for ECO to undo/revise the mappings that, I believe, are accepted by GO at this point... But of course, we are happy to take part in any discussions and implement decisions agreed upon by GOC. If you raise this on GO's tracker, please do CC us on this! (@mchibucos)

You also mentioned that additional terms need to be moved under mutant phenotype evidence. Would you be able to provide us a list of such terms that need to be child terms of mutant phenotype evidence (ECO:0000015) but are not child terms of that term in the ontology? We would be happy to move existing terms or add new terms if needed, but we need to make sure that they serve the broader ECO user community and thus aren't too restrictive or specific to GO annotation methods...

Thank you,
Suvvi & Marcus

**Comment by rctauber** [comment]
Immediate issues are resolved. More work done on IMP in #117.
