### ISSUE TITLE
evidence based on logical inference

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evidenceontology/evidenceontology#49]
```
Hi,

We need a new evidence code to annotate automated logically inferred 
annotations. Actually we need 3 :)

The 2 first codes would distinguish between annotations inferred from manual 
and automated annotations:
- evidence based on logical inference from *manual* annotation used in 
automatic assertion
- evidence based on logical inference from *electronic* annotation used in 
automatic assertion

The third code, "evidence based on logical inference used in automatic 
assertion",  would be a parent of the other two. Adding such a parent, though 
it would not be used directly in the annotations themselves, would make it 
easier for processing the rules in our eco-usage-constraints [1] file.

"evidence based on logical inference" could be defined as "a unary inference 
that is automatic, or an inference chain in which at least one step is 
automatic."

Parent term could be either a new high-level, or we could consider the reasoner 
to be a specific type of curator?

Cheers,
Melanie

[1] 
https://github.com/geneontology/go-site/blob/master/metadata/eco-usage-constrain
ts.yaml 



```

Original issue reported on code.google.com by `mcour...@gmail.com` on 20 Jun 2015 at 6:33

**Comment by mcourtot** [comment]
Any news on this, and/or anything we (with @cmungall @tonysawfordebi) can do to help?

Thanks!

**Comment by mchibucos** [comment]
Discussed this on this week's GO Annotation call. I have added terms to eco-edit.obo, but have not made a release yet. I created an inferential evidence high level term to serve as parent to both curator inference and these computational evidence terms. I am still working on the relationships (and will modify a few) and tweaking the defs. But feel free to take a look to get a sense of where things stand.

**Comment by mcourtot** [comment]
Are those in the upcoming release, and is there a release date planned? Can we use the IDs from eco-edit.obo (i.e., are those confirmed as stable) in the meanwhile? Thanks!

**Comment by nsuvarnaiari** [comment]
Hi Melanie,
We have added the terms that you requested in this ticket. The terms are now available in the latest release of ECO (eco.obo and eco.owl) available at,
https://github.com/evidenceontology/evidenceontology

A quick update on the terms we added for you,
ECO:0000363 - evidence based on computational logical inference used in automatic assertion
ECO:0000366 - evidence based on logical inference from automatic annotation used in automatic assertion
ECO:0000364 - evidence based on logical inference from manual annotation used in automatic assertion
Please let us know if these terms do not serve your needs, we can change them.

Thanks,
Suvvi

**Comment by mchibucos** [comment]
Closing. Please reopen if any unresolved issues.
