### ISSUE TITLE
Evidence codes for IntAct

### ISSUE THREAD

**Issue by mcourtot** [evidenceontology/evidenceontology#61]
AI from the GOC 2015 Washington meeting

Here is a link to the doc we were looking at: http://www.ebi.ac.uk/intact/complex/documentation/, and which explains which ECO are currently being used by IntAct

Action item for Sandra and I (Melanie) is to look into the evidence codes used by IntAct: IPI and IDA in the export, as well as creating possible children of ECO:0000088 biological system reconstruction for combinatorial evidence, such as within and inter species (where species are related based on Compara orthology)

We will submit corresponding tracker items to ECO once we can properly define which extra terms we would need.

**Comment by bmeldal** [comment]
Hi Marcus,

Melanie Courtot (GO/GOA, EBI), Sandra Orchard and myself (

both IntAct, EBI) have come up with the following proposal for new ECO codes for complexes, aided by comments from Val Wood (Pombase, Cambridge, UK) & Steve Jupe (Reactome, EBI).
I'm attaching a diagram of the proposed is_a relationships.

We propose to place the new terms under the existing term:

ECO:0000088 biological system reconstruction

Def:
(Exi
![eco_new_complex_terms_hierarchy](https://cloud.githubusercontent.com/assets/10517124/11068524/9f5c8aa0-87c9-11e5-8837-5d403846cece.jpg)
![eco_new_complex_terms_hierarchy](https://cloud.githubusercontent.com/assets/10517124/11068534/acb425be-87c9-11e5-9926-4abc14e3da1e.jpg)

sting definition: 
“Evidence based on reconstruction of a biological system that is based on an existing experimentally supported model of that biological system” to be superseded by the below:)

A type of evidence used for the reconstruction of a biological system based either on a combination of experimental evidences or existing models of that system in a related species.

Comment:
The biological system in question might be a multi-step process or pathway or a physical complex comprising several components. The components in the experimental evidence can come from the same species or a mix of species.

1)
ECO:NEW1 biological system reconstruction by experimental evidence within a single species used in manual assertion
is_a ECO:0000088 biological system reconstruction
is_a ECO:0000353 physical interaction evidence
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence where the experimental evidence is provided by multiple experiments in a single species.

Comment: Processes, pathways and complexes shown by a single experiment should not be annotated with this term but with ECO:0000353 or a child thereof.

2)
ECO:NEW2 biological system reconstruction by experimental evidence from mixed species: conservation of sequence, function and composition used in manual assertion
is_a ECO:0000088 biological system reconstruction
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence where the experimental evidence is provided by a mix of species used in the same experiment. 

Comment:
Inference is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. The evidence may originate from a combination of several experiments.

3)
ECO:NEW3 biological system reconstruction by homology evidence: conservation of sequence, function and composition used in manual assertion
is_a ECO:0000088 biological system reconstruction
is_a ECO:0000252 similarity evidence
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence where the evidence is inferred by homology from an existing experimentally supported model to a process, pathway or complex in the same or another species.

Comment: Inference may be based on paralogy and/or orthology of the genome-encoded components and is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. Evidence may originate from a combination of several experiments. 

4)
ECO:NEW4 biological system reconstruction based on orthology evidence: conservation of sequence, function and composition used in manual assertion
is_a ECO:NEW3 biological system reconstruction by similarity evidence used in manual assertion: conservation of sequence, function and composition
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence where the evidence is inferred by orthology from an existing experimentally supported model to a process, pathway or complex in another species.

Comment: Inference is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. Evidence may originate from a combination of several experiments.

5)
ECO:NEW5 biological system reconstruction based on paralogy evidence: conservation of sequence, function and composition used in manual assertion
is_a ECO:NEW3 biological system reconstruction by similarity evidence used in manual assertion: conservation of sequence, function and composition
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence where the evidence is inferred by paralogy from an existing experimentally supported model to a process, pathway or complex in the same species.

Comment: Inference is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. Evidence may originate from a combination of several experiments.

6)
ECO:NEW6 biological system reconstruction based on inference from background scientific knowledge used in manual assertion
is_a ECO:0000088 biological system reconstruction [This is questionable as ECO:0000088 implies presence of related experimental evidence and complexes annotated with this term don’t have strong experimental evidence]
is_a ECO:0000306 inference from background scientific knowledge used in manual assertion
used_in ECO:0000218 manual assertion
Def:
A type of biological system reconstruction evidence based only on background scientific knowledge of that biological system. The available knowledge is usually a combination of partial or weak experimental evidence where either some components are missing or no physical interaction evidence can be found but the system is inferred by similarity to related systems in taxonomically-disparate organisms with experimental evidence. 

Comment: 
Functional studies or ligand binding evidence are often used for the reconstruction of biological systems. It does not provide physical interaction evidence but uses proxies such a ligand binding evidences to infer the presence or absence of the complex components.

**Comment by bmeldal** [comment]
I have no idea why it says I unassigned Melanie... I can't change that field.

**Comment by mchibucos** [comment]
Hi Birgit. Thank you for this information. I just wanted to acknowledge that I am looking it over.

I will add some comments here soon. In case it is helpful, might you have some availability for a conference call this week? (Feel free to email me and we can set something up.)

**Comment by bmeldal** [comment]
Great! Sending email.

**Comment by bmeldal** [comment]
ECO:0000088 biological system reconstruction
Updated definition 
A type of evidence based on either a combination of experimental evidences, which may be only partial or weak, or existing models of that system in a related species used for the reconstruction of a biological system.

**Comment by bmeldal** [comment]
Hi Melanie,

Here's the summary of small changes Marcus is going to do:

Parent term ECO:0000088:
Change the def a bit more to include NEW6 (see comment above)

NEW1:
change relationship to ECO:0000353 to "uses" or similar
@mchibucos we also just realised we have to change the Comment to:
"Comment: Complexes shown by a single experiment should not be annotated with this term but with ECO:0000353 or a child thereof."
because single reaction expts can be used to reconstruct processes and pathways.

NEW2:
@mchibucos, "used in manual assertion" is in the wrong place in the diagram but it's correct in the text.

NEW3:
a) @mchibucos, parent is ECO:0000252 similarity evidence used in manual assertion
I forgot to add "used in manual assertion" in the text/diagram but it's the correct term!

b) move "in the same or another species" from the def to the end of the comment.

NEW4:
Tweak def to make it clear that orthology refers to the components, not function.

NEW5:
In the diagram the name should have read "by paralogy". It's correct in the text but I copied the box of NEW4 and forgot to change the word!

NEW6:
Tweak the def a bit as a bit too verbose. Adding some of it to the new def of ECO:0000088 should help.
[NB: this term may one day be a nice example how ECO can link to the Confidence ontology...]

Any comments, please add them here :)

Marcus, do you want me to update the diagram and re-load?

I hope you feel better soon, Melanie!

Birgit

**Comment by bmeldal** [comment]
Left to do: 
Birgit and Sandra to find PMID or Complex ACs as examples for each use case.

**Comment by mcourtot** [comment]
Thanks Birgit!

I am not familiar with the Confidence ontology, anyone has any pointer?

**Comment by bmeldal** [comment]
Came out earlier this year, Sandra was a contributor (although she says her part was rather small in it).

The Confidence Information Ontology: a step towards a standard for asserting confidence in annotations
PMID:25957950
http://database.oxfordjournals.org/content/2015/bav043.long

**Comment by bmeldal** [comment]
Hi Marcus,

I have finally remembered to pick examples for the new codes:

New1 - multiple evidences:
EBI-6467993 - DNA polymerase III clamp loader complex (ecoli), PMID:19450514 (partial evidence)

New2 - mixed spp evidence:
EBI-10817173 (mouse) & EBI-10818080 (rat) - Vcp-Npl4-Ufd1 AAA ATPase complex, PMID:22232657

New4: parent of New4 & New5, see below

New4 - orthology evidence:
EBI-9349763 - activated SUMO1-E1 ligase complex (mouse), inferred from EBI-9345927 (human), PMID:15660128

New5 - paralogy evidence:
EBI-9349603 - activated SUMO2-E1 ligase complex (human), inferred from EBI-9345927 (human SUMO1-E1 ligase), PMID:15660128

New6 - inferred based on background knowledge
EBI-2325312 - Collagen type I trimer (human), PMID:17876790

Let me know if there is anything else you need.

Best wishes,
Birgit

**Comment by bmeldal** [comment]
Hi Marcus,

Have you got a timeline for the implementation of the new terms now? Or is there anything missing from me right now?

Thanks,
Birgit

**Comment by mcourtot** [comment]
Hi - I see the terms have been added (thanks!), but they seem to be missing some of the original comments. For example, we had suggested to add "Comment: 
Functional studies or ligand binding evidence are often used for the reconstruction of biological systems. It does not provide physical interaction evidence but uses proxies such a ligand binding evidences to infer the presence or absence of the complex components." for NEW6, which is now ECO:0005547.

Is there an easy way we could add those in?

**Comment by bmeldal** [comment]
We need another term!

ECO:NEW biological system reconstruction evidence based on homology evidence USED IN MANUAL ASSERTION

It'll be a is_a child of ECO:0005549 biological system reconstruction evidence based on homology evidence
With the same def as the parent (plus obviously USED IN MANUAL ASSERTION) and the same comment.

and should become an is_a parent of 
ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion
and
ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion

**Comment by bmeldal** [comment]
I also noticed some missing comments: 

(@mcourtot, comments are there but in the 'metadata' tab on ols beta. I complained to SPOT and they'll be moving everything on one page with the next release!)

ECO:0005544 biological system reconstruction evidence based on orthology evidence used in manual assertion
should have the same comment as
ECO:0005545 biological system reconstruction evidence based on orthology evidence

and

ECO:0005550 biological system reconstruction evidence based on paralogy evidence
should have the same comment as
ECO:0005546 biological system reconstruction evidence based on paralogy evidence used in manual assertion

Thanks.

**Comment by bmeldal** [comment]
In fact, ECO:0005546 biological system reconstruction based on paralogy evidence used in manual assertion is missing 'evidence' after 'reconstruction'! All other terms in this branch have the same pattern of wording.

When you do the changes, please make sure all terms have the appropriate comment. I may have missed something...

**Comment by nsuvarnaiari** [comment]
Hi Birgit,

Sorry for the delay in adding the comments and edits you mentioned in your previous messages. 

I have added all the comments and also the term biological system reconstruction evidence based on homology evidence used in manual assertion. I request you to go over the node once again to make sure all the comments are present. These edits are in the latest commit of eco-edit.obo file. Will do a release soon.
I will keep the ticket open for you to comment after you review the nodes.

Thanks,
Suvvi

**Comment by bmeldal** [comment]
Thanks, Suvvi.

Could you please give me the link where the file is as I normally go in via OLS.

Thanks,
Birgit

**Comment by mchibucos** [comment]
Hello Birgit,
Take a look at the file here:
https://github.com/evidenceontology/evidenceontology/blob/master/eco-edit.obo
To download the file, click the button "Raw" which will take you here:
https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco-edit.obo
This file can be downloaded and opened in OBO-edit. Thanks!
--Marcus

**Comment by bmeldal** [comment]
Hi Suvvi,

Comment on ECO:0005610 should be:
"Inference may be based on paralogy and/or orthology of the genome-encoded components and is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. Evidence may originate from a combination of several experiments in the same or another species."
(just adding the "in the same or another species").

Comment on ECO:0005549 should be:
"Inference may be based on paralogy and/or orthology of the genome-encoded components and is made primarily on functional conservation between the two systems. The sequences and number of genome-encoded components are fairly conserved but some divergence is observed. Evidence may originate from a combination of several experiments in the same or another species."
(adding the "and" to "or orthology" as it is parent to both, homology and orthology. You added this to the new term (above) and I agree!)

I think all other comments are correct now.

Thanks again,
Birgit

**Comment by bmeldal** [comment]
Marcus, I hope you are not up in the middle of the night but not in your usual time zone! Thanks for the quick reply with the link.

**Comment by nsuvarnaiari** [comment]
Hi Birgit,

I have made the edits you posted in your last comment in our edit version of ECO. You will be able to see them in the next release. Thanks for all your help.

I am closing the ticket now, but pls reopen if needed.

Suvvi
