### ISSUE TITLE
disk diffusion assay evidence

### ISSUE THREAD

**Issue by dsiegele** [evidenceontology/evidenceontology#64]
To test for sensitivity/resistance to an antimicrobial agent, cells are spread over the surface of solid growth medium, then incubated with a disc of filter paper to which the antimicrobial agent to be tested is applied.  A zone of growth inhibition surrounding the disc is evidence for sensitivity.  

Ref: Prescott's Microbiology
ISBN:9780073402406

exact synonym: zone of inhibition evidence

**Comment by nsuvarnaiari** [comment]
Hi Debby,

I have added the term disk diffusion test evidence (ECO:0005605).
is_a experimental evidence

Closing the ticket now but pls reopen if needed.

Thanks,
Suvvi
