### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by cmungall** [evidenceontology/evidenceontology#65]
See: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/34

Recommend: CC-BY

**Comment by mchibucos** [comment]
Chris, it was previously CC BY-SA 2.0. Is this a problem?

**Comment by cmungall** [comment]
I don't know - what to start a ticket on the OBO tracker?

Whatever is chosen, unfortunately it has to go in a few different places

here - http://obofoundry.org/ontology/eco.html
and in the header of the ontology

(we have scripts to ensure these are in sync)

**Comment by mchibucos** [comment]
Added ticket https://github.com/OBOFoundry/OBOFoundry.github.io/issues/239
