### ISSUE TITLE
add text mining evidence

### ISSUE THREAD

**Issue by nlwashington** [evidenceontology/evidenceontology#66]
There should be some kind of automatic assertion types that come from text mining, maybe as a child of automatic assertion?

name:  text mining evidence

**Comment by nsuvarnaiari** [comment]
Hi Nicole,

Please send us some use cases or some documentation describing text mining when ever you get a chance. It will be easy for us to understand.

Thanks,
Suvvi

**Comment by cmungall** [comment]
Item 7 here: http://human-phenotype-ontology.github.io/documentation.html

**Comment by rctauber** [comment]
#106 includes a request for inferred from text mining (ITM) from HPO - going to close this issue to consolidate discussion on one thread.
