### ISSUE TITLE
New terms requested

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#73]
Hello, 

We'd like to request the following terms to be added to ECO: 
- in gel protein kinase assay (child of in vitro assay evidence) 
- macroscopic current trace (child of electrophysiology assay evidence)
- current density (child of electrophysiology assay evidence)
- single channel conductance (child of electrophysiology assay evidence)
- sustained current (child of electrophysiology assay evidence)
-steady state activation curve (child of electrophysiology assay evidence)
- steady state inactivation curve (child of electrophysiology assay evidence)
- window current trace (child of electrophysiology assay evidence)
- use dependence of inactivation (child of electrophysiology assay evidence)

Can you add the following terms from birnlex: (we'd rather only use a single vocabulary)
Children of electrophysiology assay evidence
- birnlex_2278 current clamp voltage recording protocol (http://neurolex.org/wiki/Category:Current_clamp_voltage_recording_protocol)
- birnlex_2281 whole-cell voltage clamp recording protocol (http://neurolex.org/wiki/Category:Whole-cell_voltage_clamp_recording_protocol)
- birnlex_2283 cell-attached single-channel recording protocol (http://neurolex.org/wiki/Category:Cell-attached_single-channel_recording_protocol)
- birnlex_2286 cell-detached inside-out single-channel recording protocol (http://neurolex.org/wiki/Category:Cell-detached_inside-out_single-channel_recording_protocol)
- birnlex_2287 reconstituted bilayer single-channel patch recording protocol (http://neurolex.org/wiki/Category:Reconstituted_bilayer_single-channel_patch_recording_protocol)
- birnlex_2279 voltage clamp current recording protocol
- birnlex_2293 electroencephalography recording protocol

Thanks, 

Pascale

**Comment by mchibucos** [comment]
Hi Pascale. Working on these now. Do you have any additional information to share with us, such as PMIDs to these techniques, internal curation documentation that explains these terms, or anything like that? Not essential, but anything extra always helps!
We will add cross references to birnlex. Assuming these are all 1:1 mappings?
Marcus

**Comment by pgaudet** [comment]
Note that Neurolex is transitioning to a new system https://github.com/SciCrunch/NIF-Ontology/issues/31- not sure how you should build these cross-references.

**Comment by nsuvarnaiari** [comment]
Pascale decided not to use the following terms, hence obsoleted the terms
single channel conductance
steady state activation curve
steady state inactivation curve
window current trace
-----------------------------------------------------
3 new terms have been added.
name:  cell-detached outside-out single-channel recording evidence
name:  cut-open oocyte voltage clamp recording evidence
name:  macropatch voltage clamp recording evidence

All the terms now have definitions. Thanks to Pascale and Valerie for that.
