### ISSUE TITLE
New term request: super-resolution microscopy (SynapseGO)

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#74]
Hello, this issue is the start of new terms required for GO annotation of Synaptic Proteins.

term: super-resolution microscopy ([Wikipedia](https://en.wikipedia.org/wiki/Super-resolution_microscopy))

**Comment by mchibucos** [comment]
OK, great!

**Comment by nsuvarnaiari** [comment]
Added this term ECO:0005578 super-resolution microscopy evidence.

**Comment by Pimmelorus** [comment]
Thank you!
