### ISSUE TITLE
New ECO codes request from Claire O’Donovan

### ISSUE THREAD

**Issue by nsuvarnaiari** [evidenceontology/evidenceontology#75]
@odonovan@ebi.ac.uk, aleks@ebi.ac.uk

Their data are based on 5 techniques: FACS/flow cytometry, ELISA,
immunoelectron microscopy, western blotting and mass spectrometry. The
only high throuput method used in these studies is mass spectrometry.
Though it is associated with more than half of all the annotations, there
is still a significant input from other 4 methods, therefore a specific
ECO code will be required for each case.
We checked the available codes and discussed them and as a result we would
like to suggest to create these ECO evidence codes:

   * immunogold labelling evidence used in manual assertion (child of
     ECO:0000090 immunogold labelling evidence)
   * flow cytometry evidence used in manual assertion (child of
     ECO:0000268 flow cytometry evidence)
   * enzyme-linked immunoabsorbent assay evidence used in manual
     assertion (child of ECO:0000267 enzyme-linked immunoabsorbent assay
     evidence)
   * high throughput mass spectrometry evidence (child of ECO:0001096
     mass spectrometry evidence).  Reference PMID: 20805795 Mass
     spectrometry in high-throughput proteomics: ready for the big time.
   * high throughput mass spectrometry evidence used in manual assertion
     (child of high throughput mass spectrometry evidence

**Comment by zebrafishembryo** [comment]
Hello, 
This is Aleks. Any news or maybe more information needed to create these terms?
Best wishes

**Comment by nsuvarnaiari** [comment]
Hi Aleks,

I have added the first 3 terms in our edit version of ECO. I wanted to read the paper for the last 2 terms to understand what is the difference between high throughput mass spectrometry and a regular mass spectrometry. 
I did not read the paper yet but if you could explain briefly what is the scope of this term, it would be very helpful.

ECO:0005579 - immunogold labelling evidence used in manual assertion
ECO:0005580 - flow cytometry evidence used in manual assertion
ECO:0005581 - enzyme-linked immunoabsorbent assay evidence used in manual assertion


Thanks,
Suvvi

**Comment by zebrafishembryo** [comment]
Hi Suvvi, 

Thank you very much for the update! 
The main reason why we need this ECO evidence code is to have an opportunity to point out that certain GO annotations refer to the experimental data obtained in the high throughput studies. There will be quite a significant difference in a data analysis and data evaluation if to compare a HTP mass-spec and a regular mass-spec (not even mentioning the sample preparation). While the regular mass spec method is quite a reliable technique for identifying a protein molecular weight and analysing its post-modifications, other mass-spec applications might require the additional quality controls and more stringent data evaluation. Very briefly, the more complex sample mixture is processed (like in the cases of the HTP studies), more quality questions should be addressed, such as a sample contamination, sensitivity of the mass spectrometer and so on. In addition, while the analysis of the small data sets allows to manually assign the spectra to proteins or peptides, in the case of large data sets only the statistical tools can be used instead. 
I hope it helps. Let me know whether you need more information. 

Many thanks, 
Aleks

**Comment by nsuvarnaiari** [comment]
Hi Aleks, 

Thanks for the details. I am sorry for asking one more (not proficient in this area), can you provide a brief definition for this technique that makes it unique and different from regular mass spec. It can be one or 2 sentences. 
Eg: Mass spectrometry (MS) measures the mass-to-charge ratio of ions to identify and quantify molecules in simple and complex mixtures. 

Thanks,
Suvvi

**Comment by zebrafishembryo** [comment]
Hi Suvvi, 

Thank you very much for such a quick respond!
I tried to write the unique and explicit definitions for the terms as you asked. Hopefully, it helps. 

- high throughput mass spectrometry evidence (child of ECO:0001096 mass spectrometry evidence)
Possible definition:
_A type of a detection assay evidence based on measuring the mass-to-charge ratio (m/z) of gas-phase ions. The techniques is used to identify and quantify molecules in complex solutions within the framework of high throughput studies._

- high throughput mass spectrometry evidence used in manual assertion (child of high throughput mass spectrometry evidence)
Possible definition:
_A type of a detection assay evidence that is used in a manual assertion and based on measuring the mass-to-charge ratio (m/z) of gas-phase ions. The techniques is used to identify and quantify molecules in complex solutions within the framework of high throughput studies._

Cheers, 
Aleks

**Comment by mchibucos** [comment]
Hi Aleks, Suvvu,
Thanks for the explanation. Suvvi, much of this info could potentially be worked into term comments. (We can discuss in person.)
Marcus

**Comment by nsuvarnaiari** [comment]
Hi Claire, Aleks

I have added the last 2 terms as well.
ECO:0005585: high throughput mass spectrometry evidence
ECO:0005586: high throughput mass spectrometry evidence used in manual assertion

Thanks for all the help.
Closing the ticket now, but pls reopen if needed.

Suvvi
