### ISSUE TITLE
Rename: immunogold labelling evidence [GO synapse term request]

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#79]
I am sorting out ECO microscopy based evidences. Because I intend to request a term 'immunoperoxidase electron microscopy' I see the need arise to update the name of:

**immunogold labelling evidence [ECO_0000090]**
into 
**immunogold labelling _electron microscopy_ evidence [ECO_0000090]**

Moreover, in OLS I cannot see that you are not implementing correct/optimal relationships. For instance, now this relation is stored: 

**immunogold labelling evidence [ECO_0000090]** 
_is_a_ **protein assay evidence [ECO_0000039]**. 
Better would be:
**immunogold labelling evidence [ECO_0000090]** 
         _is_a_ **microscopy evidence [ECO_0001098]**
         _is_a_ **immunolocalization evidence [ECO_0000087]**

Thnx, Pim

Shoutout: @dosumis

**Comment by dosumis** [comment]
Seems that immunogold can be used in light microscopy too. 
[Wikipedia](https://en.wikipedia.org/wiki/Immunogold_labelling) has

"Although immunogold labeling is typically used for transmission electron microscopy, when the gold is 'silver-enhanced' it can be seen using brightfield microscopy.[11] "

From: 
Van Laere O, De Wael L, De Mey J (1985). "Immuno gold staining (IGS) and immuno gold silver staining (IGSS) for the identification of the plant pathogenic bacterium Erwinia amylovora (Burrill) Winslow et al". Histochemistry 83 (5): 397–9. doi:10.1007/BF00509198. PMID 2416717.

**Comment by dosumis** [comment]
Agree with Pim that there are some general issues with classification of the existing term:

![image](https://cloud.githubusercontent.com/assets/112839/13492811/2775dcd6-e132-11e5-8645-c1398ec819e9.png)

1. I don't understand what protein assay evidence is (no def).  If it is an assay that detects a protein or some activity of a protein, then immunolocalization doesn't belong under it - as the antibody may be detecting some non-protein epitope.
2. immunogold should be under immunolocalization
3. 'immunolocalization evidence'  is poorly defined: "A type of protein assay evidence that involves the use of antibodies to detect biomolecules."  This  is too broad - says nothing about locatlization, but clearly includes detection on a gel (Western blot - I'd use the term immunodetection for the general case). [Wiktionary defined immunolocalization](https://en.wiktionary.org/wiki/immunolocalization) has: "The use of immunological techniques to identify the location of molecules or other structures within cells or tissues."   Might want to extend this to specify localization via microscopy - in which case immunolocalization should (also) live under the microscopy evidence branch.

**Comment by dosumis** [comment]
We will also need the manual assertion XPs for any term we use.

Suggested classification:

direct assay evidence
.  imaging assay evidence
.  .  microscopy assay evidence
.  .  .  immunolocalization evidence
.  .  .  .  immunogold labelling evidence
.  .  .  .  .  immunogold labelling electron microscopy assay evidence
.  .  .  .  .  .  immunogold labelling electron microscopy assay evidence used in manual assertion
.  .  .  electron microscopy assay evidence
.  .  .  .  immunogold electron microscopy assay evidence
.  immunodetection assay evidence
.  .   immunolocalization evidence


Suggested defs:

immunodetection evidence: "A type of direct assay evidence that involves the use of antibodies to detect biomolecules."
(Might want to add Western blot under here and also under gel electrophoresis evidence.

immunolocalization evidence': "A type of microscopy evidence that uses antibodies to detect the location of molecules or other structures within cells or tissues."

(This would explicitly exclude fractionation -> Western blot under immunolocalization, but I think that is OK).

immunogold labelling evidence: "A type of immunolocalization evidence in which the antibodies used are labelled with colloidal gold particles whose location is then detected via microscopy.  Electron microscopy is typically used, but this technique can also be used with brightfield light microscopy (Van Laere, 1985)." [PMID:4110101,  PMID:2416717]

**Comment by dosumis** [comment]
One final general point: In the long run,  multiple inheritance classification like this really needs to be managed using reasoning.  For the microscopy side, it might be worth considering design patterns that reference the imaging ontology fbbi. https://github.com/PhenoImageShare/fbbi

**Comment by dosumis** [comment]
CC @nsuvarnaiari

**Comment by Pimmelorus** [comment]
> Seems that immunogold can be used in light microscopy too. 
Then the definition of the term needs to be updated. This now states 'electron microscopy'.

**Comment by dosumis** [comment]
>  Then the definition of the term needs to be updated. This now states 'electron microscopy'.

Yep.  See suggested defs above.

Also Just noticed this was your starting point: "'immunoperoxidase electron microscopy". Suggest something like this:

direct assay evidence
. imaging assay evidence
. . microscopy assay evidence
. . . immunolocalization evidence
. . . . immunoperoxidase immunolocalization evidence
. . . . immunoperoxidase immunolocalization electron microscopy evidence

**'immunoperoxidase immunolocalization evidence':** "A type of immunolocalization evidence involving enzymatic detection of a peroxidase tagged antibody.'

**Comment by dosumis** [comment]
@mchibucos - wondering when you might have time to start work on this and the other synapse tickets.  Happy to help out with edits if needed.

**Comment by mchibucos** [comment]
Thank you for the nudge, David. We're going to meet about this today, and I or Suvvi will be in touch later today.

**Comment by nsuvarnaiari** [comment]
Hi David and Pim,

Thanks for the valuable suggestions. Marcus and I went through the tickets. We agree with your suggestions. I started working on them and aiming for a Friday (March 18th) release after incorporating all the changes, definitions and new terms. Will update the ticket as soon as I am done with the release.

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Hi Pim,

A small clarification needed, I am looking at your term request ticket #82 (Immunoperoxidase labelling electron microscopy evidence), is this different from "immunoperoxidase immunolocalization electron microscopy evidence" mentioned in this ticket? 
If the 2 terms are different, it would be helpful if you could define immunoperoxidase labelling electron microscopy evidence.

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Hi Pim and David,

I have made all the changes suggested in this ticket. I have added new terms and definitions as well (also from ticket #77 and 78). You will find these edits in the recent commit of eco-edit.obo file. I request you to have a look at the terms and definitions and let me know if they need any more changes.
Please note that the secondary is_a  parents for some of the terms suggested in the ticket have not been added. As David mentioned, we want to manage multiple inheritance using reasoning but did not figure out how to do it efficiently yet. Please let us know if you have any suggestions.
Will work on other tickets tomorrow. 

Thanks,
Suvvi

**Comment by dosumis** [comment]
Thanks Suvvi, I'll take a look today.

> Please note that the secondary is_a parents for some of the terms suggested in the ticket have not been added. As David mentioned, we want to manage multiple inheritance using reasoning but did not figure out how to do it efficiently yet. 

These links are important to our project, so we'd like to get them in soon if at all possible - ideally in time for our project meeting in mid June.  I think the limited multiple inheritance we're asking for is manageable for now, but you should certainly use inference where possible. I'll have a think about design patterns you might be able to use for inference and get back to you.

**Comment by Pimmelorus** [comment]
@nsuvarnaiari 
**immunoperoxidase labelling electron microscopy** and **immunogold labelling electron microscopy** are different. immunoperoxidase labeling uses an antibody linked peroxidase enzyme that creates a staining via catalyzing a chemical reaction. immunogold labeling uses secondary antibodies coupled to gold beads that show up as electron dense spots in the EM images. So, two completely different visualization principles.

**Comment by nsuvarnaiari** [comment]
Hi David and Pim,

Thanks for a quick reply. I will add the secondary parents soon. I would greatly appreciate your suggestions on design patterns that we could implement.
Pim, actually you got the other term wrong. The terms in question are Immunoperoxidase labelling electron microscopy evidence and immunoperoxidase immunolocalization electron microscopy evidence. The former term is from the ticket #82 and latter in this ticket.

Thanks,
Suvvi

**Comment by Pimmelorus** [comment]
@nsuvarnaiari 
Ah sorry I misunderstood you. No these terms are synonymous.

**Comment by mchibucos** [comment]
Thanks everyone for all of these helpful comments & contributions. I have created a separate ECO ticket (#88) regarding design pattern and multiple inheritance (see David's comments above). Let's include some examples from this microscopy work, but also examples from throughout ECO. David & Pim, do feel free to add any comments you think can be helpful.
Marcus

**Comment by nsuvarnaiari** [comment]
Hi Pim and David,

I have added the secondary parents. Will close the ticket once you confirm that all the terms, changes are in place. I made another commit few min back adding terms from other tickets as well.

Thanks,
Suvvi

**Comment by Pimmelorus** [comment]
@nsuvarnaiari 
Where can we check the current implementation?

**Comment by dosumis** [comment]
> Where can we check the current implementation?

Currently appear to be just in the edit file: https://github.com/evidenceontology/evidenceontology/blob/master/eco-edit.obo
It's human readable - or you could open in a standard editor (OBO-Edit or Protege).

After a release is run, it should be browsable here: http://www.ebi.ac.uk/ols/beta/ontologies/eco

@nsuvarnaiari  - do you have a release scheduled?  (Looks like it's a simple Makefile job)

**Comment by mchibucos** [comment]
Hmmmm... I replied to Pim's question, but it didn't appear here on GitHub. Must be an email reply to GitHub issue... anyway, yes, I confirm that these newest terms are in eco-edit.obo. Suvvi was planning on doing the release on Friday, but after speaking we decided to do so after feedback on these latest terms. How do they look? If you are satisfied, we can do the release...

**Comment by dosumis** [comment]
Graph looks good: 

![image](https://cloud.githubusercontent.com/assets/112839/13914499/a0eead32-ef46-11e5-941f-1b6ce6887b8a.png)

**Comment by nsuvarnaiari** [comment]
Hi Pim and David,

I finished ECO release today. You should find all your terms and edits in the release files. I am closing the ticket but please reopen if more edits are needed.

Thanks,
Suvvi
