### ISSUE TITLE
Immunofluorescence wide-field microscopy evidence [GO synapse term request] 

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#80]
_is_a_ wide-field microscopy evidence [term requested]
_is_a_ immunofluorescence evidence [ECO_0000007]

**Comment by nsuvarnaiari** [comment]
Added the term immunofluorescence wide-field microscopy evidence (ECO:0005599)
is_a wide-field fluorescence microscopy evidence [ECO:0005598] (new term added under wide-field microscopy evidence)
is_a immunofluorescence evidence [ECO:0000007].
Closing the ticket.
