### ISSUE TITLE
Immunofluorescence confocal microscopy evidence [GO synapse term request] 

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#81]
_is_a_ confocal microscopy evidence [term requested]
_is_a_ immunofluorescence evidence [ECO_0000007]

**Comment by nsuvarnaiari** [comment]
Added the term immunofluorescence confocal microscopy evidence [ECO:0005600].
is_a confocal microscopy evidence [ECO:0005587]
is_a immunofluorescence evidence [ECO_0000007]
Closing the ticket now.
