### ISSUE TITLE
Immunoperoxidase labelling electron microscopy evidence [GO synapse term request]

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#82]
_is_a_ electron microscopy evidence [ECO_0005033]
_is_a_ immunolocalization evidence [ECO_0000087]

**Comment by nsuvarnaiari** [comment]
Added the term immunoperoxidase immunolocalization electron microscopy evidence [ECO:0005596] : synonym - Immunoperoxidase labelling electron microscopy evidence
is_a electron microscopy evidence [ECO_0005033]
is_a immunoperoxidase immunolocalization evidence [ECO:0005594]

Closing the ticket now.
