### ISSUE TITLE
Discuss: western blot evidence [ECO_0000112] [GO synapse term request] 

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#83]
Now this relation is is ECO:

**western blot evidence [ECO_0000112]**
_is_a_ **protein expression level evidence [ECO_0000046]**

However, western blot is not always a method for checking the expression. This depends on the preceding experiments (basically the samples on the blot). WB is basically a protein detection method based on a SDS-PAGE gel separation and immunodetection method. So better would be:

**western blot evidence [ECO_0000112]**
_is_a_ sodium dodecyl sulfate polyacrylamide gel electrophoresis evidence [ECO_0000333]
_is_a_ immunodetection evidence [term not present, but _is_a_ **protein essay evidence [ECO_0000039]** ]

Then, **protein expression level evidence [ECO_0000046]** can be based on western blotting, but this would require a term such as  **westernblot-based protein expression level evidence**.

Right now I feel that using the **western blot evidence [ECO_0000112]** for other terms is not correct in light of its current relationships.

**Comment by nsuvarnaiari** [comment]
Hi Pim, 

Thanks for the suggestions. We have incorporated all the changes you have mentioned.

1)western blot evidence [ECO_0000112]
is_a sodium dodecyl sulfate polyacrylamide gel electrophoresis evidence [ECO_0000333]
is_a immunodetection evidence [ECO:0005593]

2)protein expression level evidence based on western blot [ECO:0005602]
is_a western blot evidence [ECO_0000112]
is_a protein expression level evidence [ECO:0000046]

Closing the ticket now but pls reopen if this needs more work.
