### ISSUE TITLE
protein mass spectrometry evidence [GO synapse term request] 

### ISSUE THREAD

**Issue by Pimmelorus** [evidenceontology/evidenceontology#84]
_is_a_ mass spectrometry evidence [ECO_0001096]
 _is_a_ protein essay evidence [ECO_0000039]

**Comment by nsuvarnaiari** [comment]
Added the term protein mass spectrometry evidence [ECO:0005603]
is_a mass spectrometry evidence [ECO_0001096]
is_a protein essay evidence [ECO_0000039]

Closing the ticket now.
