### ISSUE TITLE
New entries needed in gaf-eco-mapping.txt

### ISSUE THREAD

**Issue by tonysawfordebi** [evidenceontology/evidenceontology#86]
Can you please add the following entries to gaf-eco-mapping.txt:

IEA	GO_REF:0000107	ECO:0000256
IEA	GO_REF:0000108	ECO:0000363

Thanks very much,
Tony

**Comment by nsuvarnaiari** [comment]
Hi Tony,

The two entries have been added in gaf-eco-mapping.txt file and xref'ed in edo-edit.obo file. Closing the ticket but pls reopen if needed.

Thanks,
Suvvi

**Comment by tonysawfordebi** [comment]
Thanks, Suvvi.

Cheers,
Tony
