### ISSUE TITLE
New term request: cell transfection

### ISSUE THREAD

**Issue by pgaudet** [evidenceontology/evidenceontology#87]
Hello,

- I'd like to request the term 'cell transfection experiment evidence'. 
- Definition: "A type of evidence in which nucleic acids into cells are introduced into cells. Using various chemical, lipid or physical methods, this gene transfer technology is a powerful tool to study gene function and protein expression in the context of a cell. (ref: http://ch.promega.com/resources/product-guides-and-selectors/protocols-and-applications-guide/transfection/)
- Child of 'experimental evidence'. 

I leave it up to you to create manual assertions or not :) 

Thanks. 
Pascale

**Comment by nsuvarnaiari** [comment]
Hi Pascale,

I have added the term cell transfection experiment evidence (ECO:0005606) in eco-edit.obo file. 
is_a: ECO:0000006 ! experimental evidence

Closing the ticket now but please reopen if needed.

Thanks,
Suvvi
