### ISSUE TITLE
Design pattern for ECO

### ISSUE THREAD

**Issue by mchibucos** [evidenceontology/evidenceontology#88]
This is an umbrella ticket for **ECO design pattern**. We need to establish rules for multiple inheritance classification, specifically managing it using reasoning. See #79 and #85 for examples of this issue being raised. In #79, David OS suggests considering design patterns that reference the imaging ontology fbbi: https://github.com/PhenoImageShare/fbbi

Collect examples and address our design pattern in this ticket.

**Comment by mchibucos** [comment]
Identifying and adhering to a main axis of classification is an ongoing area of work, which is relevant to this topic. How do we decide which is_a parent class to use when multiple terms are suggested by a user? For example:
immunogold labelling evidence [ECO_0000090]
is_a microscopy evidence [ECO_0001098]
is_a immunolocalization evidence [ECO_0000087]
The idea is that we would have _one_ is_a parent, and any other related terms would be handled by logical definition.

**Comment by dosumis** [comment]
> Identifying and adhering to a main axis of classification is an ongoing area of work, which is relevant to this topic. How do we decide which is_a parent class to use when multiple terms are suggested by a user.

I'd advise not worrying too much about a primary axis of classification: just formalise whichever classifications you can. This requires finding a third party ontologies that are of high enough quality and which is maintained.  It then requires deciding on relations to use to relate your terms from this third party ontology to your own.

From fbbi, terms under [microscopy](http://www.ebi.ac.uk/ols/beta/ontologies/fbbi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbi_00000241) may be useful. Also terms under [sample preparation method](http://www.ebi.ac.uk/ols/beta/ontologies/fbbi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbi_00000001) and [visualization method](http://www.ebi.ac.uk/ols/beta/ontologies/fbbi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbi_00000031)

OBI may be a good source or relations to use.

**Comment by cmungall** [comment]
+1 to David's comments. All you need to worry about are the design patterns for the logical definitions themselves. The reasoner will take care of the hierarchy, whether it's SI or MI.

I recommend making a start on the design patterns writing them in yaml following the format here:
https://github.com/dosumis/dead_simple_owl_design_patterns

**Comment by dosumis** [comment]
Here's an example of a (dead simple owl design) pattern doc for the pattern you already implicitly use for evidence used in assertion:

https://github.com/dosumis/dead_simple_owl_design_patterns

https://gist.github.com/dosumis/3f57e9f38ec5f68f3db3

**Comment by mchibucos** [comment]
Closing. Ongoing OBI-ECO mapping work has been addressing the design pattern.
