### ISSUE TITLE
New Term Request- Capillary Assay

### ISSUE THREAD

**Issue by KristenKC** [evidenceontology/evidenceontology#90]
Source: PMID:4632978
Definition: A method used to determine the presence or absence of positive or negative chemotaxis in swimming organisms- typically bacteria or archaea- by measuring the rate of accumulation into a capillary. 
	To determine the presence of positive chemotaxis, an attractant is placed in the capillary and the presence of positive chemotaxis is determined based on the amount of organism that accumulated in the capillary.	
	To determine the presence of negative chemotaxis, a repellent is added to the organismal suspension (but not in the capillary) and the organisms that fled into the capillary are measured.

**Comment by nsuvarnaiari** [comment]
This term has been added.
capillary assay evidence (ECO:0005609)
is_a: ECO:0005021 ! chemotaxis assay evidence

Closing the ticket. Please reopen if needed.

Thanks,
Suvvi
