### ISSUE TITLE
New Term Request- Temporal Assay

### ISSUE THREAD

**Issue by KristenKC** [evidenceontology/evidenceontology#91]
Source: PMID:4576832
Definition: A method used to determine the presence or absence of positive or negative chemotaxis in swimming organisms by measuring chemotaxis in response to sudden concentration changes from one uniform spatial environment to another. 
Synonyms: Tumble frequency assay

**Comment by nsuvarnaiari** [comment]
The term has been added.
tumble frequency assay evidence (ECO:0005608) - Looks like this name is used more than temporal assay hence made temporal assay evidence a synonym.
is_a: ECO:0005021 ! chemotaxis assay evidence

Closing the ticket. Please reopen if needed.

Thanks,
Suvvi
