### ISSUE TITLE
New Term Request- Tethered Cell Assay

### ISSUE THREAD

**Issue by KristenKC** [evidenceontology/evidenceontology#92]
Source: PMID: 1103143	
Definition: A method used to determine the presence or absence of positive or negative chemotaxis in swimming organisms by observing the rotational behavior of the organism tethered to a coverslip by their flagella.

**Comment by nsuvarnaiari** [comment]
Hi Kristen,

The term has been added.
tethered cell assay evidence (ECO:0005607)
is_a: ECO:0005021 ! chemotaxis assay evidence

Closing the ticket. Please reopen if needed.

Thanks,
Suvvi
