### ISSUE TITLE
Add analytics to ECO website

### ISSUE THREAD

**Issue by mchibucos** [evidenceontology/evidenceontology#96]
Dustin @dolleyj ,
We should explore a means to track ECO site visits, etc. Can you please look into this? Google best? Alternatives? Thanks!
Marcus

**Comment by dolleyj** [comment]
No problem. I'll look into it and get back to you.

**Comment by dolleyj** [comment]
It seems Google Analytics might be the best option, especially since the new site uses a gmail account for handling emails. That would put email and analytics under one roof :)

**Comment by rctauber** [comment]
Google Analytics is up on the site. Reopen if necessary!
