### ISSUE TITLE
Umbrella issue for HT (high throughput) terms for Gene Ontology

### ISSUE THREAD

**Issue by mchibucos** [evidenceontology/evidenceontology#97]
Please use this ticket to track any GO-related HT term issues, per discussions held at the GO meeting in Switzerland.
--Marcus

**Comment by rctauber** [comment]
GO has requested the following:

> We (the HTP working group) have come to a mementos decision and would like to ask if you could make some more flavours of HTP evidence codes.
> 
> Below is the GO shorthand (name and three-letter code) for xref. Note these mappings would be for manual assertion only i.e. 'high throughput…...used in manual assertion'.
> 
> inferred from high throughput mutant phenotype (HMP)
> inferred from high throughput genetic interaction (HGI)
> inferred from high throughput direct assay (HDA)
> inferred from high throughput expression pattern (HEP)
> 
> Just to note that you have already provided: ECO:0006056 'high throughput evidence used in manual assertion' which would map to the 'inferred from high throughput experiment' (HTP) for GO.

**Comment by rctauber** [comment]
@nsuvarnaiari @jbmunro I've created a ROBOT sheet for the above terms... if you have a chance could you look over the definitions? They are mainly used from their low-throughput counterparts.

https://docs.google.com/spreadsheets/d/1dTRaHJeDds3ycEvjyaRvWhRG4kIk1-SG7dcdFQkoCOU/edit?usp=sharing

**Comment by hattrill** [comment]
Thanks, Becky. Sounds like a good strategy. I’ll look at them today.

Best, Helen

**Comment by hattrill** [comment]
I've HTP made some slight modifications to the definitions - under the tab "HTP_modified" on the spreadsheet.  But otherwise looks good to me.

Do you allow multiple parents? They could also have a Is_a to the corresponding low throughput equivalent.

Could I also ask you to modify the parent terms ECO_0006055 and ECO_0006056 so that they remove the "large numbers of" reference as they are not always large. e.g. A type of evidence where data generation is automated with equipment to allow for assaying samples or molecules in parallel. 

Thanks

**Comment by rctauber** [comment]
Thanks @hattrill !
Re: multiple parents... We do have a handful of terms in ECO now that have multiple inheritance, but they've given us some issues for our OBI integration project. Ideally, we would have one asserted parent, then the logic from the OBI mappings would allow for inference of the second parent. As we haven't implemented this logic in the live version of ECO yet, I'm ok with asserting these parents for now. They will be later removed and inferred, though.

I'll fix the HTP defs now. As for the defs for the other terms, our definition pattern is typically "A type of [parent class] that/where/derived from/etc..." so the only thing I would change is to replace evidence with "high throughput evidence" in there. If that's okay with you, I think we're good to go!

**Comment by hattrill** [comment]
That sounds fine to me. Let's go! And thank you!

**Comment by hattrill** [comment]
Tagging @cmungall

**Comment by rctauber** [comment]
@hattrill @cmungall - is everything good with these terms? I'm proposing to close this issue if so, unless there are other HT terms that GO needs. Thanks! 😄

**Comment by hattrill** [comment]
Nothing further needed. Many thanks.

**Comment by hattrill** [comment]
Hi @rctauber , @mchibucos - 
Excuse me for this highly inappropriate use of an issue tracker, but thought it was kind of a good place to contact you!

I am attempting to put something togther for the ISB DATABASE Journal Biocuration issue (deadline 31st Oct!) about annotating high throughput data using the GO. As you both worked on this, I was going to put you down as authors. If you want to look over the draft it is here - 
https://docs.google.com/document/d/1UGXWy38134Lvq22qb2tVizIgNUhZKQC1x5-docMb-ro/edit
in the GO google drive.

I've just made a doc for author names and details here - https://docs.google.com/document/d/16XW-iKZauIN9wisQDX77_fRt5adSyuGRoIF19eSjmWM/edit

If you need access, just shout.

**Comment by mgiglio99** [comment]
Note that issue https://github.com/evidenceontology/evidenceontology/issues/162 raises a question related to HT terms.
